---
title: "data_01_aps_investigations_codebook"
format: html
---

# Load the necessary packages
```{r}
#| warning: false
library(codebookr)
library(dplyr, warn.conflicts = FALSE)
library(haven)
```

# Purpose of the program

Using the CodebookR package, we will create a data dictionary for follow-up interview data for the DETECT project pertaining to APS.

# Load cleaned data
```{r}
#| warning: false
#Set working directory to location of rds files using 
#setwd("folder path") 
#or code may produce error
aps_investigations_import.rds <- file.choose()
apinve <- readRDS("aps_investigations_import.rds")
```

# Glimpse data with every column shown
```{r}
glimpse(apinve)
```

# Set column attributes

```{r}
# Create a vector of column names that have administrative data as the source
admin_vars <- apinve %>% 
  select(1:9, 14:17) %>%  # Choose the appropriate columns in the data frame
  names()
#Set source of admin_vars to "Administrative data"
for(i in admin_vars) {
  attr(apinve[[i]], "source") <- "Administrative data"
}
```

```{r}
# Create a vector of column names that have APS Investigations data from DETECT Follow-up Interview as the source 
aps_vars <- apinve %>% 
  select(10:13, 18) %>% # Choose the variables from the raw data excluding administrative data
  names()

for(i in aps_vars) {
  attr(apinve[[i]], "source") <- "DETECT Follow-up Interview APS Investigations"
}

# Create a vector of column names that have the same source, in this case recoded factor variables
factor_vars <- apinve %>% 
  select(19:26) %>%  #Choose the recoded variables
  names()

for(i in factor_vars) {
  attr(apinve[[i]], "source") <- "Recoded from raw data"
}
```

```{r}
# Add column attributes to all variables
apinve <- apinve %>%
      cb_add_col_attributes( 
      x_primary_key, 
      description = "Unique identifier for record"
    ) %>%
  
    cb_add_col_attributes( 
      x_created_by, 
      description = "Person who created the record"
    ) %>%
  
    cb_add_col_attributes( 
      x_created_timestamp, 
      description = "Timestamp when the record was created",
      col_type = "Time"
    ) %>%
  
    cb_add_col_attributes( 
      x_modified_by, 
      description = "Person who modified the record"
    ) %>%
  
    cb_add_col_attributes( 
      x_modified_timestamp, 
      description = "Timestamp when the record was modified",
      col_type = "Time"
    ) %>%
  
    cb_add_col_attributes( 
      x_error_message, 
      description = "Error message entered by research team"
    ) %>%
  
    cb_add_col_attributes( 
      x_record_month, 
      description = "Month record was created",
      col_type = "Time"
    ) %>%
  
    cb_add_col_attributes( 
      x_record_year, 
      description = "Year record was created",
      col_type = "Time"
    ) %>%
  
    cb_add_col_attributes( 
      x_record_status, 
      description = "Status of the record as determined by research team"
    ) %>%
  
    cb_add_col_attributes( 
      x_record_comment, 
      description = "Comments by interviewer"
    ) %>%
  
      cb_add_col_attributes( 
      xc_case_i_d, 
      description = "Unique case ID"
    ) %>%
  
        cb_add_col_attributes( 
      xc_lead_panel_summary_count, 
      description = "Count of lead panel summaries for older adult"
    ) %>%
  
    cb_add_col_attributes( 
      medstar_id, 
      description = "Unique record number in MedStar System"
    ) %>%
  
    cb_add_col_attributes( 
      name_full, 
      description = "Full name of older individual"
    ) %>%
  
    cb_add_col_attributes( 
      aps_report, 
      description  = "AI_1. Has anyone from Adult Protective Services ever attempted to investigate whether or not you were living with elder abuse or neglect?", 
      skip_pattern = "Skip to section 6 if any answer is given but Yes"
    ) %>%
  
    cb_add_col_attributes( 
      aps_times, 
      description  = "AI_2. How many times has this happened in your life?",
      skip_pattern = "If answer is 0 or Refused, go to Section 6. If answer is 1 go to AI_4."
    ) %>%
  
    cb_add_col_attributes( 
      aps_first, 
      description  = "AI_3. When was the first time APS attempted to do an investigation?",
      skip_pattern = "If answer is Refused, go to Section 6."
    ) %>%
  
    cb_add_col_attributes( 
      aps_recent, 
      description = "AI_4. When was the most recent time APS attempted to do an investigation?"
    ) %>%
  
    cb_add_col_attributes( 
      aps_report_4cat, 
      description  = "Recoded variable aps_report to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1, 
        "No"         = 2, 
        "Don’t know" = 7, 
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      aps_report_4cat_f, 
      description = "Recoded variable aps_report as a factor variable"
    ) %>%
  
    cb_add_col_attributes(
      aps_times_5cat, 
      description = "Recoded variable aps_times to match levels in follow-up interview protocol",
      value_labels = c(
        "0"          = 0, 
        "1"          = 1, 
        "2+"         = 2, 
        "Don’t know" = 7, 
        "Refused"    = 9),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      aps_times_5cat_f, 
      description = "Recoded variable aps_times as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      aps_first_8cat, 
      description = "Recoded variable aps_first to match levels in follow-up interview protocol",
      value_labels = c(
        "10 or more years ago"                       = 1, 
        "5-10 years ago"                             = 2, 
        "1-5 years ago"                              = 3, 
        "In the past year but more than a month ago" = 4, 
        "In the past month"                          = 5, 
        "In the past week"                           = 6, 
        "Don’t know"                                 = 7,
        "Refused"                                    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      aps_first_8cat_f, 
      description = "Recoded variable aps_first as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      aps_recent_8cat, 
      description = "Recoded variable aps_recent to match levels in follow-up interview protocol",
      value_labels = c(
        "In the past week"                           = 1, 
        "In the past month"                          = 2,
        "In the past year but more than a month ago" = 3,
        "1-5 years ago"                              = 4,
        "5-10 years ago"                             = 5, 
        "10 or more years ago"                       = 6,
        "Don’t know"                                 = 7,
        "Refused"                                    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      aps_recent_8cat_f, 
      description = "Recoded variable aps_recent as a factor variable"
    )
```

# Exclude summary stats for certain variables in word doc

```{r}
#Create a vector of variables to exclude summary statistics from
no_stats <- apinve %>%
  select(1:9, 14:17)

no_stats_vars <- colnames(no_stats)

```


# Pass data frame to the codebook function
```{r}
#Add title, subtitle and description while excluding summary statistics for the specified variables
aps_codebook <- codebook(
  df = apinve,
  title = "Codebook ",
  subtitle = "APS Investigation Dataset",
  description = "Data collected during DETECT follow-up interviews regarding visits the patient may have had from Adult Protective Services", no_summary_stats = no_stats_vars 
)
```


```{r}
print(aps_codebook, "data_01_aps_investigations_codebook.docx")
```
