---
title: "Create Participant Codebook"
---

```{r}
# Load necessary packages
library(codebookr)
library(dplyr, warn.conflicts = FALSE)
library(readr)
source("../r/variable_descriptions.R")
```

# Purpose of the program

Using the CodebookR package, we will create a data dictionary for follow-up interview data for the DETECT project.

# Load cleaned data

```{r}
#| warning: false
participant <- read_rds("../data/cleaned_rds_files/participant_import.rds")
```

# Set column attributes

```{r}
# Set the source to "Participant data" for all the variables
participant_vars <- participant %>%
  names()

for (i in participant_vars) {
  attr(participant[[i]], "source") <- "Participant data"
}
```

```{r}
# Choose variables that will not have summary statistics
no_stats <- participant %>%
  select(
    -c(age, race, matches("_[0-9]cat"), matches("xc_detect_positive_summary_count"))
  )


no_stats_vars <- colnames(no_stats)
```


```{r}
# Add column attributes to all variables
participant <- participant %>%
  cb_add_col_attributes(
    x_primary_key,
    description = "Unique record ID used internally by the database."
  ) %>%
  cb_add_col_attributes(
    x_created_by,
    description = "User who created the record."
  ) %>%
  cb_add_col_attributes(
    x_created_timestamp,
    description = "Timestamp when the record was created.",
    col_type = "Time"
  ) %>%
  cb_add_col_attributes(
    x_modified_by,
    description = "User who last modified the record."
  ) %>%
  cb_add_col_attributes(
    x_modified_timestamp,
    description = "Timestamp when the record was last modified.",
    col_type = "Time"
  ) %>%
  cb_add_col_attributes(
    x_error_message,
    description = "Any database error messages."
  ) %>%
  cb_add_col_attributes(
    x_record_month,
    description = "Related month of the record.",
    col_type = "Time"
  ) %>%
  cb_add_col_attributes(
    x_record_year,
    description = "Related year of the record.",
    col_type = "Time"
  ) %>%
  cb_add_col_attributes(
    x_record_status,
    description = "The records status."
  ) %>%
  cb_add_col_attributes(
    medstar_id,
    description = "Record ID of the participant."
  ) %>%
  cb_add_col_attributes(
    name_full,
    description = "Full name of the participant."
  ) %>%
  cb_add_col_attributes(
    name_first,
    description = "First name of the participant."
  ) %>%
  cb_add_col_attributes(
    name_middle_initial,
    description = "Initial of the middle name of the participant."
  ) %>%
  cb_add_col_attributes(
    name_last,
    description = "Last name of the participant."
  ) %>%
  cb_add_col_attributes(
    name_suffix,
    description = "Name suffix of the participant."
  ) %>%
  cb_add_col_attributes(
    xc_case_id,
    description = "Last 5 characters of the MedstarID."
  ) %>%
  cb_add_col_attributes(
    x_address_original,
    description = "Participant's street address."
  ) %>%
  cb_add_col_attributes(
    city,
    description = "Participant's city of residence."
  ) %>%
  cb_add_col_attributes(
    state,
    description = "Participant's state of residence."
  ) %>%
  cb_add_col_attributes(
    zip_code,
    description = "Participant's zip_code."
  ) %>%
  cb_add_col_attributes(
    dob,
    description = "Participant's date of birth."
  ) %>%
  cb_add_col_attributes(
    x_randomizer,
    description = "Internal system variable used to randomize records."
  ) %>%
  cb_add_col_attributes(
    phone,
    description = "Participant phone number."
  ) %>%
  cb_add_col_attributes(
    x_call_order,
    description = "System variable used to track the order that participants should be called."
  ) %>%
  cb_add_col_attributes(
    incident_timestamp,
    description = "Coming from Medstar; Timestamp of when EMS was notified of the incident."
  ) %>%
  cb_add_col_attributes(
    unit_arrived_timestamp,
    description = "Coming from Medstar; Timestamp of when EMS arrived at the incident."
  ) %>%
  cb_add_col_attributes(
    medstar_internal_id,
    description = "Coming from Medstar; Internal ID number for the incident."
  ) %>%
  cb_add_col_attributes(
    ems_response_number,
    description = "Coming from Medstar; EMS response number."
  ) %>%
  cb_add_col_attributes(
    complaint_reported,
    description = "Coming from Medstar; Compliants reported by dispatch for patient."
  ) %>%
  cb_add_col_attributes(
    age,
    description = "Participant's age in years."
  ) %>%
  cb_add_col_attributes(
    incident_result,
    description = "Coming from Medstar; Result of the incident."
  ) %>%
  cb_add_col_attributes(
    ems_crew_member,
    description = "Coming from Medstar; Name of the EMS crew member that completed the report."
  ) %>%
  cb_add_col_attributes(
    symptom_list,
    description = "Coming from Medstar; participant list of symptoms."
  ) %>%
  cb_add_col_attributes(
    race,
    description = "Participant's racial identity."
  ) %>%
  cb_add_col_attributes(
    american_indian_alaska_native,
    description = "Dummy variable for participant American Indian or Alaska Native racial identity derived from race variable."
  ) %>%
  cb_add_col_attributes(
    asian,
    description = "Dummy variable for participant Asian racial identity derived from race variable."
  ) %>%
  cb_add_col_attributes(
    black_african_american,
    description = "Dummy variable for participant Black or African American racial identity derived from race variable."
  ) %>%
  cb_add_col_attributes(
    hispanic_latino,
    description = "Dummy variable for participant Hispanic or Latino ethnicity derived from race variable."
  ) %>%
  cb_add_col_attributes(
    middle_eastern_north_african,
    description = "Dummy variable for participant Middle Eastern or North African racial identity derived from race variable."
  ) %>%
  cb_add_col_attributes(
    native_hawaiian_other_pacific_islander,
    description = "Dummy variable for participant Native Hawaiian or other Pacific Islander racial identity derived from race variable."
  ) %>%
  cb_add_col_attributes(
    white,
    description = "Dummy variable for participant White racial identity derived from race variable."
  ) %>%
  cb_add_col_attributes(
    other_race,
    description = "Dummy variable for participant other racial identity derived from race variable."
  ) %>%
  cb_add_col_attributes(
    xc_incident_day_name,
    description = "Internal system variable."
  ) %>%
  cb_add_col_attributes(
    xc_incident_month_name,
    description = "Internal system variable."
  ) %>%
  cb_add_col_attributes(
    xc_incident_day,
    description = "Internal system variable."
  ) %>%
  cb_add_col_attributes(
    xc_incident_year,
    description = "Internal system variable."
  ) %>%
  cb_add_col_attributes(
    xc_record_month_year_abbr,
    description = "Internal system variable."
  ) %>%
  cb_add_col_attributes(
    x_is_archived,
    description = "Internal system variable."
  ) %>%
  cb_add_col_attributes(
    apt,
    description = "Participant's apartment number."
  ) %>%
  cb_add_col_attributes(
    address,
    description = "Participant's street address (reformatted)."
  ) %>%
  cb_add_col_attributes(
    x_usps_address_result,
    description = "Internal system variable."
  ) %>%
  cb_add_col_attributes(
    x_address_verified,
    description = "Internal system variable."
  ) %>%
  cb_add_col_attributes(
    x_call_order_initial,
    description = "Internal system variable."
  ) %>%
  cb_add_col_attributes(
    x_exclusion_reason,
    description = "Internal system variable."
  ) %>%
  cb_add_col_attributes(
    xc_call_order_even_odd,
    description = "Internal system variable."
  ) %>%
  cb_add_col_attributes(
    xc_participant_list_found_count,
    description = "Internal system variable."
  ) %>%
  cb_add_col_attributes(
    x_aps_reported_confirmation_number,
    description = "Internal system variable."
  ) %>%
  cb_add_col_attributes(
    x_aps_reported_2cat_f,
    description = "Indicates if the medic submitted an APS report. It is no longer in use."
  ) %>%
  cb_add_col_attributes(
    incident_timestamp,
    description = "Internal system variable."
  ) %>%
  cb_add_col_attributes(
    xc_name_title,
    description = "Internal system variable."
  ) %>%
  cb_add_col_attributes(
    address_valid,
    description = ""
  ) %>%
  cb_add_col_attributes(
    address_updated,
    description = "Participant's address."
  ) %>%
  cb_add_col_attributes(
    apt_updated,
    description = "Participant's apartment number."
  ) %>%
  cb_add_col_attributes(
    city_updated,
    description = "Participant's city."
  ) %>%
  cb_add_col_attributes(
    zip_code_updated,
    description = "Participant's ZIP code."
  ) %>%
  cb_add_col_attributes(
    xc_address,
    description = "Internal system variable."
  ) %>%
  cb_add_col_attributes(
    xc_incident_date,
    description = "Internal system variable."
  ) %>%
  cb_add_col_attributes(
    xc_detect_positive_summary_count,
    description = "Internal system variable."
  ) %>%
  cb_add_col_attributes(
    x_do_not_call_2cat_f,
    description = "Internal system variable.",
    col_type = "Categorical"
  ) %>%
  cb_add_col_attributes(
    x_unusual_odor_5cat_f,
    description = "Are there unusual odors (e.g. urine, feces) that are unrelated to current medical conditions and/or are more extreme than expected given current medical conditions?"
  ) %>%
  cb_add_col_attributes(
    x_unmet_needs_5cat_f,
    description = "Is/Does the patient/older adult have unmet needs for assistance with eating, toileting, transferring, dressing, or bathing?"
  ) %>%
  cb_add_col_attributes(
    x_hoarding_medications_5cat_f,
    description = "Does the older adult appear to be hoarding/saving old medications?"
  ) %>%
  cb_add_col_attributes(
    x_difficulty_medications_5cat_f,
    description = "Does the older adult have difficulties taking their prescribed medications as directed?"
  ) %>%
  cb_add_col_attributes(
    x_disarray_hoarding_5cat_f,
    description = "Is inside of home in extreme disarray/hoarding?"
  ) %>%
  cb_add_col_attributes(
    x_health_safety_concern_5cat_f,
    description = "Does the living environment pose a health or safety concern (e.g., fire hazard, insect or rodent infestation, urine or feces present)?"
  ) %>%
  cb_add_col_attributes(
    x_caregiver_lack_knowledge_5cat_f,
    description = "If caregiver present, do they appear to lack knowledge of the patient/older adult’s medical needs?"
  ) %>%
  cb_add_col_attributes(
    x_caregiver_unengaged_5cat_f,
    description = "If caregiver(s) present, do they appear unengaged an inattentive in caring for the patient/older adult?"
  ) %>%
  cb_add_col_attributes(
    x_caregiver_frustrated_5cat_f,
    description = "If caregiver(s) present, do they appear frustrated, tired, angry or burdened by the patient/older adult?"
  ) %>%
  cb_add_col_attributes(
    x_caregiver_anxious_5cat_f,
    description = "If caregiver(s) present, do they appear overly concerned (e.g., anxious, hovering)?"
  ) %>%
  cb_add_col_attributes(
    x_isolated_home_5cat_f,
    description = "Is the older adult isolated in the home and/or cut-off from needed social networks or supports?"
  ) %>%
  cb_add_col_attributes(
    x_depressed_5cat_f,
    description = "Does the older adult appear depressed, anxious, or emotionally distressed for reasons other than their immediate medical condition?"
  ) %>%
  cb_add_col_attributes(
    x_poor_personal_hygiene_5cat_f,
    description = "Does the older adult have poor personal hygiene (including soiled in urine or feces)?"
  ) %>%
  cb_add_col_attributes(
    x_inadequately_clothed_5cat_f,
    description = "Is the older adult inadequately clothed or wearing dirty, torn, or soiled clothing?"
  ) %>%
  cb_add_col_attributes(
    xc_detect_status_2cat_f,
    description = "Internal system variable.",
    col_type = "Categorical"
  ) %>%
  cb_add_col_attributes(
    sex_3cat_f,
    description = "Participant's sex.",
    col_type = "Categorical"
  )
```
# Create a data frame containing the column names and their descriptions using the df_descriptions function

```{r}
par_desc <- var_descriptions(participant)
```

## Save as rds file
```{r}
write_rds(par_desc, "../codebooks/variable_descriptions/participant_var_desc.rds")
```

# Pass data frame to the codebook() function

```{r}
# Add title and description to codebook
participant_codebook <- codebook(
  df = participant,
  title = "Participant Dataset",
  description = "",
  no_summary_stats = no_stats_vars
)
```

```{r}
print(participant_codebook, "../codebooks/participant_codebook.docx")
```
