---
title: "data_06_self_report_codebook"
format: html
---

```{r}
# Load necessary packages
library(codebookr)
library(dplyr, warn.conflicts = FALSE)
library(readr)
```

# Purpose of the program

Using the CodebookR package, we will create a data dictionary for follow-up interview data for the DETECT project pertaining to self-report injury, violence, neglect, and exploitation.

# Load cleaned data

```{r}
#| warning: false
self_report_import.rds <- file.choose()
sr <- readRDS(self_report_import.rds)
```

# Set column attributes

```{r}
#Set the source to "DETECT Follow-up Interview Questions Self Report" for all the variables
sr_vars <- sr %>% 
  select(1:353) %>% 
  names()

for(i in sr_vars) {
  attr(sr[[i]], "source") <- "DETECT Follow-up Interview Questions - Self Report"
}
```

```{r}
# Choose variables that will not have summary statistics
no_stats <- sr %>%
  select(1:14,346:353)

no_stats_vars <- colnames(no_stats)
```


```{r}
#Add column attributes to all self-report variables
self_report <- sr %>%
  cb_add_col_attributes( 
      x_created_by, 
      description = "Person who created the record"
    ) %>%
  
    cb_add_col_attributes( 
      x_created_timestamp, 
      description = "Timestamp when the record was created"
    ) %>%
  
    cb_add_col_attributes( 
      x_modified_by, 
      description = "Person who modified the record"
    ) %>%
  
    cb_add_col_attributes( 
      x_modified_timestamp, 
      description = "Timestamp when the record was modified"
    ) %>%
  
    cb_add_col_attributes( 
      x_error_message, 
      description = "Error message entered by research team"
    ) %>%
  
    cb_add_col_attributes( 
      x_record_month, 
      description = "Month record was created"
    ) %>%
  
    cb_add_col_attributes( 
      x_record_year, 
      description = "Year record was created"
    ) %>%
  
    cb_add_col_attributes( 
      x_record_status, 
      description = "Status of the record as determined by research team"
    ) %>%
  
    cb_add_col_attributes( 
      x_record_comment, 
      description = "Comments by interviewer"
    ) %>%
  
    cb_add_col_attributes( 
      medstar_id, 
      description = "Unique record number in MedStar System"
    ) %>%
  
    cb_add_col_attributes( 
      name_full, 
      description = "Full name of older individual"
    ) %>%

    cb_add_col_attributes( 
      neglect_go_4cat, 
      description = "SR_1a. Do you need someone to help you get to the places you need to go, for example do you need someone to drive you to the grocery store, a place of worship, the doctor?",
      skip_pattern = "If 'Yes', go to SR_1b. All other answers, go to SR_2a",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_food_4cat, 
      description = "SR_2a. Do you need someone to make sure you have enough food, medicines or any other things you need in your house?",
      skip_pattern =  "If 'Yes', go to SR_2b. All other answers, go to SR_3a",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_house_4cat, 
      description = "SR_3a. Do you need someone to help you with household things, like cooking meals, helping you eat, or making sure you take the correct medicines each day?",
      skip_pattern = "If 'Yes', go to SR_3b. All other answers, go to SR_4a",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_clean_4cat, 
      description = "SR_4a. Do you need someone to help you with house cleaning or yard work?",
      skip_pattern = "If 'Yes', go to SR_4b. All other answers, go to SR_5a",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_ready_4cat, 
      description = "SR_5a. Do you need someone to help you get out of bed, get showered, or get dressed?",
      skip_pattern = "If 'Yes', go to SR_5b. All other answers, go to SR_6a",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_bills_4cat, 
      description = "SR_6a. Do you need someone to make sure your bills get paid?",
      skip_pattern = "If 'Yes', go to SR_6b. All other answers, go to SR_7a",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_go_4cat_f, 
      description = "SR_1a. Do you need someone to help you get to the places you need to go, for example do you need someone to drive you to the grocery store, a place of worship, the doctor?",
      skip_pattern = "If 'Yes', go to SR_1b. All other answers, go to SR_2a"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_food_4cat_f, 
      description = "SR_2a. Do you need someone to make sure you have enough food, medicines or any other things you need in your house?",
      skip_pattern =  "If 'Yes', go to SR_2b. All other answers, go to SR_3a"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_house_4cat_f, 
      description = "SR_3a. Do you need someone to help you with household things, like cooking meals, helping you eat, or making sure you take the correct medicines each day?",
      skip_pattern = "If 'Yes', go to SR_3b. All other answers, go to SR_4a"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_clean_4cat_f, 
      description = "SR_4a. Do you need someone to help you with house cleaning or yard work?",
      skip_pattern = "If 'Yes', go to SR_4b. All other answers, go to SR_5a"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_ready_4cat_f, 
      description = "SR_5a. Do you need someone to help you get out of bed, get showered, or get dressed?",
      skip_pattern = "If 'Yes', go to SR_5b. All other answers, go to SR_6a"
    ) %>%
 
    cb_add_col_attributes( 
      neglect_bills_4cat_f, 
      description = "SR_6a. Do you need someone to make sure your bills get paid?",
      skip_pattern = "If 'Yes', go to SR_6b. All other answers, go to SR_7a"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_go_help_5cat, 
      description = "SR_1b. Do you have someone who helps with this?",
      skip_pattern = "If 'Yes, one person' or 'Yes, more than one person', go to SR_1c. All other answers, go to SR_2a",
      value_labels = c(
        "Yes,  one person"           = 1,
        "Yes,  more than one person" = 2,
        "No"                         = 3,
        "Don’t know"                 = 7,
        "Refused"                    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_food_help_5cat, 
      description = "SR_2b. Do you have someone who helps with this?",
      skip_pattern = "If 'Yes, one person' or 'Yes, more than one person', go to SR_2c. All other answers, go to 3R_2a",
      value_labels = c(
        "Yes,  one person"           = 1,
        "Yes,  more than one person" = 2,
        "No"                         = 3,
        "Don’t know"                 = 7,
        "Refused"                    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_house_help_5cat, 
      description = "SR_3b. Do you have someone who helps with this?",
      value_labels = c(
        "Yes,  one person"           = 1,
        "Yes,  more than one person" = 2,
        "No"                         = 3,
        "Don’t know"                 = 7,
        "Refused"                    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_clean_help_5cat, 
      description = "SR_4b. Do you have someone who helps with this?",
      skip_pattern = "If 'Yes, one person' or 'Yes, more than one person', go to SR_4c. All other answers, go to SR_5a",
      value_labels = c(
        "Yes,  one person"           = 1,
        "Yes,  more than one person" = 2,
        "No"                         = 3,
        "Don’t know"                 = 7,
        "Refused"                    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_ready_help_5cat, 
      description = "SR_5b. Do you have someone who helps with this?",
      skip_pattern = "If 'Yes, one person' or 'Yes, more than one person', go to SR_5c. All other answers, go to SR_6a",
      value_labels = c(
        "Yes,  one person"           = 1,
        "Yes,  more than one person" = 2,
        "No"                         = 3,
        "Don’t know"                 = 7,
        "Refused"                    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_bills_help_5cat, 
      description = "SR_6b. Do you have someone who helps with this?",
      skip_pattern = "If 'Yes, one person' or 'Yes, more than one person', go to SR_6c. All other answers, go to SR_7a",
      value_labels = c(
        "Yes,  one person"           = 1,
        "Yes,  more than one person" = 2,
        "No"                         = 3,
        "Don’t know"                 = 7,
        "Refused"                    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_go_help_5cat_f, 
      description = "SR_1b. Do you have someone who helps with this?",
      skip_pattern = "If 'Yes, one person' or 'Yes, more than one person', go to SR_1c. All other answers, go to SR_2a"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_food_help_5cat_f, 
      description = "SR_2b. Do you have someone who helps with this?",
      skip_pattern = "If 'Yes, one person' or 'Yes, more than one person', go to SR_2c. All other answers, go to 3R_2a"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_house_help_5cat_f, 
      description = "SR_3b. Do you have someone who helps with this?"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_clean_help_5cat_f, 
      description = "SR_4b. Do you have someone who helps with this?",
      skip_pattern = "If 'Yes, one person' or 'Yes, more than one person', go to SR_4c. All other answers, go to SR_5a"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_ready_help_5cat_f, 
      description = "SR_5b. Do you have someone who helps with this?",
      skip_pattern = "If 'Yes, one person' or 'Yes, more than one person', go to SR_5c. All other answers, go to SR_6a"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_bills_help_5cat_f, 
      description = "SR_6b. Do you have someone who helps with this?",
      skip_pattern = "If 'Yes, one person' or 'Yes, more than one person', go to SR_6c. All other answers, go to SR_7a"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_go_reliable_6cat, 
      description = "SR_1c. How reliable would you say (that person/these people) is/are? Would you say they are… (READ LIST)",
      value_labels = c(
        "Not at all reliable" = 1,
        "Somewhat reliable"   = 2,
        "Very reliable"       = 3,
        "Completely reliable" = 4,
        "Don’t know"          = 7,
        "Refused"             = 9
      ),
      col_type = "Categorical"
    ) %>%

    cb_add_col_attributes( 
      neglect_food_reliable_6cat, 
      description = "SR_2c. How reliable would you say (that person/these people) is/are? Would you say they are… (READ LIST)",
      value_labels = c(
        "Not at all reliable" = 1,
        "Somewhat reliable"   = 2,
        "Very reliable"       = 3,
        "Completely reliable" = 4,
        "Don’t know"          = 7,
        "Refused"             = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_house_reliable_6cat, 
      description = "SR_3c. How reliable would you say (that person/these people) is/are? Would you say they are… (READ LIST)",
      value_labels = c(
        "Not at all reliable" = 1,
        "Somewhat reliable"   = 2,
        "Very reliable"       = 3,
        "Completely reliable" = 4,
        "Don’t know"          = 7,
        "Refused"             = 9
      ),
      col_type = "Categorical"
    ) %>%
 
    cb_add_col_attributes( 
      neglect_clean_reliable_6cat, 
      description = "SR_4c. How reliable would you say (that person/these people) is/are? Would you say they are… (READ LIST)",
      value_labels = c(
        "Not at all reliable" = 1,
        "Somewhat reliable"   = 2,
        "Very reliable"       = 3,
        "Completely reliable" = 4,
        "Don’t know"          = 7,
        "Refused"             = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_ready_reliable_6cat, 
      description = "SR_5c. How reliable would you say (that person/these people) is/are? Would you say they are… (READ LIST)",
      value_labels = c(
        "Not at all reliable" = 1,
        "Somewhat reliable"   = 2,
        "Very reliable"       = 3,
        "Completely reliable" = 4,
        "Don’t know"          = 7,
        "Refused"             = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_bills_reliable_6cat, 
      description = "SR_6c. How reliable would you say (that person/these people) is/are? Would you say they are… (READ LIST)",
      value_labels = c(
        "Not at all reliable" = 1,
        "Somewhat reliable"   = 2,
        "Very reliable"       = 3,
        "Completely reliable" = 4,
        "Don’t know"          = 7,
        "Refused"             = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_go_reliable_6cat_f, 
      description = "SR_1c. How reliable would you say (that person/these people) is/are? Would you say they are… (READ LIST)"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_food_reliable_6cat_f, 
      description = "SR_2c. How reliable would you say (that person/these people) is/are? Would you say they are… (READ LIST)"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_house_reliable_6cat_f, 
      description = "SR_3c. How reliable would you say (that person/these people) is/are? Would you say they are… (READ LIST)"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_clean_reliable_6cat_f, 
      description = "SR_4c. How reliable would you say (that person/these people) is/are? Would you say they are… (READ LIST)"
    ) %>%
      
    cb_add_col_attributes( 
      neglect_ready_reliable_6cat_f, 
      description = "SR_5c. How reliable would you say (that person/these people) is/are? Would you say they are… (READ LIST)"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_bills_reliable_6cat_f, 
      description = "SR_6c. How reliable would you say (that person/these people) is/are? Would you say they are… (READ LIST)"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_person_12cat_f, 
      description = "SR_7. Considering all the things that we just talked about, who is the person who is supposed to help you with these things most of the time? (MULTIPLE RECORD)"
    ) %>%
 
    cb_add_col_attributes( 
      neglect_person_12cat, 
      description = "SR_7. Considering all the things that we just talked about, who is the person who is supposed to help you with these things most of the time? (MULTIPLE RECORD)",
      value_labels = c(
    "A spouse or partner"     = 1, 
    "An ex spouse or partner" = 2, 
    "A parent or step-parent" = 3, 
    "A brother or sister"     = 4, 
    "A son or daughter"       = 5, 
    "Another relative"        = 6, 
    "A coworker"              = 7, 
    "A neighbor"              = 8, 
    "A friend"                = 9, 
    "Some other non-relative" = 10,
    "Don't know"              = 77, 
    "Refused"                 = 99
      ),
      col_type = "Categorical"
    ) %>%

    cb_add_col_attributes( 
      finance_help_4cat, 
      description = "SR_8. Is there someone who helps you take care of your finances, or is there someone other than yourself who makes decisions about your money and your property, either with or without your approval?",
      skip_pattern = "If 'Yes', go to SR_9. All other answers, go to SR_16",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%

    cb_add_col_attributes( 
      finance_person_permission_4cat, 
      description = "SR_10. Does that person usually ask for your permission before deciding to spend your money or sell your property?",
      skip_pattern = "If 'No', go to SR_10a. All other answers, go to SR_11",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
   
    cb_add_col_attributes( 
      finance_person_decisions_4cat, 
      description = "SR_11. Do you feel like that person usually makes good decisions about your finances?",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      finance_copies_4cat, 
      description = "SR_12. Do you have the copies of paperwork for the financial decisions they make or can you get copies if you wanted them?",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      finance_person_forged_4cat, 
      description = "SR_13. Has that person ever forged your signature without your permission in order to sell your property or to get money from your accounts?",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      finance_person_tricked_4cat, 
      description = "SR_14. Has that person ever forced or tricked you into signing a document so that they would be able to get some of your money or possessions?",
      skip_pattern = "If 'Yes', so to SR_14a. All other answers, go to SR_15",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      finance_person_stolen_4cat, 
      description = "SR_15. Has that person, or anyone else you are close to, ever stolen your money or take your things for themselves, their friends, or to sell?",
      skip_pattern = "If 'Yes', so to SR_15a. All other answers, go to SR_16",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      finance_stranger_permission_4cat, 
      description = "SR_16. Has a stranger ever spent your money or sold your property without your permission?",
      skip_pattern = "If 'Yes', so to SR_16a. All other answers, go to SR_17",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      finance_stranger_forged_4cat, 
      description = "SR_17. Has a stranger ever forged your signature in order to get some of your money or sell your property?",
      skip_pattern = "If 'Yes', go to SR_17a. All other answers, go to SR_18",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      finance_stranger_tricked_4cat, 
      description = "SR_18. Has a stranger ever forced or tricked you into signing a document so that they would be able to get some of your money or possessions?",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      finance_person_permission_65_4cat, 
      description = "SR_10a. Were you age 65 or older the last time that person spent your money or sold your property without your permission?",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      finance_person_forged_65_4cat, 
      description = "SR_13a. Were you age 65 or older the last time that person forged your signature without your permission in order to sell your property or to get money from your accounts?",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      finance_person_tricked_65_4cat, 
      description = "SR_14a. Were you age 65 or older the last time that person forced or tricked you into signing a document so that they would be able to get some of your money or possessions?",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      finance_person_stolen_65_4cat, 
      description = "SR_15a. Were you age 65 or older the last time that person stole your money or took your things for themselves, their friends, or to sell?",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      finance_stranger_permission_65_4cat, 
      description = "SR_16a. Were you age 65 or older the last time a stranger spent your money or sold your property without your permission?",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      finance_stranger_forged_65_4cat, 
      description = "SR_17a. Were you age 65 or older the last time a stranger forged your signature in order to get some of your money or sell your property?",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      finance_stranger_tricked_65_4cat, 
      description = "SR_18a. Were you age 65 or older the last time a stranger forced or tricked you into signing a document so that they would be able to get some of your money or possessions?",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      finance_help_4cat_f, 
      description = "SR_8. Is there someone who helps you take care of your finances, or is there someone other than yourself who makes decisions about your money and your property, either with or without your approval?",
      skip_pattern = "If 'Yes', go to SR_9. All other answers, go to SR_16"
    ) %>%
  
    cb_add_col_attributes( 
      finance_person_permission_4cat_f, 
      description = "SR_10. Does that person usually ask for your permission before deciding to spend your money or sell your property?",
      skip_pattern = "If 'No', go to SR_10a. All other answers, go to SR_11"
    ) %>%
  
    cb_add_col_attributes( 
      finance_person_decisions_4cat_f, 
      description = "SR_11. Do you feel like that person usually makes good decisions about your finances?"
    ) %>%
  
    cb_add_col_attributes( 
      finance_copies_4cat_f, 
      description = "SR_12. Do you have the copies of paperwork for the financial decisions they make or can you get copies if you wanted them?"
    ) %>%
  
    cb_add_col_attributes( 
      finance_person_forged_4cat_f, 
      description = "SR_13. Has that person ever forged your signature without your permission in order to sell your property or to get money from your accounts?"
    ) %>%
  
    cb_add_col_attributes( 
      finance_person_tricked_4cat_f, 
      description = "SR_14. Has that person ever forced or tricked you into signing a document so that they would be able to get some of your money or possessions?",
      skip_pattern = "If 'Yes', so to SR_14a. All other answers, go to SR_15"
    ) %>%
  
    cb_add_col_attributes( 
      finance_person_stolen_4cat_f, 
      description = "SR_15. Has that person, or anyone else you are close to, ever stolen your money or take your things for themselves, their friends, or to sell?",
      skip_pattern = "If 'Yes', so to SR_15a. All other answers, go to SR_16"
    ) %>%
  
    cb_add_col_attributes( 
      finance_stranger_permission_4cat_f, 
      description = "SR_16. Has a stranger ever spent your money or sold your property without your permission?",
      skip_pattern = "If 'Yes', so to SR_16a. All other answers, go to SR_17"
    ) %>%
  
    cb_add_col_attributes( 
      finance_stranger_forged_4cat_f, 
      description = "SR_17. Has a stranger ever forged your signature in order to get some of your money or sell your property?",
      skip_pattern = "If 'Yes', go to SR_17a. All other answers, go to SR_18"
    ) %>%
  
    cb_add_col_attributes( 
      finance_stranger_tricked_4cat_f, 
      description = "SR_18. Has a stranger ever forced or tricked you into signing a document so that they would be able to get some of your money or possessions?"
    ) %>%
  
    cb_add_col_attributes( 
      finance_person_permission_65_4cat_f, 
      description = "SR_10a. Were you age 65 or older the last time that person spent your money or sold your property without your permission?"
    ) %>%
  
    cb_add_col_attributes( 
      finance_person_forged_65_4cat_f, 
      description = "SR_13a. Were you age 65 or older the last time that person forged your signature without your permission in order to sell your property or to get money from your accounts?"
    ) %>%
  
    cb_add_col_attributes( 
      finance_person_tricked_65_4cat_f, 
      description = "SR_14a. Were you age 65 or older the last time that person forced or tricked you into signing a document so that they would be able to get some of your money or possessions?"
    ) %>%
  
    cb_add_col_attributes( 
      finance_person_stolen_65_4cat_f, 
      description = "SR_15a. Were you age 65 or older the last time that person stole your money or took your things for themselves, their friends, or to sell?"
    ) %>%
  
    cb_add_col_attributes( 
      finance_stranger_permission_65_4cat_f, 
      description = "SR_16a. Were you age 65 or older the last time a stranger spent your money or sold your property without your permission?"
    ) %>%
  
    cb_add_col_attributes( 
      finance_stranger_forged_65_4cat_f, 
      description = "SR_17a. Were you age 65 or older the last time a stranger forged your signature in order to get some of your money or sell your property?"
    ) %>%
  
    cb_add_col_attributes( 
      finance_stranger_tricked_65_4cat_f, 
      description = "SR_18a. Were you age 65 or older the last time a stranger forced or tricked you into signing a document so that they would be able to get some of your money or possessions?"
    ) %>%
  
    cb_add_col_attributes( 
      finance_person_12cat_f, 
      description = "SR_9. What is that person’s relationship to you? (MULTIPLE RECORD)"
    ) %>%
  
    cb_add_col_attributes( 
      finance_person_12cat, 
      description = "SR_9. What is that person’s relationship to you? (MULTIPLE RECORD)",
      value_labels = c(
    "A spouse or partner"     = 1, 
    "An ex spouse or partner" = 2, 
    "A parent or step-parent" = 3, 
    "A brother or sister"     = 4, 
    "A son or daughter"       = 5, 
    "Another relative"        = 6, 
    "A coworker"              = 7, 
    "A neighbor"              = 8, 
    "A friend"                = 9, 
    "Some other non-relative" = 10,
    "Don't know"              = 77, 
    "Refused"                 = 99
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      finance_person_permission_last_time_8cat, 
      description = "SR_10b. When was the last time that person spent your money or sold your property without your permission?",
      value_labels = c(
        "Less than 1 month ago"                       = 1,
        "Between 1 month and less than 3 months ago"  = 2,
        "Between 3 months and less than 6 months ago" = 3,
        "Between 6 months and less than 1 year ago"   = 4,
        "Between 1 year and less than 3 years ago"    = 5,
        "3 or more years ago"                         = 6,
        "Don’t know"                                  = 7,
        "Refused"                                     = 9
      ),
      col_type = "Categorical"
    ) %>%

    cb_add_col_attributes( 
      finance_person_forged_last_time_8cat, 
      description = "SR_13b. When was the last time that person forged your signature without your permission in order to sell your property or to get money from your accounts?",
      value_labels = c(
        "Less than 1 month ago"                       = 1,
        "Between 1 month and less than 3 months ago"  = 2,
        "Between 3 months and less than 6 months ago" = 3,
        "Between 6 months and less than 1 year ago"   = 4,
        "Between 1 year and less than 3 years ago"    = 5,
        "3 or more years ago"                         = 6,
        "Don’t know"                                  = 7,
        "Refused"                                     = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      finance_person_tricked_last_time_8cat, 
      description = "SR_14b. When was the last time that person forced or tricked you into signing a document so that they would be able to get some of your money or possessions?",
      value_labels = c(
        "Less than 1 month ago"                       = 1,
        "Between 1 month and less than 3 months ago"  = 2,
        "Between 3 months and less than 6 months ago" = 3,
        "Between 6 months and less than 1 year ago"   = 4,
        "Between 1 year and less than 3 years ago"    = 5,
        "3 or more years ago"                         = 6,
        "Don’t know"                                  = 7,
        "Refused"                                     = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      finance_person_stolen_last_time_8cat, 
      description = "SR_15b. When was the last time that person stole your money or took your things for themselves, their friends, or to sell?",
      value_labels = c(
        "Less than 1 month ago"                       = 1,
        "Between 1 month and less than 3 months ago"  = 2,
        "Between 3 months and less than 6 months ago" = 3,
        "Between 6 months and less than 1 year ago"   = 4,
        "Between 1 year and less than 3 years ago"    = 5,
        "3 or more years ago"                         = 6,
        "Don’t know"                                  = 7,
        "Refused"                                     = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      finance_stranger_permission_last_time_8cat, 
      description = "SR_16b. When was the last time a stranger spent your money or sold your property without your permission?",
      value_labels = c(
        "Less than 1 month ago"                       = 1,
        "Between 1 month and less than 3 months ago"  = 2,
        "Between 3 months and less than 6 months ago" = 3,
        "Between 6 months and less than 1 year ago"   = 4,
        "Between 1 year and less than 3 years ago"    = 5,
        "3 or more years ago"                         = 6,
        "Don’t know"                                  = 7,
        "Refused"                                     = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      finance_stranger_forged_last_time_8cat, 
      description = "SR_17b. When was the last time a stranger forged your signature in order to get some of your money or sell your property?",
      value_labels = c(
        "Less than 1 month ago"                       = 1,
        "Between 1 month and less than 3 months ago"  = 2,
        "Between 3 months and less than 6 months ago" = 3,
        "Between 6 months and less than 1 year ago"   = 4,
        "Between 1 year and less than 3 years ago"    = 5,
        "3 or more years ago"                         = 6,
        "Don’t know"                                  = 7,
        "Refused"                                     = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      finance_stranger_tricked_last_time_8cat, 
      description = "SR_18b. When was the last time a stranger forced or tricked you into signing a document so that they would be able to get some of your money or possessions?",
      value_labels = c(
        "Less than 1 month ago"                       = 1,
        "Between 1 month and less than 3 months ago"  = 2,
        "Between 3 months and less than 6 months ago" = 3,
        "Between 6 months and less than 1 year ago"   = 4,
        "Between 1 year and less than 3 years ago"    = 5,
        "3 or more years ago"                         = 6,
        "Don’t know"                                  = 7,
        "Refused"                                     = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      finance_person_permission_last_time_8cat_f, 
      description = "SR_10b. When was the last time that person spent your money or sold your property without your permission?"
    ) %>%
  
    cb_add_col_attributes( 
      finance_person_forged_last_time_8cat_f, 
      description = "SR_13b. When was the last time that person forged your signature without your permission in order to sell your property or to get money from your accounts?"
    ) %>%
  
    cb_add_col_attributes( 
      finance_person_tricked_last_time_8cat_f, 
      description = "SR_14b. When was the last time that person forced or tricked you into signing a document so that they would be able to get some of your money or possessions?"
    ) %>%
  
    cb_add_col_attributes( 
      finance_person_stolen_last_time_8cat_f, 
      description = "SR_15b. When was the last time that person stole your money or took your things for themselves, their friends, or to sell?"
    ) %>%
  
    cb_add_col_attributes( 
      finance_stranger_permission_last_time_8cat_f, 
      description = "SR_16b. When was the last time a stranger spent your money or sold your property without your permission?"
    ) %>%
  
    cb_add_col_attributes( 
      finance_stranger_forged_last_time_8cat_f, 
      description = "SR_17b. When was the last time a stranger forged your signature in order to get some of your money or sell your property?"
    ) %>%
  
    cb_add_col_attributes( 
      finance_stranger_tricked_last_time_8cat_f, 
      description = "SR_18b. When was the last time a stranger forced or tricked you into signing a document so that they would be able to get some of your money or possessions?"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_yelled_4cat, 
      description = "SR_19a. Has anyone ever verbally attacked, scolded, or yelled at you so that you felt afraid for your safety, threatened or intimidated?",
      skip_pattern = "If 'Yes', go to SR_19b. All other answers, go to SR_20a",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
        ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_embarrassed_4cat, 
      description = "SR_20a. Has anyone ever made you feel humiliated or embarrassed by calling you names such as stupid, or telling you that you or your opinion was worthless?",
       skip_pattern = "If 'Yes', go to SR_20b. All other answers, go to SR_21a",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
        ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_harassed_4cat, 
      description = "SR_21a. Has anyone ever forcefully or repeatedly asked you to do something so much that you felt harassed or coerced into doing something against your will?",
      skip_pattern = "If 'Yes', go to SR_21b. All other answers, go to SR_22a",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
        ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_refused_4cat, 
      description = "SR_22a. Has anyone close to you ever completely refused to talk to you or ignored you for days at a time, even when you wanted to talk to them?",
      skip_pattery = "If 'Yes', go to SR_22b. All other answers, go to SP_2",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
        ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_incident_60_4cat, 
      description = "Question used in older version of the follow-up interview",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
        ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_incident_reported_4cat, 
      description = "Question used in older version of the follow-up interview",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
        ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_person_live_4cat, 
      description = "Question used in older version of the follow-up interview",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
        ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_person_alcohol_4cat, 
      description = "SR_27. Did that person have a problem with alcohol or drugs when these things happened?",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
        ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_person_counseling_4cat, 
      description = "SR_28. Has that person ever received inpatient or outpatient counseling for emotional problems?",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
        ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_person_police_4cat, 
      description = "SR_29. Has that person ever been in trouble with the police?",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
        ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_person_job_4cat, 
      description = "SR_30. Did that person have a job at the time when these things happened?",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
        ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_person_help_4cat, 
      description = "SR_32. Did that person ever help you out with any day to day things, like shopping, taking medicines, driving you places, getting dressed, and that type of thing?",
      skip_pattern = "IF Q26b = Yes, go to SR_33. All other answers, go to SR_T5",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
        ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_person_no_live_4cat, 
      description = "SR_33. Would you be able to live on your own if that person no longer lived with you?",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
        ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_yelled_65_4cat, 
      description = "SR_19c. Were you age 65 or older the last time (most recent time) this happened?",
      skip_pattern = "If 'Yes', go to SR_T4. Else, go to SR_T5",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
        ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_embarrassed_65_4cat, 
      description = "SR_20c. Were you age 65 or older the last time (most recent time) this happened?",
      skip_pattern = "If 'Yes', go to SR_T4. Else, go to SR_T5",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
        ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_harassed_65_4cat, 
      description = "SR_21c. Were you age 65 or older the last time (most recent time) this happened?",
      skip_pattern = "If 'Yes', go to SR_T4. Else, go to SR_T5",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
        ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_refused_65_4cat, 
      description = "SR_22c. Were you age 65 or older the last time (most recent time) this happened?",
      skip_pattern = "If 'Yes', go to SR_T4. Else, go to SR_T5",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
        ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_incident_reported_v2_4cat, 
      description = "SR_24.  Did you or anyone else report what happened to the police or other authorities?",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
        ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_person_live_then_4cat, 
      description = "SR_26a. Did that person (any of those people) live with you when these things happened?",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
        ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_person_live_now_4cat, 
      description = "SR_26b. Does that person (any of those people) live with you now?",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
        ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_yelled_4cat_f, 
      description = "SR_19a. Has anyone ever verbally attacked, scolded, or yelled at you so that you felt afraid for your safety, threatened or intimidated?",
      skip_pattern = "If 'Yes', go to SR_19b. All other answers, go to SR_20a",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
        ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_embarrassed_4cat_f, 
      description = "SR_20a. Has anyone ever made you feel humiliated or embarrassed by calling you names such as stupid, or telling you that you or your opinion was worthless?",
       skip_pattern = "If 'Yes', go to SR_20b. All other answers, go to SR_21a",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
        ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_harassed_4cat_f, 
      description = "SR_21a. Has anyone ever forcefully or repeatedly asked you to do something so much that you felt harassed or coerced into doing something against your will?",
      skip_pattern = "If 'Yes', go to SR_21b. All other answers, go to SR_22a",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
        ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_refused_4cat_f, 
      description = "SR_22a. Has anyone close to you ever completely refused to talk to you or ignored you for days at a time, even when you wanted to talk to them?",
      skip_pattery = "If 'Yes', go to SR_22b. All other answers, go to SP_2"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_incident_60_4cat_f, 
      description = "Question used in older version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_incident_reported_4cat_f, 
      description = "Question used in older version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_person_live_4cat_f, 
      description = "Question used in older version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_person_alcohol_4cat_f, 
      description = "SR_27. Did that person have a problem with alcohol or drugs when these things happened?"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_person_counseling_4cat_f, 
      description = "SR_28. Has that person ever received inpatient or outpatient counseling for emotional problems?"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_person_police_4cat_f, 
      description = "SR_29. Has that person ever been in trouble with the police?"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_person_job_4cat_f, 
      description = "SR_30. Did that person have a job at the time when these things happened?"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_person_help_4cat_f, 
      description = "SR_32. Did that person ever help you out with any day to day things, like shopping, taking medicines, driving you places, getting dressed, and that type of thing?",
      skip_pattern = "IF Q26b = Yes, go to SR_33. All other answers, go to SR_T5"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_person_no_live_4cat_f, 
      description = "SR_33. Would you be able to live on your own if that person no longer lived with you?"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_yelled_65_4cat_f, 
      description = "SR_19c. Were you age 65 or older the last time (most recent time) this happened?",
      skip_pattern = "If 'Yes', go to SR_T4. Else, go to SR_T5"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_embarrassed_65_4cat_f, 
      description = "SR_20c. Were you age 65 or older the last time (most recent time) this happened?",
      skip_pattern = "If 'Yes', go to SR_T4. Else, go to SR_T5"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_harassed_65_4cat_f, 
      description = "SR_21c. Were you age 65 or older the last time (most recent time) this happened?",
      skip_pattern = "If 'Yes', go to SR_T4. Else, go to SR_T5"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_refused_65_4cat_f, 
      description = "SR_22c. Were you age 65 or older the last time (most recent time) this happened?",
      skip_pattern = "If 'Yes', go to SR_T4. Else, go to SR_T5"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_incident_reported_v2_4cat_f, 
      description = "SR_24.  Did you or anyone else report what happened to the police or other authorities?"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_person_live_then_4cat_f, 
      description = "SR_26a. Did that person (any of those people) live with you when these things happened?"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_person_live_now_4cat_f, 
      description = "SR_26b. Does that person (any of those people) live with you now?"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_incident_person_12cat_f, 
      description = "Question used in older version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_incident_person_12cat, 
      description = "Question used in older version of the follow-up interview",
      value_labels = c(
    "A spouse or partner"     = 1, 
    "An ex spouse or partner" = 2, 
    "A parent or step-parent" = 3, 
    "A brother or sister"     = 4, 
    "A son or daughter"       = 5, 
    "Another relative"        = 6, 
    "A coworker"              = 7, 
    "A neighbor"              = 8, 
    "A friend"                = 9, 
    "Some other non-relative" = 10,
    "Don't know"              = 77, 
    "Refused"                 = 99
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_yelled_last_time_8cat, 
      description = "SR_19d. How long ago was the last time (most recent time) this happened?",
      value_labels = c(
        "Less than 1 month ago"                       = 1,
        "Between 1 month and less than 3 months ago"  = 2,
        "Between 3 months and less than 6 months ago" = 3,
        "Between 6 months and less than 1 year ago"   = 4,
        "Between 1 year and less than 3 years ago"    = 5,
        "3 or more years ago"                         = 6,
        "Don’t know"                                  = 7,
        "Refused"                                     = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_embarrassed_last_time_8cat, 
      description = "SR_20d. How long ago was the last time (most recent time) this happened?",
      value_labels = c(
        "Less than 1 month ago"                       = 1,
        "Between 1 month and less than 3 months ago"  = 2,
        "Between 3 months and less than 6 months ago" = 3,
        "Between 6 months and less than 1 year ago"   = 4,
        "Between 1 year and less than 3 years ago"    = 5,
        "3 or more years ago"                         = 6,
        "Don’t know"                                  = 7,
        "Refused"                                     = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_harassed_last_time_8cat, 
      description = "SR_21d. How long ago was the last time (most recent time) this happened?",
      value_labels = c(
        "Less than 1 month ago"                       = 1,
        "Between 1 month and less than 3 months ago"  = 2,
        "Between 3 months and less than 6 months ago" = 3,
        "Between 6 months and less than 1 year ago"   = 4,
        "Between 1 year and less than 3 years ago"    = 5,
        "3 or more years ago"                         = 6,
        "Don’t know"                                  = 7,
        "Refused"                                     = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_refused_last_time_8cat, 
      description = "SR_22d. How long ago was the last time (most recent time) this happened?",
      value_labels = c(
        "Less than 1 month ago"                       = 1,
        "Between 1 month and less than 3 months ago"  = 2,
        "Between 3 months and less than 6 months ago" = 3,
        "Between 6 months and less than 1 year ago"   = 4,
        "Between 1 year and less than 3 years ago"    = 5,
        "3 or more years ago"                         = 6,
        "Don’t know"                                  = 7,
        "Refused"                                     = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_yelled_last_time_8cat_f, 
      description = "SR_19d. How long ago was the last time (most recent time) this happened?"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_embarrassed_last_time_8cat_f, 
      description = "SR_20d. How long ago was the last time (most recent time) this happened?"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_harassed_last_time_8cat_f, 
      description = "SR_21d. How long ago was the last time (most recent time) this happened?"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_refused_last_time_8cat_f, 
      description = "SR_22d. How long ago was the last time (most recent time) this happened?"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_yelled_times_7cat, 
      description = "SR_19b. About how many times has this happened to you in your lifetime?",
      value_labels = c(
        "1 or 2 times"                      = 1,
        "Between 3 and less than 5 times"   = 2,
        "Between 5 and less than 10 times"  = 3,
        "Between 10 and less than 20 times" = 4,
        "20 or more times"                  = 5,
        "Don’t know"                        = 7,
        "Refused"                           = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_embarrassed_times_7cat, 
      description = "SR_20b. About how many times has this happened to you in your lifetime?",
      value_labels = c(
        "1 or 2 times"                      = 1,
        "Between 3 and less than 5 times"   = 2,
        "Between 5 and less than 10 times"  = 3,
        "Between 10 and less than 20 times" = 4,
        "20 or more times"                  = 5,
        "Don’t know"                        = 7,
        "Refused"                           = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_harassed_times_7cat, 
      description = "SR_21b. About how many times has this happened to you in your lifetime?",
      value_labels = c(
        "1 or 2 times"                      = 1,
        "Between 3 and less than 5 times"   = 2,
        "Between 5 and less than 10 times"  = 3,
        "Between 10 and less than 20 times" = 4,
        "20 or more times"                  = 5,
        "Don’t know"                        = 7,
        "Refused"                           = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_refused_times_7cat, 
      description = "SR_22b. About how many times has this happened to you in your lifetime?",
      value_labels = c(
        "1 or 2 times"                      = 1,
        "Between 3 and less than 5 times"   = 2,
        "Between 5 and less than 10 times"  = 3,
        "Between 10 and less than 20 times" = 4,
        "20 or more times"                  = 5,
        "Don’t know"                        = 7,
        "Refused"                           = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_yelled_times_7cat_f, 
      description = "SR_19b. About how many times has this happened to you in your lifetime?"
    ) %>%

    cb_add_col_attributes( 
      emotional_embarrassed_times_7cat_f, 
      description = "SR_20b. About how many times has this happened to you in your lifetime?"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_harassed_times_7cat_f, 
      description = "SR_21b. About how many times has this happened to you in your lifetime?"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_refused_times_7cat_f, 
      description = "SR_22b. About how many times has this happened to you in your lifetime?"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_person_friends_6cat, 
      description = "SR_31. How many friends did that person have at the time when these things happened? Would you say…",
      value_labels = c(
        "None"             = 0,
        "Very few (1 -3)"  = 1,
        "Some (4 -6)"      = 2,
        "A lot (7+)"       = 3,
        "Don’t know"       = 7,
        "Refused"          = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_person_friends_6cat_f, 
      description = "SR_31. How many friends did that person have at the time when these things happened? Would you say…"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_incident_person_v2_12cat_f, 
      description = "SR_25. What was your relationship to the person, or people, who treated you this way? (MULTIPLE RECORD)",
      skip_pattern = "IF SR_25 = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, OR 11} Go to SR_26a. Else, go to SR_T5"
) %>%
  
    cb_add_col_attributes( 
      emotional_incident_person_v2_12cat, 
      description = "SR_25. What was your relationship to the person, or people, who treated you this way? (MULTIPLE RECORD)",
      skip_pattern = "IF SR_25 = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, OR 11} Go to SR_26a. Else, go to SR_T5",
      value_labels = c(
      "A spouse or partner"     = 1, 
      "An ex spouse or partner" = 2, 
      "A parent or step-parent" = 3, 
      "A brother or sister"     = 4, 
      "A son or daughter"       = 5, 
      "Another relative"        = 6, 
      "A coworker"              = 7, 
      "A neighbor"              = 8, 
      "A friend"                = 9, 
      "Some other non-relative" = 10,
      "Don't know"              = 77, 
      "Refused"                 = 99
    ),
    col_type = "Categorical"
  ) %>%  
  
    cb_add_col_attributes( 
      physical_hit_4cat, 
      description = "SR_34a. Has anyone ever hit you with their hand or object, slapped you, or threatened you with a weapon?",
      skip_pattern = "If 'Yes', go to SR_34b. All other answers, go to SR_35a",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      physical_restrain_4cat, 
      description = "SR_35a. Has anyone ever tried to restrain you by holding you down, tying you up, or locking you in your room or house?",
      skip_pattern = "If 'Yes', go to SR_35b. All other answers,go to SR_36a",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      physical_hurt_4cat, 
      description = "SR_36a. Has anyone ever physically hurt you so that you suffered some degree of injury, including cuts, bruises, or other marks?",
      skip_pattern = "If 'Yes', go to SR_36b. All other answers, go to SP_6",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      physical_incident_60_4cat, 
      description = "Question from an older version of the follow-up interview",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      physical_incident_reported_4cat, 
      description = "Question from an older version of the follow-up interview",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      physical_incident_person_4cat, 
      description = "Question from an older version of the follow-up interview",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      physical_person_4cat, 
      description = "Question from an older version of the follow-up interview",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      physical_person_live_4cat, 
      description = "Question from an older version of the follow-up interview",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      physical_person_alcohol_4cat, 
      description = "SR_42. Did that person have a problem with alcohol or drugs at the time when these things happened?",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      physical_person_counseling_4cat, 
      description = "SR_43. Has that person ever received inpatient or outpatient counseling for emotional problems?",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      physical_person_police_4cat, 
      description = "SR_44. Has that person ever been in trouble with the police?",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      physical_person_job_4cat, 
      description = "SR_45. Did that person have a job at the time when these things happened?",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      physical_person_help_4cat, 
      description = "SR_47. Did that person ever help you out with any day to day things, like shopping, taking medicines, driving you places, getting dressed, and that type of thing?",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      physical_person_no_live_4cat, 
      description = "SR_48. Would you be able to live on your own if that person no longer lived with you?",
      skip_pattern =  "All answers, go to SR_T7(SR_49a)",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      physical_hit_65_4cat, 
      description = "Were you age 65 or older the last time (most recent time) this happened?",
      skip_pattern =  "If yes, go to SR_T6. Else, go to SR_T7",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      physical_restrain_65_4cat, 
      description = "Were you age 65 or older the last time (most recent time) this happened?",
      skip_pattern =  "If yes, go to SR_T6. Else, go to SR_T7",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
   
    cb_add_col_attributes( 
      physical_hurt_65_4cat, 
      description = "Were you age 65 or older the last time (most recent time) this happened?",
      skip_pattern =  "If yes, go to SR_T6. Else, go to SR_T7",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      physical_incident_reported_v2_4cat, 
      description = "SR_38. Did you or anyone else report what happened to the police or other authorities?",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      physical_person_live_then_4cat, 
      description = "SR_41a. Did that person (any of those people) live with you when these things happened?",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      physical_person_live_now_4cat, 
      description = "SR_41b. Does that person (any of those people) live with you now?",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%

    cb_add_col_attributes( 
      physical_hit_4cat_f, 
      description = "SR_34a. Has anyone ever hit you with their hand or object, slapped you, or threatened you with a weapon?",
      skip_pattern = "If 'Yes', go to SR_34b. All other answers, go to SR_35a"
    ) %>%
  
    cb_add_col_attributes( 
      physical_restrain_4cat_f, 
      description = "SR_35a. Has anyone ever tried to restrain you by holding you down, tying you up, or locking you in your room or house?",
      skip_pattern = "If 'Yes', go to SR_35b. All other answers,go to SR_36a"
    ) %>%
  
    cb_add_col_attributes( 
      physical_hurt_4cat_f, 
      description = "SR_36a. Has anyone ever physically hurt you so that you suffered some degree of injury, including cuts, bruises, or other marks?",
      skip_pattern = "If 'Yes', go to SR_36b. All other answers, go to SP_6"
    ) %>%
  
    cb_add_col_attributes( 
      physical_incident_60_4cat_f, 
      description = "Question from an older version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      physical_incident_reported_4cat_f, 
      description = "Question from an older version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      physical_incident_person_4cat_f, 
      description = "Question from an older version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      physical_person_4cat_f, 
      description = "Question from an older version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      physical_person_live_4cat_f, 
      description = "Question from an older version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      physical_person_alcohol_4cat_f, 
      description = "SR_42. Did that person have a problem with alcohol or drugs at the time when these things happened?"
    ) %>%
  
    cb_add_col_attributes( 
      physical_person_counseling_4cat_f, 
      description = "SR_43. Has that person ever received inpatient or outpatient counseling for emotional problems?"
    ) %>%
  
    cb_add_col_attributes( 
      physical_person_police_4cat_f, 
      description = "SR_44. Has that person ever been in trouble with the police?"
    ) %>%
  
    cb_add_col_attributes( 
      physical_person_job_4cat_f, 
      description = "SR_45. Did that person have a job at the time when these things happened?"
    ) %>%
  
    cb_add_col_attributes( 
      physical_person_help_4cat_f, 
      description = "SR_47. Did that person ever help you out with any day to day things, like shopping, taking medicines, driving you places, getting dressed, and that type of thing?"
    ) %>%
  
    cb_add_col_attributes( 
      physical_person_no_live_4cat_f, 
      description = "SR_48. Would you be able to live on your own if that person no longer lived with you?",
      skip_pattern =  "All answers, go to SR_T7(SR_49a)"
    ) %>%
  
    cb_add_col_attributes( 
      physical_hit_65_4cat_f, 
      description = "Were you age 65 or older the last time (most recent time) this happened?",
      skip_pattern =  "If yes, go to SR_T6. Else, go to SR_T7"
    ) %>%
  
    cb_add_col_attributes( 
      physical_restrain_65_4cat_f, 
      description = "Were you age 65 or older the last time (most recent time) this happened?",
      skip_pattern =  "If yes, go to SR_T6. Else, go to SR_T7"
    ) %>%
  
    cb_add_col_attributes( 
      physical_hurt_65_4cat_f, 
      description = "Were you age 65 or older the last time (most recent time) this happened?",
      skip_pattern =  "If yes, go to SR_T6. Else, go to SR_T7"
    ) %>%
  
    cb_add_col_attributes( 
      physical_incident_reported_v2_4cat_f, 
      description = "SR_38. Did you or anyone else report what happened to the police or other authorities?"
    ) %>%
  
    cb_add_col_attributes( 
      physical_person_live_then_4cat_f, 
      description = "SR_41a. Did that person (any of those people) live with you when these things happened?"
    ) %>%
  
    cb_add_col_attributes( 
      physical_person_live_now_4cat_f, 
      description = "SR_41b. Does that person (any of those people) live with you now?"
    ) %>%
  
    cb_add_col_attributes( 
      physical_hit_last_time_8cat, 
      description = "SR_34d. How long ago was the last time (most recent time) this happened?",
      value_labels = c(
        "Less than 1 month ago"                       = 1,
        "Between 1 month and less than 3 months ago"  = 2,
        "Between 3 months and less than 6 months ago" = 3,
        "Between 6 months and less than 1 year ago"   = 4,
        "Between 1 year and less than 3 years ago"    = 5,
        "3 or more years ago"                         = 6,
        "Don’t know"                                  = 7,
        "Refused"                                     = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      physical_restrain_last_time_8cat, 
      description = "SR_35d. How long ago was the last time (most recent time) this happened?",
      value_labels = c(
        "Less than 1 month ago"                       = 1,
        "Between 1 month and less than 3 months ago"  = 2,
        "Between 3 months and less than 6 months ago" = 3,
        "Between 6 months and less than 1 year ago"   = 4,
        "Between 1 year and less than 3 years ago"    = 5,
        "3 or more years ago"                         = 6,
        "Don’t know"                                  = 7,
        "Refused"                                     = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      physical_hurt_last_time_8cat, 
      description = "SR_36d. How long ago was the last time (most recent time) this happened?",
      value_labels = c(
        "Less than 1 month ago"                       = 1,
        "Between 1 month and less than 3 months ago"  = 2,
        "Between 3 months and less than 6 months ago" = 3,
        "Between 6 months and less than 1 year ago"   = 4,
        "Between 1 year and less than 3 years ago"    = 5,
        "3 or more years ago"                         = 6,
        "Don’t know"                                  = 7,
        "Refused"                                     = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      physical_hit_last_time_8cat_f, 
      description = "SR_34d. How long ago was the last time (most recent time) this happened?"
    ) %>%
  
    cb_add_col_attributes( 
      physical_restrain_last_time_8cat_f, 
      description = "SR_35d. How long ago was the last time (most recent time) this happened?"
    ) %>%
  
    cb_add_col_attributes( 
      physical_hurt_last_time_8cat_f, 
      description = "SR_36d. How long ago was the last time (most recent time) this happened?"
    ) %>%
  
    cb_add_col_attributes( 
      physical_hit_times_7cat, 
      description = "SR_34b. About how many times has this happened to you in your lifetime?",
      value_labels = c(
        "1 or 2 times"                      = 1,
        "Between 3 and less than 5 times"   = 2,
        "Between 5 and less than 10 times"  = 3,
        "Between 10 and less than 20 times" = 4,
        "20 or more times"                  = 5,
        "Don’t know"                        = 7,
        "Refused"                           = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      physical_restrain_times_7cat, 
      description = "SR_35b. About how many times has this happened to you in your lifetime?",
      value_labels = c(
        "1 or 2 times"                      = 1,
        "Between 3 and less than 5 times"   = 2,
        "Between 5 and less than 10 times"  = 3,
        "Between 10 and less than 20 times" = 4,
        "20 or more times"                  = 5,
        "Don’t know"                        = 7,
        "Refused"                           = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      physical_hurt_times_7cat, 
      description = "SR_36b. About how many times has this happened to you in your lifetime?",
      value_labels = c(
        "1 or 2 times"                      = 1,
        "Between 3 and less than 5 times"   = 2,
        "Between 5 and less than 10 times"  = 3,
        "Between 10 and less than 20 times" = 4,
        "20 or more times"                  = 5,
        "Don’t know"                        = 7,
        "Refused"                           = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      physical_hit_times_7cat_f, 
      description = "SR_34b. About how many times has this happened to you in your lifetime?"
    ) %>%
  
    cb_add_col_attributes( 
      physical_restrain_times_7cat_f, 
      description = "SR_35b. About how many times has this happened to you in your lifetime?"
    ) %>%
  
    cb_add_col_attributes( 
      physical_hurt_times_7cat_f, 
      description = "SR_36b. About how many times has this happened to you in your lifetime?"
    ) %>%
  
    cb_add_col_attributes( 
      physical_person_friends_6cat, 
      description = "SR_46. How many friends did that person have at the time when these things happened? Would you say…",
      value_labels = c(
        "None"            = 0,
        "Very few (1 -3)" = 1,
        "Some (4 -6)"     = 2,
        "A lot (7+)"      = 3,
        "Don’t know"      = 7,
        "Refused"         = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      physical_person_friends_6cat_f, 
      description = "SR_46. How many friends did that person have at the time when these things happened? Would you say…"
    ) %>%
  
cb_add_col_attributes( 
  physical_incident_person_v2_12cat_f, 
  description = "SR_40. What was your relationship to the person, or people, who treated you this way? (MULTIPLE RECORD)",
  skip_pattern = "IF SR_40 = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, OR 11} Go to SR_41a. Else, go to SR_T7"
) %>%
  
  cb_add_col_attributes( 
    physical_incident_person_v2_12cat, 
    description = "SR_40. What was your relationship to the person, or people, who treated you this way? (MULTIPLE RECORD)",
    skip_pattern = "IF SR_40 = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, OR 11} Go to SR_41a. Else, go to SR_T7",
    value_labels = c(
      "A spouse or partner"     = 1, 
      "An ex spouse or partner" = 2, 
      "A parent or step-parent" = 3, 
      "A brother or sister"     = 4, 
      "A son or daughter"       = 5, 
      "Another relative"        = 6, 
      "A coworker"              = 7, 
      "A neighbor"              = 8, 
      "A friend"                = 9, 
      "Some other non-relative" = 10,
      "Don't know"              = 77, 
      "Refused"                 = 99
    ),
    col_type = "Categorical"
  ) %>%

cb_add_col_attributes( 
  physical_person_12cat_f, 
  description = "Question from an older version of the follow-up interview"
) %>%
  
  cb_add_col_attributes( 
    physical_person_12cat, 
    description = "Question from an older version of the follow-up interview",
    value_labels = c(
      "A spouse or partner"     = 1, 
      "An ex spouse or partner" = 2, 
      "A parent or step-parent" = 3, 
      "A brother or sister"     = 4, 
      "A son or daughter"       = 5, 
      "Another relative"        = 6, 
      "A coworker"              = 7, 
      "A neighbor"              = 8, 
      "A friend"                = 9, 
      "Some other non-relative" = 10,
      "Don't know"              = 77, 
      "Refused"                 = 99
    ),
    col_type = "Categorical"
  ) %>%
  
    cb_add_col_attributes( 
      sexual_harm_4cat, 
      description = "SR_49a. Regardless of how long ago it happened or who made the advances, has anyone ever made you have sex or oral sex by using force or threatening to harm you or someone close to you?",
      skip_pattern = "If 'Yes', go to SR_49b. All other answers, go to SR_50a",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9 
      ),
      col_type = "Categorical"
    ) %>%

    cb_add_col_attributes( 
      sexual_touched_4cat, 
      description = "SR_50a. Females- Has anyone ever touched your breasts or pubic area or made you touch his penis by using force or threat of force? Males - Has anyone ever touched your pubic area or made you touch their pubic area by using force or threat of force?",
      skip_pattern = "If 'Yes', go to SR_50b. All other answers, go to SR_51a",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9 
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_forced_4cat, 
      description = "SR_51a. Females- Has anyone ever forced you to undress or expose your breasts or pubic area when you didn’t want to? Males- Has anyone ever forced you to undress or expose your pubic area when you didn’t want to?",
      skip_pattern = "If 'Yes', go to SR_51b. All other answers, go to SR_52_a",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9 
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_picture_4cat, 
      description = "SR_52a. Has anyone ever taken a picture of you with your clothes partially or completely taken off when you didn’t want them to?",
      skip_pattern = "If 'Yes', go to SR_52b. All other answers, go to SR_53a",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9 
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_incident_60_4cat, 
      description = "Question from an older version of the follow-up interview",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9 
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_incident_reported_4cat, 
      description = "Question from an older version of the follow-up interview",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9 
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_incident_person_4cat, 
      description = "Question from an older version of the follow-up interview",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9 
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_person_4cat, 
      description = "Question from an older version of the follow-up interview",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9 
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_person_live_4cat, 
      description = "Question from an older version of the follow-up interview",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9 
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_person_alcohol_4cat, 
      description = "SR_58. Did that person have a problem with alcohol or drugs at the time when these things happened?",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9 
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_person_counseling_4cat, 
      description = "SR_59. Has that person ever received inpatient or outpatient counseling for emotional problems?",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9 
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_person_police_4cat, 
      description = "SR_60. Has that person ever been in trouble with the police",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9 
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_person_job_4cat, 
      description = "SR_61. Did that person have a job at the time when these things happened?",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9 
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_person_help_4cat, 
      description = "SR_63. Did that person ever help you out with any day to day things, like shopping, taking medicines, driving you places, getting dressed, and that type of thing?",
      skip_pattern = "SP_10. IF SR_57b = Yes, go to SR_64. All other answers, go to Go to FNW_T1",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9 
      ),
      col_type = "Categorical"
    ) %>%

    cb_add_col_attributes( 
      sexual_person_no_live_4cat, 
      description = "SR_64. Would you be able to live on your own if that person no longer lived with you?",
      skip_pattern = "All answers, go to FNW_T1",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9 
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_harm_65_4cat, 
      description = "Were you age 65 or older the last time (most recent time) this happened?",
      skip_pattern = "If yes, go to SR_T8. Else, go to FNW_T1",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9 
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_touched_65_4cat, 
      description = "Were you age 65 or older the last time (most recent time) this happened?",
      skip_pattern = "If yes, go to SR_T8. Else, go to FNW_T1",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9 
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_forced_65_4cat, 
      description = "Were you age 65 or older the last time (most recent time) this happened?",
      skip_pattern = "If yes, go to SR_T8. Else, go to FNW_T1",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9 
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_picture_65_4cat, 
      description = "Were you age 65 or older the last time (most recent time) this happened?",
      skip_pattern = "If yes, go to SR_T8. Else, go to FNW_T1",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9 
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_incident_reported_v2_4cat, 
      description = "SR_54. Did you or anyone else report what happened to the police or other authorities?",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9 
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_person_live_then_4cat, 
      description = "SR_57a. Did that person (any of those people) live with you when these things happened?",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9 
      ),
      col_type = "Categorical"
    ) %>%
    cb_add_col_attributes( 
      sexual_person_live_now_4cat, 
      description = "SR_57b. Does that person (any of those people) live with you now?",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9 
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_harm_4cat_f, 
      description = "SR_49a. Regardless of how long ago it happened or who made the advances, has anyone ever made you have sex or oral sex by using force or threatening to harm you or someone close to you?",
      skip_pattern = "If 'Yes', go to SR_49b. All other answers, go to SR_50a"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_touched_4cat_f, 
      description = "SR_50a. Females- Has anyone ever touched your breasts or pubic area or made you touch his penis by using force or threat of force? Males - Has anyone ever touched your pubic area or made you touch their pubic area by using force or threat of force?",
      skip_pattern = "If 'Yes', go to SR_50b. All other answers, go to SR_51a"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_forced_4cat_f, 
      description = "SR_51a. Females- Has anyone ever forced you to undress or expose your breasts or pubic area when you didn’t want to? Males- Has anyone ever forced you to undress or expose your pubic area when you didn’t want to?",
      skip_pattern = "If 'Yes', go to SR_51b. All other answers, go to SR_52_a"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_picture_4cat_f, 
      description = "SR_52a. Has anyone ever taken a picture of you with your clothes partially or completely taken off when you didn’t want them to?",
      skip_pattern = "If 'Yes', go to SR_52b. All other answers, go to SR_53a"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_incident_60_4cat_f, 
      description = "Question from an older version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_incident_reported_4cat_f, 
      description = "Question from an older version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_incident_person_4cat_f, 
      description = "Question from an older version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_person_4cat_f, 
      description = "Question from an older version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_person_live_4cat_f, 
      description = "Question from an older version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_person_alcohol_4cat_f, 
      description = "SR_58. Did that person have a problem with alcohol or drugs at the time when these things happened?"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_person_counseling_4cat_f, 
      description = "SR_59. Has that person ever received inpatient or outpatient counseling for emotional problems?"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_person_police_4cat_f, 
      description = "SR_60. Has that person ever been in trouble with the police?"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_person_job_4cat_f, 
      description = "SR_61. Did that person have a job at the time when these things happened?"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_person_help_4cat_f, 
      description = "SR_63. Did that person ever help you out with any day to day things, like shopping, taking medicines, driving you places, getting dressed, and that type of thing?",
      skip_pattern = "SP_10. IF SR_57b = Yes, go to SR_64. All other answers, go to Go to FNW_T1"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_person_no_live_4cat_f, 
      description = "SR_64. Would you be able to live on your own if that person no longer lived with you?",
      skip_pattern = "All answers, go to FNW_T1"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_harm_65_4cat_f, 
      description = "Were you age 65 or older the last time (most recent time) this happened?",
      skip_pattern = "If yes, go to SR_T8. Else, go to FNW_T1"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_touched_65_4cat_f, 
      description = "Were you age 65 or older the last time (most recent time) this happened?",
      skip_pattern = "If yes, go to SR_T8. Else, go to FNW_T1"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_forced_65_4cat_f, 
      description = "Were you age 65 or older the last time (most recent time) this happened?",
      skip_pattern = "If yes, go to SR_T8. Else, go to FNW_T1"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_picture_65_4cat_f, 
      description = "Were you age 65 or older the last time (most recent time) this happened?",
      skip_pattern = "If yes, go to SR_T8. Else, go to FNW_T1"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_incident_reported_v2_4cat_f, 
      description = "SR_54. Did you or anyone else report what happened to the police or other authorities?"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_person_live_then_4cat_f, 
      description = "SR_57a. Did that person (any of those people) live with you when these things happened?"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_person_live_now_4cat_f, 
      description = "SR_57b. Does that person (any of those people) live with you now?"
    ) 

self_report <- self_report %>%
  
    cb_add_col_attributes( 
      sexual_harm_last_time_8cat, 
      description = "SR_49d. How long ago was the last time (most recent time) this happened?",
      value_labels = c(
        "Less than 1 month ago"                       = 1,
        "Between 1 month and less than 3 months ago"  = 2,
        "Between 3 months and less than 6 months ago" = 3,
        "Between 6 months and less than 1 year ago"   = 4,
        "Between 1 year and less than 3 years ago"    = 5,
        "3 or more years ago"                         = 6,
        "Don’t know"                                  = 7,
        "Refused"                                     = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_touched_last_time_8cat, 
      description = "SR_49d. How long ago was the last time (most recent time) this happened?",
      value_labels = c(
        "Less than 1 month ago"                       = 1,
        "Between 1 month and less than 3 months ago"  = 2,
        "Between 3 months and less than 6 months ago" = 3,
        "Between 6 months and less than 1 year ago"   = 4,
        "Between 1 year and less than 3 years ago"    = 5,
        "3 or more years ago"                         = 6,
        "Don’t know"                                  = 7,
        "Refused"                                     = 9
      ),
      col_type = "Categorical"
    ) %>%

    cb_add_col_attributes( 
      sexual_forced_last_time_8cat, 
      description = "SR_49d. How long ago was the last time (most recent time) this happened?",
      value_labels = c(
        "Less than 1 month ago"                       = 1,
        "Between 1 month and less than 3 months ago"  = 2,
        "Between 3 months and less than 6 months ago" = 3,
        "Between 6 months and less than 1 year ago"   = 4,
        "Between 1 year and less than 3 years ago"    = 5,
        "3 or more years ago"                         = 6,
        "Don’t know"                                  = 7,
        "Refused"                                     = 9
      ),
      col_type = "Categorical"
    ) %>%

    cb_add_col_attributes( 
      sexual_picture_last_time_8cat, 
      description = "SR_49d. How long ago was the last time (most recent time) this happened?",
      value_labels = c(
        "Less than 1 month ago"                       = 1,
        "Between 1 month and less than 3 months ago"  = 2,
        "Between 3 months and less than 6 months ago" = 3,
        "Between 6 months and less than 1 year ago"   = 4,
        "Between 1 year and less than 3 years ago"    = 5,
        "3 or more years ago"                         = 6,
        "Don’t know"                                  = 7,
        "Refused"                                     = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_harm_last_time_8cat_f, 
      description = "SR_49d. How long ago was the last time (most recent time) this happened?"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_touched_last_time_8cat_f, 
      description = "SR_49d. How long ago was the last time (most recent time) this happened?"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_forced_last_time_8cat_f, 
      description = "SR_49d. How long ago was the last time (most recent time) this happened?"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_picture_last_time_8cat_f, 
      description = "SR_49d. How long ago was the last time (most recent time) this happened?"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_harm_times_7cat, 
      description = "SR_51b. About how many times has this happened to you in your lifetime?",
      value_labels = c(
        "1 or 2 times"                      = 1,
        "Between 3 and less than 5 times"   = 2,
        "Between 5 and less than 10 times"  = 3,
        "Between 10 and less than 20 times" = 4,
        "20 or more times"                  = 5,
        "Don’t know"                        = 7,
        "Refused"                           = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_touched_times_7cat, 
      description = "SR_51b. About how many times has this happened to you in your lifetime?",
      value_labels = c(
        "1 or 2 times"                      = 1,
        "Between 3 and less than 5 times"   = 2,
        "Between 5 and less than 10 times"  = 3,
        "Between 10 and less than 20 times" = 4,
        "20 or more times"                  = 5,
        "Don’t know"                        = 7,
        "Refused"                           = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_forced_times_7cat, 
      description = "SR_51b. About how many times has this happened to you in your lifetime?",
      value_labels = c(
        "1 or 2 times"                      = 1,
        "Between 3 and less than 5 times"   = 2,
        "Between 5 and less than 10 times"  = 3,
        "Between 10 and less than 20 times" = 4,
        "20 or more times"                  = 5,
        "Don’t know"                        = 7,
        "Refused"                           = 9
      ),
      col_type = "Categorical"
    ) %>%
 
    cb_add_col_attributes( 
      sexual_picture_times_7cat, 
      description = "SR_51b. About how many times has this happened to you in your lifetime?",
      value_labels = c(
        "1 or 2 times"                      = 1,
        "Between 3 and less than 5 times"   = 2,
        "Between 5 and less than 10 times"  = 3,
        "Between 10 and less than 20 times" = 4,
        "20 or more times"                  = 5,
        "Don’t know"                        = 7,
        "Refused"                           = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_harm_times_7cat_f, 
      description = "SR_51b. About how many times has this happened to you in your lifetime?"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_touched_times_7cat_f, 
      description = "SR_51b. About how many times has this happened to you in your lifetime?"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_forced_times_7cat_f, 
      description = "SR_51b. About how many times has this happened to you in your lifetime?"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_picture_times_7cat_f, 
      description = "SR_51b. About how many times has this happened to you in your lifetime?"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_person_friends_6cat, 
      description = "SR_62. How many friends did that person have at the time when these things happened? Would you say…",
      value_labels = c(
        "None"            = 0,
        "Very few (1 -3)" = 1,
        "Some (4 -6)"     = 2,
        "A lot (7+)"      = 3,
        "Don’t know"      = 7,
        "Refused"         = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_person_friends_6cat_f, 
      description = "SR_62. How many friends did that person have at the time when these things happened? Would you say…"
    ) %>%
  
cb_add_col_attributes( 
  sexual_incident_person_v2_12cat_f, 
  description = "SR_56. What was your relationship to the person, or people, who treated you this way? (MULTIPLE RECORD)",
  skip_pattern = "IF SR_56 = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, OR 11} Go to SR_57a. Else, go to FNW_T1"
) %>%
  
  cb_add_col_attributes( 
    sexual_incident_person_v2_12cat, 
  description = "SR_56. What was your relationship to the person, or people, who treated you this way? (MULTIPLE RECORD)",
  skip_pattern = "IF SR_56 = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, OR 11} Go to SR_57a. Else, go to FNW_T1",
    value_labels = c(
      "A spouse or partner"     = 1, 
      "An ex spouse or partner" = 2, 
      "A parent or step-parent" = 3, 
      "A brother or sister"     = 4, 
      "A son or daughter"       = 5, 
      "Another relative"        = 6, 
      "A coworker"              = 7, 
      "A neighbor"              = 8, 
      "A friend"                = 9, 
      "Some other non-relative" = 10,
      "Don't know"              = 77, 
      "Refused"                 = 99
    ),
    col_type = "Categorical"
  ) %>%
  
cb_add_col_attributes( 
  sexual_person_12cat_f, 
  description = "Question from an older version of the follow-up interview"
) %>%
  
  cb_add_col_attributes( 
    sexual_person_12cat, 
    description = "Question from an older version of the follow-up interview",
    value_labels = c(
      "A spouse or partner"     = 1, 
      "An ex spouse or partner" = 2, 
      "A parent or step-parent" = 3, 
      "A brother or sister"     = 4, 
      "A son or daughter"       = 5, 
      "Another relative"        = 6, 
      "A coworker"              = 7, 
      "A neighbor"              = 8, 
      "A friend"                = 9, 
      "Some other non-relative" = 10,
      "Don't know"              = 77, 
      "Refused"                 = 99
    ),
    col_type = "Categorical"
  ) %>%
  
    cb_add_col_attributes( 
      fear_afraid_2cat, 
      description = "FNW_1. What do you worry most about right now?",
      value_labels = c(
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      fear_future_2cat, 
      description = "FNW_2. What is your greatest fear for your future?",
      value_labels = c(
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      fear_grateful_2cat, 
      description = "FNW_3. What are you most grateful for right now?",
      value_labels = c(
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      fear_forward_2cat, 
      description = "FNW_4. What are you most looking forward to for your future?",
      value_labels = c(
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      fear_important_2cat, 
      description = "FNW_5. What is the single most important thing that someone outside of your friends and family could do to benefit your quality of life right now?",
      value_labels = c(
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    )%>% 

    cb_add_col_attributes( 
      fear_afraid_2cat_f, 
      description = "FNW_1. What do you worry most about right now?"
    ) %>%
  
    cb_add_col_attributes( 
      fear_future_2cat_f, 
      description = "FNW_2. What is your greatest fear for your future?"
    ) %>%
  
    cb_add_col_attributes( 
      fear_grateful_2cat_f, 
      description = "FNW_3. What are you most grateful for right now?"
    ) %>%
  
    cb_add_col_attributes( 
      fear_forward_2cat_f, 
      description = "FNW_4. What are you most looking forward to for your future?"
    ) %>%
  
    cb_add_col_attributes( 
      fear_important_2cat_f, 
      description = "FNW_5. What is the single most important thing that someone outside of your friends and family could do to benefit your quality of life right now?"
    ) %>%
  
    cb_add_col_attributes( 
      report_private_5cat, 
      description = "SR_98 [Please don’t read — just complete on your own]. Was another person (e.g., caregivers, family members, friends, etc.) present when completing THIS SECTION (Self-Report Injury, Violence, Neglect, & Exploitation) of the interview?",
      skip_pattern = "If 'No' or 'Don't know', go to Section 5(APS Investigations). All other answers, go to SR_99.",
      value_labels = c(
        "Yes, for the entire time"                       = 1,
        "Yes, for part of the time"                      = 2,
        "No, but they were still close enough to hear"   = 3,
        "No"                                             = 4,
        "Don’t know"                                     = 7
      ),
      col_type = "Categorical"
    ) %>%

    cb_add_col_attributes( 
      report_private_5cat_f, 
      description = "SR_98 [Please don’t read — just complete on your own]. Was another person (e.g., caregivers, family members, friends, etc.) present when completing THIS SECTION (Self-Report Injury, Violence, Neglect, & Exploitation) of the interview?",
      skip_pattern = "If 'No' or 'Don't know', go to Section 5(APS Investigations). All other answers, go to SR_99."
    ) %>%
  
    cb_add_col_attributes( 
      report_influence_4cat, 
      description = "SR_99 [Please don’t read — just complete on your own]. Did you get the impression that the presence of other people (e.g., caregivers, family members, friends, etc.) may have affected the answers given by the patient during THIS SECTION (Self-Report Injury, Violence, Neglect, & Exploitation) of the interview?",
      value_labels = c(
        "Yes"         = 1,
        "No"          = 2,
        "Don’t know"  = 7
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      report_influence_4cat_f, 
      description = "SR_99 [Please don’t read — just complete on your own]. Did you get the impression that the presence of other people (e.g., caregivers, family members, friends, etc.) may have affected the answers given by the patient during THIS SECTION (Self-Report Injury, Violence, Neglect, & Exploitation) of the interview?"
    )%>%
  
    cb_add_col_attributes( 
      emotional_yelled_times_times, 
      description = "Question from earlier version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_yelled_age, 
      description = "Question from earlier version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_yelled_age_years, 
      description = "Question from earlier version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_embarrassed_times_times, 
      description = "Question from earlier version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_embarrassed_age, 
      description = "Question from earlier version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_embarrassed_age_years, 
      description = "Question from earlier version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_harassed_times_times, 
      description = "Question from earlier version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_harassed_age, 
      description = "Question from earlier version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_harassed_age_years, 
      description = "Question from earlier version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_refused_times_times, 
      description = "Question from earlier version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_refused_age, 
      description = "Question from earlier version of the follow-up interview"
    ) %>%

      cb_add_col_attributes( 
      emotional_refused_age_years, 
      description = "Question from earlier version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      physical_hit_times_times, 
      description = "Question from an older version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      physical_hit_age, 
      description = "Question from an older version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      physical_hit_age_years, 
      description = "Question from an older version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      physical_restrain_times_times, 
      description = "Question from an older version of the follow-up intervie"
    ) %>%

    cb_add_col_attributes( 
      physical_restrain_age, 
      description = "Question from an older version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      physical_restrain_age_years, 
      description = "Question from an older version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      physical_hurt_times_times, 
      description = "Question from an older version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      physical_hurt_age, 
      description = "Question from an older version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      physical_hurt_age_years, 
      description = "Question from an older version of the follow_up interview"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_harm_times_times, 
      description = "Question from an older version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_harm_age, 
      description = "Question from an older version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_harm_age_years, 
      description = "Question from an older version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_touched_times_times, 
      description = "Question from an older version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_touched_age, 
      description = "Question from an older version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_touched_age_years, 
      description = "Question from an older version of the follow-up interview"
    ) %>%

    cb_add_col_attributes( 
      sexual_forced_times_times, 
      description = "Question from an older version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_forced_age, 
      description = "Question from an older version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_forced_age_years, 
      description = "Question from an older version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_picture_times_times, 
      description = "Question from an older version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_picture_age, 
      description = "Question from an older version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_picture_age_years, 
      description = "Question from an older version of the follow-up interview"
    ) %>%
  
      cb_add_col_attributes( 
      finance_stranger_permission_times_times, 
      description = "Question from earlier version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      finance_stranger_permission_age, 
      description = "Question from earlier version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      finance_stranger_permission_age_years, 
      description = "Question from earlier version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      finance_stranger_forged_times_times, 
      description = "Question from earlier version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      finance_stranger_forged_age, 
      description = "Question from earlier version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      finance_stranger_forged_age_years, 
      description = "Question from earlier version of the follow-up interview"
    ) %>%
   
      cb_add_col_attributes( 
      finance_stranger_tricked_times_times, 
      description = "Question from earlier version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      finance_stranger_tricked_age, 
      description = "Question from earlier version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      finance_stranger_tricked_age_years, 
      description = "Question from earlier version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      fear_afraid_response, 
      description = "FNW_1. What do you worry most about right now? [open ended]"
    ) %>%
  
    cb_add_col_attributes( 
      fear_future_response, 
      description = "FNW_2. What is your greatest fear for your future? [open ended]"
    ) %>%
  
    cb_add_col_attributes( 
      fear_grateful_response, 
      description = "FNW_3. What are you most grateful for right now? [open ended]"
    ) %>%
  
    cb_add_col_attributes( 
      fear_forward_response, 
      description = "FNW_4. What are you most looking forward to for your future? [open ended]"
    ) %>%
  
    cb_add_col_attributes( 
      fear_important_response, 
      description = "FNW_5. What is the single most important thing that someone outside of your friends and family could do to benefit your quality of life right now? [open ended]"
    ) %>%

    cb_add_col_attributes( 
      xc_emotional_list, 
      description = "Calculated comma-separated list of the selected emotional mistreatment that the participant reported; used internally by the database to display a customized follow-up question to the participant"
    ) %>% 
 
    cb_add_col_attributes( 
      xc_physical_list, 
      description = "Calculated comma-separated list of the selected physical mistreatment that the participant reported; used internally by the database to display a customized follow-up question to the participant"
    ) %>% 
  
    cb_add_col_attributes( 
      xc_sexual_list, 
      description = "Calculated comma-separated list of the selected sexual mistreatment that the participant reported; used internally by the database to display a customized follow-up question to the participant"
    ) %>%

    cb_add_col_attributes( 
      xc_case_id, 
      description = "Calculated by the database from the last 5 characters of the MedstarID"
    ) %>% 

    cb_add_col_attributes( 
      x_primary_key, 
      description = "unique record id"
    ) %>%   

    cb_add_col_attributes( 
      xc_lead_panel_summary_count, 
      description = "Calculated count of positive abuse instances across SelfReport, ApsInvestigations, and ObservationalMeasures"
    )   
```

# Pass data frame to the codebook() function

```{r}
# Add title and description to codebook
self_report_codebook <- codebook(
  df = self_report,
  title = "Self Report Dataset",
  description = "Data collected during DETECT follow-up interviews on self-report of injury, violence, neglect, and exploitation.",
  no_summary_stats = no_stats_vars)
```

```{r}
print(self_report_codebook, "self_report_codebook.docx")
```
