---
title: "Sociodemographic Information Codebook"
---

```{r}
# Load necessary packages and functions
library(codebookr)
library(dplyr, warn.conflicts = FALSE)
library(readr)
source("../r/variable_descriptions.R")
```

# Purpose of the program

Using the CodebookR package, we will create a data dictionary for follow-up interview data for the DETECT project.
# Load cleaned data

```{r}
#| warning: false
socdem <- read_rds("../data/cleaned_rds_files/sociodemographic_information_import.rds")
```
# Set column attributes

```{r}
#Set the source to "DETECT Follow-up Interview Questions - Sociodemographic Information" for all the variables
socdem_vars <- socdem %>% 
  names()

for(i in socdem_vars) {
  attr(socdem[[i]], "source") <- "DETECT Follow-up Interview Questions - Sociodemographic Information"
}
```

```{r}
# Choose variables that will not have summary statistics
no_stats <- socdem %>%
  select(
     c(matches("^(x|xc)_"), matches("^(name)"), medstar_id)
    )

no_stats_vars <- colnames(no_stats)
```


```{r}
# Add column attributes to all variables
sociodemographic_information <- socdem %>%
    cb_add_col_attributes( 
      x_primary_key, 
      description = "Unique record ID used internally by the database"
    ) %>%
  
    cb_add_col_attributes( 
      x_created_by, 
      description = "Person who created the record"
    ) %>%
  
    cb_add_col_attributes( 
      x_created_timestamp, 
      description = "Timestamp when the record was created",
      col_type = "Time"
    ) %>%
  
    cb_add_col_attributes( 
      x_modified_by, 
      description = "Person who modified the record"
    ) %>%
  
    cb_add_col_attributes( 
      x_modified_timestamp, 
      description = "Timestamp when the record was modified",
      col_type = "Time"
    ) %>%
  
    cb_add_col_attributes( 
      x_error_message, 
      description = "Error message entered by research team"
    ) %>%
  
    cb_add_col_attributes( 
      x_record_month, 
      description = "Month record was created",
      col_type = "Time"
    ) %>%
  
    cb_add_col_attributes( 
      x_record_year, 
      description = "Year record was created",
      col_type = "Time"
    ) %>%
  
    cb_add_col_attributes( 
      x_record_status, 
      description = "Status of the record as determined by research team"
    ) %>%
  
    cb_add_col_attributes( 
      x_record_comment, 
      description = "Comments by interviewer"
    ) %>%
  
    cb_add_col_attributes( 
      medstar_id, 
      description = "Unique record number in MedStar System"
    ) %>%
  
    cb_add_col_attributes( 
      name_full, 
      description = "Full name of older individual"
    ) %>%

    cb_add_col_attributes( 
      xc_case_id, 
      description = "Calculated by the database from the last 5 characters of the MedstarID"
    ) %>%
  
    cb_add_col_attributes( 
      sode_people, 
      description = "SI_1. Including you how many people live in this household?"
    ) %>%
  
    cb_add_col_attributes( 
      sode_marital_8cat, 
      description = "Recoded variable sode_marital to match levels in follow-up interview protocol",
      value_labels = c(
        "Married"                                     = 1,
        "Living as an unmarried or common law couple" = 2,
        "Separated"                                   = 3,
        "Divorced"                                    = 4,
        "Widowed"                                     = 5,
        "Single, or never married"                    = 6,
        "Don’t know"                                  = 7,
        "Refused"                                     = 9
      )
    ) %>%
  
    cb_add_col_attributes( 
      sode_marital_8cat_f, 
      description = "SI_2. What is your marital status? Would you say you are…"
    ) %>%
  
    cb_add_col_attributes( 
      sogi_identity_5cat, 
      description = "SOGI_1. What is your gender identity?",
      value_labels = c(
        "Male"       = 1,
        "Female"     = 2,
        "Other"      = 3,
        "Don’t know" = 7,
        "Refused"    = 9
      )
    ) %>%
  
    cb_add_col_attributes( 
      sogi_identity_5cat_f, 
      description = "SOGI_1. What is your gender identity?"
    ) %>%
  
    cb_add_col_attributes( 
      sogi_orientation_8cat, 
      description = "SOGI_2. What best describes your sexual orientation?",
      value_labels = c(
        "Straight/heterosexual" = 1,
        "Gay man"               = 2,
        "Lesbian/gay woman"     = 3,
        "Bisexual"              = 4,
        "Queer"                 = 5,
        "Other"                 = 6,
        "Don’t know"            = 7,
        "Refused"               = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sogi_orientation_8cat_f, 
      description = "SOGI_2. What best describes your sexual orientation?"
    ) %>%
  
    cb_add_col_attributes( 
      sode_age_4cat, 
      description = "SI_3. How old are you?",
      value_labels = c(
        "Age 65 to 100+" = 1,
        "Don’t know"     = 7,
        "Refused"        = 9
      )
    ) %>%
  
    cb_add_col_attributes( 
      sode_age_4cat_f, 
      description = "SI_3. How old are you?"
    ) %>%
  
    cb_add_col_attributes( 
      sode_age_years, 
      description = "Reported age of older individual - Question used in older version of protocol"
    ) %>%
  
    cb_add_col_attributes( 
      sode_hispanic_4cat, 
      description = "SI_4. Are you of Hispanic or Latino origin?", 
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      )
    ) %>%
  
    cb_add_col_attributes( 
      sode_hispanic_4cat_f, 
      description = "SI_4. Are you of Hispanic or Latino origin?"
    ) %>%

    cb_add_col_attributes( 
      american_indian_or_alaska_native, 
      description = "sode_race dummy variable for american inidian or alaska native category"
    ) %>%
  
    cb_add_col_attributes( 
      asian, 
      description = "sode_race dummy variable for asian category"
    ) %>%

    cb_add_col_attributes( 
      black_or_african_american, 
      description = "sode_race dummy variable for black or african american category"
    ) %>%
  
    cb_add_col_attributes( 
      native_hawaiian_or_other_pacific_islander, 
      description = "sode_race dummy variable for native hawaiian or other pacific islander category"
    ) %>%
  
    cb_add_col_attributes( 
      white, 
      description = "sode_race dummy variable for white category"
    ) %>%
  
    cb_add_col_attributes( 
      other, 
      description = "sode_race dummy variable for other category"
    ) %>%
  
    cb_add_col_attributes( 
      sode_school_9cat, 
      description = "SI_6. What is the highest level of schooling you completed",
      value_labels = c(
        "Some high school (no diploma)"                                  = 1,
        "High school graduate"                                           = 2,
        "Some college (no degree)"                                       = 3,
        "Associate’s degree"                                             = 4,
        "Bachelor’s degree (BA, AB, BS, etc.)"                           = 5,
        "Some graduate or professional school (no degree)"               = 6,
        "Graduate or professional school degree (MS, MA, MD, PhD, etc.)" = 7,
        "Don’t know"                                                     = 77,
        "Refused"                                                        = 99
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sode_school_9cat_f, 
      description = "SI_6. What is the highest level of schooling you completed"
    ) %>%
  
    cb_add_col_attributes( 
      sode_employed_11cat, 
      description = "SI_7. What is your employment status? Would you say you are…",
      value_labels = c(
        "Employed full time"         = 1,
        "Employed part time"         = 2,
        "In the military"            = 3,
        "Unemployed"                 = 4,
        "Retired"                    = 5,
        "A student"                  = 6,
        "A homemaker"                = 7,
        "Disabled or unable to work" = 8,
        "Something else"             = 9,
        "Don’t know"                 = 77,
        "Refused"                    = 99
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sode_employed_11cat_f, 
      description = "SI_7. What is your employment status? Would you say you are…"
    ) %>%
  
    cb_add_col_attributes( 
      sode_income_9cat, 
      description = "SI_8. Including everyone else in your household, which of the following categories best describes your total household income before taxes? Is it..",
      value_labels = c(
        "$10,000 or less"              = 1,
        "Between $10,001 and $20,000"  = 2,
        "Between $20,001 and $35,000"  = 3,
        "Between $35,001 and $50,000"  = 4,
        "Between $50,001 and $75,000"  = 5,
        "Between $75,001 and $100,000" = 6,
        "More than $100,000"           = 7,
        "Don’t know"                   = 77,
        "Refused"                      = 99
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sode_income_9cat_f, 
      description = "SI_8. Including everyone else in your household, which of the following categories best describes your total household income before taxes? Is it.."
    ) %>%
  
    cb_add_col_attributes( 
      sode_military_4cat, 
      description = "SI_9. Have you ever served in the military (e.g., on active duty in the U.S. Armed Forces, Reserves, or National Guard)?", 
      skip_pattern = "If answer is yes, go to SI_10. For all other answers, go to SI_11",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      )
    ) %>%
  
    cb_add_col_attributes( 
      sode_military_4cat_f, 
      description = "SI_9. Have you ever served in the military (e.g., on active duty in the U.S. Armed Forces, Reserves, or National Guard)?", 
      skip_pattern = "If answer is yes, go to SI_10. For all other answers, go to SI_11"
    ) %>%
  
    cb_add_col_attributes( 
      sode_unwanted_4cat, 
      description = "When you were in the military: SI_10.  Did you ever receive unwanted, threatening or repeated sexual attention (for example, touching, cornering, pressure for sexual favors, or inappropriate verbal remarks, etc.?)",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      )
    ) %>%
  
    cb_add_col_attributes( 
      sode_unwanted_4cat_f, 
      description = "When you were in the military: SI_10.  Did you ever receive unwanted, threatening or repeated sexual attention (for example, touching, cornering, pressure for sexual favors, or inappropriate verbal remarks, etc.?)"
    ) %>%
  
    cb_add_col_attributes( 
      sode_sexual_4cat, 
      description = "SI_11. Did you have sexual contact against your will or when you were unable to say no (for example, after being forced or threatened or to avoid other consequences?)",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      )
    ) %>%
  
    cb_add_col_attributes( 
      sode_sexual_4cat_f, 
      description = "SI_11. Did you have sexual contact against your will or when you were unable to say no (for example, after being forced or threatened or to avoid other consequences?)"
    ) %>%
  
    cb_add_col_attributes( 
      hsi_contact_4cat, 
      description = "HS_1. Would it be alright if we contact you again in the future?",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      )
    ) %>%
  
    cb_add_col_attributes( 
      hsi_contact_4cat_f, 
      description = "HS_1. Would it be alright if we contact you again in the future?"
    )%>%
  
    cb_add_col_attributes( 
      sode_people_3cat, 
      description = "SI_1. Including you how many people live in this household?",
      value_labels = c(
        "Number 1 to 9+"  = 1:9,
        "Don't know"      = 77,
        "Refused"         = 99
      )
    ) %>%
  
    cb_add_col_attributes( 
      sode_people_3cat_f, 
      description = "SI_1. Including you how many people live in this household?"
    ) %>%
  
    cb_add_col_attributes( 
      sode_people_cont, 
      description = "SI_1. Including you how many people live in this household? (continuous variable that excludes non-numerical responses in sode_people)."
    ) %>%
  
    cb_add_col_attributes( 
      sode_race_8cat, 
      description = "SI_5. Which of the following racial categories describes you? You may select more than one.",
      value_labels = c(
        "American Indian or Alaskan Native"         = 1,
        "Asian"                                     = 2,
        "Black or African American"                 = 3,
        "Native Hawaiian or Other Pacific Islander" = 4,
        "White"                                     = 5,
        "Other race or multiple races"              = 6, 
        "Don't know"                                = 7, 
        "Refused"                                   = 8
 
        )
    ) %>%
    cb_add_col_attributes( 
      sode_race_8cat_f, 
      description = "SI_5. Which of the following racial categories describes you? You may select more than one."
    ) %>%
  
    cb_add_col_attributes( 
      sode_race_eth_6cat, 
      description = "Ethnicity the participant self-identifies with. Derived from sode_race and sode_hispanic variables.",
      value_labels = c(
      "Hispanic, any race"                         = 1, 
      "Black, non-Hispanic"                        = 2, 
      "White, non-Hispanic"                        = 3,
      "Other race or multiple races, non-Hispanic" = 4,
      "Don't know"                                 = 5, 
      "Refused"                                    = 6                    

      )
    ) %>%
  
    cb_add_col_attributes( 
      sode_race_eth_6cat_f, 
      description = "Ethnicity the participant self-identifies with. Derived from sode_race and sode_hispanic variables."
    )

```
# Create a data frame containing the column names and their descriptions using the var_descriptions function

```{r}
soc_desc <- var_descriptions(sociodemographic_information)
```

## Save as rds file
```{r}
write_rds(soc_desc, "../codebooks/variable_descriptions/sociodemographic_information_var_desc.rds")
```

# Pass data frame to the codebook() function

```{r}
# Add title and description to codebook
socdem_codebook <- codebook(
  df = sociodemographic_information,
  title = "Sociodemographic Information Dataset",
  description = "Data collected during DETECT follow-up interviews about sociodemographic information",
  no_summary_stats = no_stats_vars)
```

```{r}
print(socdem_codebook, "../codebooks/sociodemographic_information_codebook.docx")
```


