---
title: "CodebookR Self-Report data from recoded data"
author: "Marissa Gough"
---

```{r}
# Load necessary packages
library(codebookr)
library(dplyr, warn.conflicts = FALSE)
library(readr)
library(stringr)
```

# Purpose of the program

Using the CodebookR package, we will create a data dictionary for follow-up interview data for the DETECT project.

```{r}
# Load data from Self Report data set
sr <- read_rds("~.../detect_public/data/sr_factor.rds") #598 576
```


```{r}
# Remove vertical tab data frame
# for example, remove all spaces
sr <- sr %>% 
  mutate(across(where(is.character), str_remove_all, pattern = fixed("\v")))
```

# Set column attributes

```{r}
# Create a vector of column names that have the same source, in this case administrative data
admin_vars <- sr %>% 
  select(1:11) %>%  # Choose the first columns in the data frame
  names()

for(i in admin_vars) {
  attr(sr[[i]], "source") <- "Administrative data"
}
```

```{r}
# Create a vector of column names that have the same source, in this case, neglect variables
neglect_vars <- sr %>% 
  select('neglect_go':'neglect_person') %>% 
  names()

for(i in neglect_vars) {
  attr(sr[[i]], "source") <- "DETECT follow-up interview: Self-report neglect variables"
}
```

```{r}
# Create a vector of column names that have the same source, in this case,financial abuse variables
finance_vars <- sr %>% 
  select('finance_help':'finance_stranger_tricked_age_years') %>% 
  names()

for(i in finance_vars) {
  attr(sr[[i]], "source") <- "DETECT follow-up interview: Self-report financial abuse variables"
}
```

```{r}
# Create a vector of column names that have the same source, in this case emotional abuse variables
emotional_vars <- sr %>% 
  select('emotional_yelled':'emotional_person_no_live') %>% 
  names()

for(i in emotional_vars) {
  attr(sr[[i]], "source") <- "DETECT follow-up interview: Self-report emotional abuse variables"
}
```

```{r}
# Create a vector of column names that have the same source, in this case physical abuse variables
physical_vars <- sr %>% 
  select('physical_hit':'physical_person_no_live') %>% 
  names()

for(i in physical_vars) {
  attr(sr[[i]], "source") <- "DETECT follow-up interview: Self-report physical abuse variables"
}
```

```{r}
# Create a vector of column names that have the same source, in this case sexual abuse variables
sexual_vars <- sr %>% 
  select('sexual_harm':'sexual_person_no_live') %>% 
  names()

for(i in sexual_vars) {
  attr(sr[[i]], "source") <- "DETECT follow-up interview: Self-report sexual abuse variables"
}
```

```{r}
# Create a vector of column names that have the same source, in this case, fears, wants, needs variables
fwn_vars <- sr %>% 
  select('fear_afraid':'fear_important_response') %>% 
  names()

for(i in fwn_vars) {
  attr(sr[[i]], "source") <- "DETECT follow-up interview: Self-report fear, wants, needs variables"
}
```

```{r}
# Create a vector of column names that have the same source, in this case, APS report variables
report_vars <- sr %>% 
  select('report_private':'report_influence') %>% 
  names()

for(i in report_vars) {
  attr(sr[[i]], "source") <- "DETECT follow-up interview: Self-report APS report variables"
}
```

```{r}
# Create a vector of column names that have the same source, in this case, recoded factor variables
factor_vars <- sr %>% 
  select('neglect_go_4cat':'report_influence_4cat_f') %>% 
  names()

for(i in fwn_vars) {
  attr(sr[[i]], "source") <- "Recoded from the raw self-report data"
}
```

```{r}
# Create a template for all variables in the data frame
for (i in seq_along(names(sr))) {
  cat(paste0('
    cb_add_col_attributes( \n    ',
      "  ", names(sr)[i], ', \n    ',
      "  ", 'description = ""
    ) %>%
  '))
}
```

```{r}
#Add column attributes to all self-report variables
sr <- sr %>%
  
  cb_add_col_attributes( 
      x_created_by, 
      description = ""
    ) %>%
  
    cb_add_col_attributes( 
      x_created_timestamp, 
      description = ""
    ) %>%
  
    cb_add_col_attributes( 
      x_modified_by, 
      description = ""
    ) %>%
  
    cb_add_col_attributes( 
      x_modified_timestamp, 
      description = ""
    ) %>%
  
    cb_add_col_attributes( 
      x_error_message, 
      description = ""
    ) %>%
  
    cb_add_col_attributes( 
      x_record_month, 
      description = ""
    ) %>%
  
    cb_add_col_attributes( 
      x_record_year, 
      description = ""
    ) %>%
  
    cb_add_col_attributes( 
      x_record_status, 
      description = ""
    ) %>%
  
    cb_add_col_attributes( 
      x_record_comment, 
      description = ""
    ) %>%
  
    cb_add_col_attributes( 
      medstar_id, 
      description = ""
    ) %>%
  
    cb_add_col_attributes( 
      name_full, 
      description = ""
    ) %>%
  
    cb_add_col_attributes( 
      neglect_go, 
      description = "SR_1a. Do you need someone to help you get to the places you need to go, for example do you need someone to drive you to the grocery store, a place of worship, the doctor?",
      skip_pattern = "If 'Yes', go to SR_1b. All other answers, go to SR_2a"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_go_help, 
      description = "SR_1b. Do you have someone who helps with this?",
      skip_pattern = "If 'Yes, one person' or 'Yes, more than one person', go to SR_1c. All other answers, go to SR_2a"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_go_reliable, 
      description = "SR_1c. How reliable would you say (that person/these people) is/are? Would you say they are… (READ LIST)"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_food, 
      description = "SR_2a. Do you need someone to make sure you have enough food, medicines or any other things you need in your house?",
      skip_pattern =  "If 'Yes', go to SR_2b. All other answers, go to SR_3a"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_food_help, 
      description = "SR_2b. Do you have someone who helps with this?",
      skip_pattern = "If 'Yes, one person' or 'Yes, more than one person', go to SR_2c. All other answers, go to 3R_2a"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_food_reliable, 
      description = "SR_2c. How reliable would you say (that person/these people) is/are? Would you say they are… (READ LIST)"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_house, 
      description = "SR_3a. Do you need someone to help you with household things, like cooking meals, helping you eat, or making sure you take the correct medicines each day?",
      skip_pattern = "If 'Yes', go to SR_3b. All other answers, go to SR_4a"

    ) %>%
  
    cb_add_col_attributes( 
      neglect_house_help, 
      description = "SR_3b. Do you have someone who helps with this?",
      skip_pattern = "If 'Yes, one person' or 'Yes, more than one person', go to SR_3c. All other answers, go to SR_4a"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_house_reliable, 
      description = "SR_3c. How reliable would you say (that person/these people) is/are? Would you say they are… (READ LIST)"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_clean, 
      description = "SR_4a. Do you need someone to help you with house cleaning or yard work?",
      skip_pattern = "If 'Yes', go to SR_4b. All other answers, go to SR_5a"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_clean_help, 
      description = "SR_4b. Do you have someone who helps with this?",
      skip_pattern = "If 'Yes, one person' or 'Yes, more than one person', go to SR_4c. All other answers, go to SR_5a"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_clean_reliable, 
      description = "SR_4c. How reliable would you say (that person/these people) is/are? Would you say they are… (READ LIST)"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_ready, 
      description = "SR_5a. Do you need someone to help you get out of bed, get showered, or get dressed?",
      skip_pattern = "If 'Yes', go to SR_5b. All other answers, go to SR_6a"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_ready_help, 
      description = "SR_5b. Do you have someone who helps with this?",
      skip_pattern = "If 'Yes, one person' or 'Yes, more than one person', go to SR_5c. All other answers, go to SR_6a"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_ready_reliable, 
      description = "SR_4c. How reliable would you say (that person/these people) is/are? Would you say they are… (READ LIST)"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_bills, 
      description = "SR_6a. Do you need someone to make sure your bills get paid?",
      skip_pattern = "If 'Yes', go to SR_6b. All other answers, go to SR_7a"
      
    ) %>%
  
    cb_add_col_attributes( 
      neglect_bills_help, 
      description = "SR_6b. Do you have someone who helps with this?",
      skip_pattern = "If 'Yes, one person' or 'Yes, more than one person', go to SR_6c. All other answers, go to SR_7a"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_bills_reliable, 
      description = "SR_4c. How reliable would you say (that person/these people) is/are? Would you say they are… (READ LIST)",
      skip_pattern = "IF SR_1b, SR_2b, SR_3b, SR_4b, SR_5b, OR SR_6b = Yes, go to SR_7. All other answers, go to SR_8"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_person, 
      description = "SR_7. Considering all the things that we just talked about, who is the person who is supposed to help you with these things most of the time? (MULTIPLE RECORD)"
    ) %>%
  
    cb_add_col_attributes( 
      finance_help, 
      description = "SR_8. Is there someone who helps you take care of your finances, or is there someone other than yourself who makes decisions about your money and your property, either with or without your approval?",
      skip_pattern = "If 'Yes', go to SR_9. All other answers, go to SR_16"
    ) %>%
  
    cb_add_col_attributes( 
      finance_person, 
      description = "SR_9. What is that person’s relationship to you? (MULTIPLE RECORD)",
      skip_pattern = "If 'Don't know' or 'Refused', go to SR_10. All other answers go to SR_16"
    ) %>%
  
    cb_add_col_attributes( 
      finance_person_permission, 
      description = "SR_10. Does that person usually ask for your permission before deciding to spend your money or sell your property?",
      skip_pattern - "If 'No', go to SR_10a. All other answers, go to SR_11 "
    ) %>%
  
    cb_add_col_attributes( 
      finance_person_decisions, 
      description = "SR_11. Do you feel like that person usually makes good decisions about your finances?"
    ) %>%
  
    cb_add_col_attributes( 
      finance_copies, 
      description = "SR_12. Do you have the copies of paperwork for the financial decisions they make or can you get copies if you wanted them?"
    ) %>%
  
    cb_add_col_attributes( 
      finance_person_forged, 
      description = "SR_13. Has that person ever forged your signature without your permission in order to sell your property or to get money from your accounts?",
      skip_pattern = "If 'Yes', go to SR_13a. All other answers, go to SR_14"
    ) %>%
  
    cb_add_col_attributes( 
      finance_person_tricked, 
      description = "SR_14. Has that person ever forced or tricked you into signing a document so that they would be able to get some of your money or possessions?",
      skip_pattern = "If 'Yes', so to SR_14a. All other answers, go to SR_15"
    ) %>%
  
    cb_add_col_attributes( 
      finance_person_stolen, 
      description = "SR_15. Has that person, or anyone else you are close to, ever stolen your money or take your things for themselves, their friends, or to sell?",
      skip_pattern = "If 'Yes', so to SR_15a. All other answers, go to SR_16"
    ) %>%
  
    cb_add_col_attributes( 
      finance_stranger_permission, 
      description = "SR_16. Has a stranger ever spent your money or sold your property without your permission?",
      skip_pattern = "If 'Yes', so to SR_16a. All other answers, go to SR_17"
    ) %>%
  
    cb_add_col_attributes( 
      finance_stranger_permission_times, 
      description = "Question from earlier version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      finance_stranger_permission_times_times, 
      description = "Question from earlier version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      finance_stranger_permission_age, 
      description = "Question from earlier version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      finance_stranger_permission_age_years, 
      description = "Question from earlier version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      finance_stranger_forged, 
      description = "SR_17. Has a stranger ever forged your signature in order to get some of your money or sell your property?",
      skip_pattern = "If 'Yes', go to SR_17a. All other answers, go to SR_18"
    ) %>%
  
    cb_add_col_attributes( 
      finance_stranger_forged_times, 
      description = "Question from earlier version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      finance_stranger_forged_times_times, 
      description = "Question from earlier version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      finance_stranger_forged_age, 
      description = "Question from earlier version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      finance_stranger_forged_age_years, 
      description = "Question from earlier version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      finance_stranger_tricked, 
      description = "SR_18. Has a stranger ever forced or tricked you into signing a document so that they would be able to get some of your money or possessions?",
      skip_pattern = "If 'Yes', go to SR_18a. All other questions, go to SR_T3"
    ) %>%
  
    cb_add_col_attributes( 
      finance_stranger_tricked_times, 
      description = "Question from earlier version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      finance_stranger_tricked_times_times, 
      description = "Question from earlier version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      finance_stranger_tricked_age, 
      description = "Question from earlier version of the follow-up interview"
    ) %>%
  cb_add_col_attributes( 
      emotional_yelled, 
      description = "SR_19a. Has anyone ever verbally attacked, scolded, or yelled at you so that you felt afraid for your safety, threatened or intimidated?",
      skip_pattern = "If 'Yes', go to SR_19b. All other answers, go to SR_20a"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_yelled_times, 
      description = "SR_19b. About how many times has this happened to you in your lifetime?"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_yelled_times_times, 
      description = "Question from earlier version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_yelled_age, 
      description = "Question from earlier version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_yelled_age_years, 
      description = "Question from earlier version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_embarrassed, 
      description = "SR_20a. Has anyone ever made you feel humiliated or embarrassed by calling you names such as stupid, or telling you that you or your opinion was worthless?",
       skip_pattern = "If 'Yes', go to SR_20b. All other answers, go to SR_21a"
      
    ) %>%
  
    cb_add_col_attributes( 
      emotional_embarrassed_times, 
      description = "SR_20b. About how many times has this happened to you in your lifetime?"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_embarrassed_times_times, 
      description = "Question from earlier version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_embarrassed_age, 
      description = "Question from earlier version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_embarrassed_age_years, 
      description = "Question from earlier version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_harassed, 
      description = "SR_21a. Has anyone ever forcefully or repeatedly asked you to do something so much that you felt harassed or coerced into doing something against your will?",
      skip_pattern = "If 'Yes', go to SR_21b. All other answers, go to SR_22a"
      
    ) %>%
  
    cb_add_col_attributes( 
      emotional_harassed_times, 
      description = "Question from earlier version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_harassed_times_times, 
      description = "Question from earlier version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_harassed_age, 
      description = "Question from earlier version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_harassed_age_years, 
      description = "Question from earlier version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_refused, 
      description = "SR_22a. Has anyone close to you ever completely refused to talk to you or ignored you for days at a time, even when you wanted to talk to them?",
      skip_pattery = "If 'Yes', go to SR_22b. All other answers, go to SP_2"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_refused_times, 
      description = "Question from earlier version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_refused_times_times, 
      description = "Question from earlier version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_refused_age, 
      description = "Question from earlier version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_refused_age_years, 
      description = "Question from earlier version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_incident60, 
      description = "Question from earlier version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_incident_reported, 
      description = "Question used in older version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_incident_person, 
      description = "Question used in older version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_person_live, 
      description = "Question used in older version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_person_alcohol, 
      description = "SR_27. Did that person have a problem with alcohol or drugs when these things happened?"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_person_counseling, 
      description = "SR_28. Has that person ever received inpatient or outpatient counseling for emotional problems?"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_person_police, 
      description = "SR_29. Has that person ever been in trouble with the police?"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_person_job, 
      description = "SR_30. Did that person have a job at the time when these things happened?"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_person_friends, 
      description = "SR_31. How many friends did that person have at the time when these things happened? Would you say…"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_person_help, 
      description = "SR_32. Did that person ever help you out with any day to day things, like shopping, taking medicines, driving you places, getting dressed, and that type of thing?",
      skip_pattern = "IF Q26b = Yes, go to SR_33. All other answers, go to SR_T5"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_person_no_live, 
      description = "SR_33. Would you be able to live on your own if that person no longer lived with you?"
    ) %>%
  
    cb_add_col_attributes( 
      physical_hit, 
      description = "SR_34a. Has anyone ever hit you with their hand or object, slapped you, or threatened you with a weapon?",
      skip_pattern = "If 'Yes', go to SR_34b. All other answers, go to SR_35a"
    ) %>%
  
    cb_add_col_attributes( 
      physical_hit_times, 
      description = " SR_34b. About how many times has this happened to you in your lifetime?"
    ) %>%
  
    cb_add_col_attributes( 
      physical_hit_times_times, 
      description = "Question from an older version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      physical_hit_age, 
      description = "Question from an older version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      physical_hit_age_years, 
      description = "Question from an older version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      physical_restrain, 
      description = "SR_35a. Has anyone ever tried to restrain you by holding you down, tying you up, or locking you in your room or house?",
      skip_pattern = "If 'Yes', go to SR_35b. All other answers,go to SR_36a"
    ) %>%
  
    cb_add_col_attributes( 
      physical_restrain_times, 
      description = "SR_35b. About how many times has this happened to you in your lifetime?"
    ) %>%
  
    cb_add_col_attributes( 
      physical_restrain_times_times, 
      description = "Question from an older version of the follow-up intervie"
    ) %>%
  
    cb_add_col_attributes( 
      physical_restrain_age, 
      description = "Question from an older version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      physical_restrain_age_years, 
      description = "Question from an older version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      physical_hurt, 
      description = "SR_36a. Has anyone ever physically hurt you so that you suffered some degree of injury, including cuts, bruises, or other marks?",
      skip_pattern = "If 'Yes', go to SR_36b. All other answers, go to SP_6"
    ) %>%
  
    cb_add_col_attributes( 
      physical_hurt_times, 
      description = "SR_36b. About how many times has this happened to you in your lifetime?"
    ) %>%
  
    cb_add_col_attributes( 
      physical_hurt_times_times, 
      description = "Question from an older version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      physical_hurt_age, 
      description = "Question from an older version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      physical_hurt_age_years, 
      description = "Question from an older version of the follow_up interview"
    ) %>%
  
    cb_add_col_attributes( 
      physical_incident60, 
      description = "Question from an older version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      physical_incident_reported, 
      description = "Question from an older version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      physical_incident_person, 
      description = "Questio from an older version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      physical_person, 
      description = "Question from an older version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      physical_person_live, 
      description = "Question from an older version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      physical_person_alcohol, 
      description = "SR_42. Did that person have a problem with alcohol or drugs at the time when these things happened?"
    ) %>%
  
    cb_add_col_attributes( 
      physical_person_counseling, 
      description = "SR_43. Has that person ever received inpatient or outpatient counseling for emotional problems?"
    ) %>%
  
    cb_add_col_attributes( 
      physical_person_police, 
      description = "SR_44. Has that person ever been in trouble with the police?"
    ) %>%
  
    cb_add_col_attributes( 
      physical_person_job, 
      description = "SR_45. Did that person have a job at the time when these things happened?"
    ) %>%
  
    cb_add_col_attributes( 
      physical_person_friends, 
      description = "SR_46. How many friends did that person have at the time when these things happened? Would you say…"
    ) %>%
  
    cb_add_col_attributes( 
      physical_person_help, 
      description = "SR_47. Did that person ever help you out with any day to day things, like shopping, taking medicines, driving you places, getting dressed, and that type of thing?"
    ) %>%
  
    cb_add_col_attributes( 
      physical_person_no_live, 
      description = "SR_48. Would you be able to live on your own if that person no longer lived with you?",
      skip_pattern =  "All answers, go to SR_T7(SR_49a)"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_harm, 
      description = "SR_49a. Regardless of how long ago it happened or who made the advances, has anyone ever made you have sex or oral sex by using force or threatening to harm you or someone close to you?",
      skip_pattern = "If 'Yes', go to SR_49b. All other answers, go to SR_50a"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_harm_times, 
      description = "SR_49b. About how many times has this happened to you in your lifetime?"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_harm_times_times, 
      description = "Question from an older version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_harm_age, 
      description = "Question from an older version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_harm_age_years, 
      description = "Question from an older version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_touched, 
      description = "SR_50a. Females- Has anyone ever touched your breasts or pubic area or made you touch his penis by using force or threat of force? Males - Has anyone ever touched your pubic area or made you touch their pubic area by using force or threat of force?",
      skip_pattern = "If 'Yes', go to SR_50b. All other answers, go to SR_51a"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_touched_times, 
      description = "SR_50b. About how many times has this happened to you in your lifetime?"
      
    ) %>%
  
    cb_add_col_attributes( 
      sexual_touched_times_times, 
      description = "Question from an older version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_touched_age, 
      description = "Question from an older version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_touched_age_years, 
      description = "Question from an older version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_forced, 
      description = "SR_51a. Females- Has anyone ever forced you to undress or expose your breasts or pubic area when you didn’t want to? Males- Has anyone ever forced you to undress or expose your pubic area when you didn’t want to?",
      skip_pattern = "If 'Yes', go to SR_51b. All other answers, go to SR_52_a"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_forced_times, 
      description = "SR_51b. About how many times has this happened to you in your lifetime?"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_forced_times_times, 
      description = "Question from an older version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_forced_age, 
      description = "Question from an older version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_forced_age_years, 
      description = "Question from an older version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_picture, 
      description = "SR_52a. Has anyone ever taken a picture of you with your clothes partially or completely taken off when you didn’t want them to?",
      skip_pattern = "If 'Yes', go to SR_52b. All other answers, go to SR_53a"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_picture_times, 
      description = "SR_52b. About how many times has this happened to you in your lifetime?"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_picture_times_times, 
      description = "Question from an older version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_picture_age, 
      description = "Question from an older version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_picture_age_years, 
      description = "Question from an older version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_incident60, 
      description = "Question from an older version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_incident_reported, 
      description = "Question from an older version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_incident_person, 
      description = "Question from an older version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_person, 
      description = "Question from an older version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_person_live, 
      description = "Question from an older version of the follow-up interview"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_person_alcohol, 
      description = "SR_58. Did that person have a problem with alcohol or drugs at the time when these things happened?"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_person_counseling, 
      description = "SR_59. Has that person ever received inpatient or outpatient counseling for emotional problems?"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_person_police, 
      description = "SR_60. Has that person ever been in trouble with the police?"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_person_job, 
      description = "SR_61. Did that person have a job at the time when these things happened?"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_person_friends, 
      description = "SR_62. How many friends did that person have at the time when these things happened? Would you say…"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_person_help, 
      description = "SR_63. Did that person ever help you out with any day to day things, like shopping, taking medicines, driving you places, getting dressed, and that type of thing?",
      skip_pattern = "SP_10. IF SR_57b = Yes, go to SR_64. All other answers, go to Go to FNW_T1"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_person_no_live, 
      description = "SR_64. Would you be able to live on your own if that person no longer lived with you?",
      skip_pattern = "All answers, go to FNW_T1"
    ) %>%
  
    cb_add_col_attributes( 
      fear_afraid, 
      description = "FNW_1. What do you worry most about right now?"
    ) %>%
  
    cb_add_col_attributes( 
      fear_afraid_response, 
      description = ""
    ) %>%
  
    cb_add_col_attributes( 
      fear_future, 
      description = "FNW_2. What is your greatest fear for your future?"
    ) %>%
  
    cb_add_col_attributes( 
      fear_future_response, 
      description = ""
    ) %>%
  
    cb_add_col_attributes( 
      fear_grateful, 
      description = "FNW_3. What are you most grateful for right now?"
    ) %>%
  
    cb_add_col_attributes( 
      fear_grateful_response, 
      description = ""
    ) %>%
  
    cb_add_col_attributes( 
      fear_forward, 
      description = "FNW_4. What are you most looking forward to for your future?"
    ) %>%
  
    cb_add_col_attributes( 
      fear_forward_response, 
      description = ""
    ) %>%
  
    cb_add_col_attributes( 
      fear_important, 
      description = "FNW_5. What is the single most important thing that someone outside of your friends and family could do to benefit your quality of life right now?"
    ) %>%
  
    cb_add_col_attributes( 
      fear_important_response, 
      description = ""
    ) %>%
  
    cb_add_col_attributes( 
      finance_person_permission65, 
      description = "SR_10a. Were you age 65 or older the last time that person spent your money or sold your property without your permission?",
      skip_pattern = "If 'Yes', go to SR_10b. All other answers, go to SR_11"
    ) %>%
  
    cb_add_col_attributes( 
      finance_person_permission_last_time, 
      description = "SR_10b. When was the last time that person spent your money or sold your property without your permission?"
    ) %>%
  
    cb_add_col_attributes( 
      finance_person_forged65, 
      description = "SR_13a. Were you age 65 or older the last time that person forged your signature without your permission in order to sell your property or to get money from your accounts?",
      skip_pattern = "If 'Yes', go to SR_13b. All other answers, go to SR_14"
    ) %>%
  
    cb_add_col_attributes( 
      finance_person_forged_last_time, 
      description = "SR_13b. When was the last time that person forged your signature without your permission in order to sell your property or to get money from your accounts?"
    ) %>%
  
    cb_add_col_attributes( 
      finance_person_tricked65, 
      description = "SR_14a. Were you age 65 or older the last time that person forced or tricked you into signing a document so that they would be able to get some of your money or possessions?",
      skip_pattern = "If 'Yes', go to SR_14b. All other answers, go to SR_15"
    ) %>%
  
    cb_add_col_attributes( 
      finance_person_tricked_last_time, 
      description = "SR_14b. When was the last time that person forced or tricked you into signing a document so that they would be able to get some of your money or possessions?"
    ) %>%
  
    cb_add_col_attributes( 
      finance_person_stolen65, 
      description = "SR_15a. Were you age 65 or older the last time that person stole your money or took your things for themselves, their friends, or to sell?",
      skip_pattern = "If 'Yes', go to SR_15b. All other answers, go to SR_16"
    ) %>%
  
    cb_add_col_attributes( 
      finance_person_stolen_last_time, 
      description = "SR_15b. When was the last time that person stole your money or took your things for themselves, their friends, or to sell?"
    ) %>%
  
    cb_add_col_attributes( 
      finance_stranger_permission65, 
      description = "SR_16a. Were you age 65 or older the last time a stranger spent your money or sold your property without your permission?",
      skip_pattern = "If 'Yes', go to SR_16b. All other answers, go to SR_17"
    ) %>%
  
    cb_add_col_attributes( 
      finance_stranger_permission_last_time, 
      description = "SR_16b. When was the last time a stranger spent your money or sold your property without your permission?"
    ) %>%
  
    cb_add_col_attributes( 
      finance_stranger_forged65, 
      description = "SR_17a. Were you age 65 or older the last time a stranger forged your signature in order to get some of your money or sell your property?",
      skip_pattern = "If 'Yes', go to SR_17b. All other answers, go to SR_18."
    ) %>%
  
    cb_add_col_attributes( 
      finance_stranger_forged_last_time, 
      description = "SR_17b. When was the last time a stranger forged your signature in order to get some of your money or sell your property?"
    ) %>%
  
    cb_add_col_attributes( 
      finance_stranger_tricked65, 
      description = "SR_18a. Were you age 65 or older the last time a stranger forced or tricked you into signing a document so that they would be able to get some of your money or possessions?",
      skip_pattern = "If 'Yes', go to SR_18b. All other answers, go to SR_TR3(Emotional Abuse Variables)."
    ) %>%
  
    cb_add_col_attributes( 
      finance_stranger_tricked_last_time, 
      description = "SR_18b. When was the last time a stranger forced or tricked you into signing a document so that they would be able to get some of your money or possessions?"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_yelled65, 
      description = "SR_19c. Were you age 65 or older the last time (most recent time) this happened?",
      skip_pattern = "If 'No', go to SR_20a. All other answers, go to SR_19d. "
    ) %>%
  
    cb_add_col_attributes( 
      emotional_yelled_last_time, 
      description = "SR_19d. How long ago was the last time (most recent time) this happened? "
    ) %>%
  
    cb_add_col_attributes( 
      emotional_embarrassed65, 
      description = "SR_20c. Were you age 65 or older the last time (most recent time) this happened?", 
      skip_pattern = "If 'No', go to SR_21a. All other answers, go to SR_20d."
    ) %>%
  
    cb_add_col_attributes( 
      emotional_embarrassed_last_time, 
      description = "SR_20d. How long ago was the last time (most recent time) this happened?"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_harassed65, 
      description = "SR_21c. Were you age 65 or older the last time (most recent time) this happened?",
      skip_pattern = "If 'No', go to SR_22a. All other answers, go to SR_21d."
    ) %>%
  
    cb_add_col_attributes( 
      emotional_harassed_last_time, 
      description = "SR_21d. How long ago was the last time (most recent time) this happened? "
    ) %>%
  
    cb_add_col_attributes( 
      emotional_refused65, 
      description = "SR_22c. Were you age 65 or older the last time (most recent time) this happened?",
      skip_pattern = "If 'No', go to SP_2 skip pattern. All other answers, go to SR_23a."
    ) %>%
  
    cb_add_col_attributes( 
      emotional_refused_last_time, 
      description = "SR_22d. How long ago was the last time (most recent time) this happened?",
      skip_pattern = "SP_2. IF SR_19c, SR_20c,SR_21c,  OR SR_22c = YES, go to SR_TR4(SR_24). All other answers, go to SR_TR5(Physical Mistreatment variables)."
    ) %>%
  
    cb_add_col_attributes( 
      emotional_incident_reported_v2, 
      description = "SR_24.  Did you or anyone else report what happened to the police or other authorities?"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_incident_person_v2, 
      description = "SR_25. What was your relationship to the person, or people, who treated you this way? (MULTIPLE RECORD)", 
      skip_pattern = "All answers, go to SP_3. IF SR_25 = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, OR 11}, go to SR_26a. All other answers, go to SR_T5(Physical Mistreatment variables)."
    ) %>%
  
    cb_add_col_attributes( 
      emotional_person_live_then, 
      description = "SR_26a. Did that person (any of those people) live with you when these things happened?"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_person_live_now, 
      description = "SR_26b. Does that person (any of those people) live with you now?"
    ) %>%
  
    cb_add_col_attributes( 
      physical_hit65, 
      description = "SR_34c. Were you age 65 or older the last time (most recent time) this happened?",
      skip_pattern = "If 'No', go to SR_35a. All other answers, go to SR_34d."
    ) %>%
  
    cb_add_col_attributes( 
      physical_hit_last_time, 
      description = "SR_34d. How long ago was the last time (most recent time) this happened?"
    ) %>%
  
    cb_add_col_attributes( 
      physical_restrain65, 
      description = "SR_35c. Were you age 65 or older the last time (most recent time) this happened?",
      skip_pattern = "If 'No', go to SR_36a. All other answers, go to SR_35d."
    ) %>%
  
    cb_add_col_attributes( 
      physical_restrain_last_time, 
      description = "SR_35d. How long ago was the last time (most recent time) this happened?"
    ) %>%
  
    cb_add_col_attributes( 
      physical_hurt65, 
      description = "SR_36c. Were you age 65 or older the last time (most recent time) this happened?",
      skip_pattern = "If 'No', go to SR_36a. All other answers, go to SR_36d."
    ) %>%
  
    cb_add_col_attributes( 
      physical_hurt_last_time, 
      description = "SR_36d. How long ago was the last time (most recent time) this happened?",
      skip_pattern = "All answers, go to SP5. IF SR_34c, SR_35c,  OR SR_36c = YES, go to SR_T6(SR_38). All other answers, go to SR_T7(Sexual Mistreatment variables)"
    ) %>%
  
    cb_add_col_attributes( 
      physical_incident_reported_v2, 
      description = "SR_38. Did you or anyone else report what happened to the police or other authorities?"
    ) %>%
  
    cb_add_col_attributes( 
      physical_incident_person_v2, 
      description = "SR_40. What was your relationship to the person, or people, who treated you this way? (MULTIPLE RECORD)",
      skip_pattern = "All answers, go to SP6. IF SR_40 = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, OR 11}, go to SR_41a. All other answers, go to SR_T7(Sexual Mistreatment variables)."
    ) %>%
  
    cb_add_col_attributes( 
      physical_person_live_then, 
      description = "SR_41a. Did that person (any of those people) live with you when these things happened?"
    ) %>%
  
    cb_add_col_attributes( 
      physical_person_live_now, 
      description = "SR_41b. Does that person (any of those people) live with you now?"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_harm65, 
      description = "SR_49c. Were you age 65 or older the last time (most recent time) this happened?"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_harm_last_time, 
      description = "SR_49d. How long ago was the last time (most recent time) this happened?"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_touched65, 
      description = "SR_50c. Were you age 65 or older the last time (most recent time) this happened?",
      skip_pattern = "If 'No', go to SR_51a. All other answers, go to SR_50d."
    ) %>%
  
    cb_add_col_attributes( 
      sexual_touched_last_time, 
      description = "SR_50d. How long ago was the last time (most recent time) this happened?"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_forced65, 
      description = "SR_51c. Were you age 65 or older the last time (most recent time) this happened?",
      skip_pattern = "If 'No', go to SR_52a. All other answers, go to SR_51d."
    ) %>%
  
    cb_add_col_attributes( 
      sexual_forced_last_time, 
      description = "SR_51d. How long ago was the last time (most recent time) this happened? "
    ) %>%
  
    cb_add_col_attributes( 
      sexual_picture65, 
      description = "SR_52c. Were you age 65 or older the last time (most recent time) this happened?",
      skip_pattern = "If 'No', go to SR_53a. All other answers, go to SR_52d."
    ) %>%
  
    cb_add_col_attributes( 
      sexual_picture_last_time, 
      description = "SR_52d. How long ago was the last time (most recent time) this happened?",
      skip_pattern = "All answers, go to SP8. IF SR_49c, SR_50c, SR_51c,  OR SR_52c = YES, go to SR_T8(SR_54). All other answers, go to FNW_T1(Fears, Wants, Needs variables)."
    ) %>%
  
    cb_add_col_attributes( 
      sexual_incident_reported_v2, 
      description = "SR_54. Did you or anyone else report what happened to the police or other authorities?"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_incident_person_v2, 
      description = "SR_56. What was your relationship to the person, or people, who treated you this way? (MULTIPLE RECORD)",
      skip_pattern = "All answers, go to SP9. IF SR_56 = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, OR 11}, go to SR_57a. All other answers, go to FNW_T1(Fears, Wants, Needs variables)."
    ) %>%
  
    cb_add_col_attributes( 
      sexual_person_live_then, 
      description = "SR_57a. Did that person (any of those people) live with you when these things happened?"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_person_live_now, 
      description = "SR_57b. Does that person (any of those people) live with you now?"
    ) %>%
  
    cb_add_col_attributes( 
      report_private, 
      description = "SR_98 [Please don’t read — just complete on your own]. Was another person (e.g., caregivers, family members, friends, etc.) present when completing THIS SECTION (Self-Report Injury, Violence, Neglect, & Exploitation) of the interview?",
      skip_pattern = "If 'No' or 'Don't know', go to Section 5(APS Investigations). All other answers, go to SR_99."
    ) %>%
  
    cb_add_col_attributes( 
      report_influence, 
      description = "SR_99 [Please don’t read — just complete on your own]. Did you get the impression that the presence of other people (e.g., caregivers, family members, friends, etc.) may have affected the answers given by the patient during THIS SECTION (Self-Report Injury, Violence, Neglect, & Exploitation) of the interview?"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_go_4cat, 
      description = "Recoded neglect_go variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_food_4cat, 
      description = "Recoded neglect_food variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_house_4cat, 
      description = "Recoded neglect_house variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_clean_4cat, 
      description = "Recoded neglect_clean variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_ready_4cat, 
      description = "Recoded neglect_ready variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_bills_4cat, 
      description = "Recoded neglect_bills variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_go_4cat_f, 
      description = "Recoded neglect_go variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_food_4cat_f, 
      description = "Recoded neglect_food variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_house_4cat_f, 
      description = "Recoded neglect_house variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_clean_4cat_f, 
      description = "Recoded neglect_clean variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_ready_4cat_f, 
      description = "Recoded neglect_ready variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_bills_4cat_f, 
      description = "Recoded neglect_bills variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_go_help_5cat, 
      description = "Recoded neglect_go_help variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes,  one person"           = 1,
        "Yes,  more than one person" = 2,
        "No"                         = 3,
        "Don’t know"                 = 7,
        "Refused"                    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_food_help_5cat, 
      description = "Recoded neglect_food_help variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes,  one person"           = 1,
        "Yes,  more than one person" = 2,
        "No"                         = 3,
        "Don’t know"                 = 7,
        "Refused"                    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_house_help_5cat, 
      description = "Recoded neglect_house_help variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes,  one person"           = 1,
        "Yes,  more than one person" = 2,
        "No"                         = 3,
        "Don’t know"                 = 7,
        "Refused"                    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_clean_help_5cat, 
      description = "Recoded neglect_clean_help variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes,  one person"           = 1,
        "Yes,  more than one person" = 2,
        "No"                         = 3,
        "Don’t know"                 = 7,
        "Refused"                    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_ready_help_5cat, 
      description = "Recoded neglect_ready_help variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes,  one person"           = 1,
        "Yes,  more than one person" = 2,
        "No"                         = 3,
        "Don’t know"                 = 7,
        "Refused"                    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_bills_help_5cat, 
      description = "Recoded neglect_bills_help variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes,  one person"           = 1,
        "Yes,  more than one person" = 2,
        "No"                         = 3,
        "Don’t know"                 = 7,
        "Refused"                    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_go_help_5cat_f, 
      description = "Recoded neglect_go_help variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_food_help_5cat_f, 
      description = "Recoded neglect_food_help variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_house_help_5cat_f, 
      description = "Recoded neglect_house_help variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_clean_help_5cat_f, 
      description = "Recoded neglect_clean_help variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_ready_help_5cat_f, 
      description = "Recoded neglect_ready_help variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_bills_help_5cat_f, 
      description = "Recoded neglect_bills_help variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_go_reliable_6cat, 
      description = "Recoded neglect_go_reliable variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Not at all reliable" = 1,
        "Somewhat reliable"   = 2,
        "Very reliable"       = 3,
        "Completely reliable" = 4,
        "Don’t know"          = 7,
        "Refused"             = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_food_reliable_6cat, 
      description = "Recoded neglect_food_reliable variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Not at all reliable" = 1,
        "Somewhat reliable"   = 2,
        "Very reliable"       = 3,
        "Completely reliable" = 4,
        "Don’t know"          = 7,
        "Refused"             = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_house_reliable_6cat, 
      description = "Recoded neglect_house_reliable variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Not at all reliable" = 1,
        "Somewhat reliable"   = 2,
        "Very reliable"       = 3,
        "Completely reliable" = 4,
        "Don’t know"          = 7,
        "Refused"             = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_clean_reliable_6cat, 
      description = "Recoded neglect_clean_reliable variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Not at all reliable" = 1,
        "Somewhat reliable"   = 2,
        "Very reliable"       = 3,
        "Completely reliable" = 4,
        "Don’t know"          = 7,
        "Refused"             = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_ready_reliable_6cat, 
      description = "Recoded neglect_ready_reliable variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Not at all reliable" = 1,
        "Somewhat reliable"   = 2,
        "Very reliable"       = 3,
        "Completely reliable" = 4,
        "Don’t know"          = 7,
        "Refused"             = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_bills_reliable_6cat, 
      description = "Recoded neglect_bills_reliable variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Not at all reliable" = 1,
        "Somewhat reliable"   = 2,
        "Very reliable"       = 3,
        "Completely reliable" = 4,
        "Don’t know"          = 7,
        "Refused"             = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_go_reliable_6cat_f, 
      description = "Recoded neglect_go_reliable variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_food_reliable_6cat_f, 
      description = "Recoded neglect_food_reliable variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_house_reliable_6cat_f, 
      description = "Recoded neglect_house_reliable variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_clean_reliable_6cat_f, 
      description = "Recoded neglect_clean_reliable variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_ready_reliable_6cat_f, 
      description = "Recoded neglect_ready_reliable variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_bills_reliable_6cat_f, 
      description = "Recoded neglect_bills_reliable variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_spouse, 
      description = "Created dummy variable for neglect_person variable answer 'A spouse or partner' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_ex_partner, 
      description = "Created dummy variable for neglect_person variable answer 'An ex spouse or partner' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_parent, 
      description = "Created dummy variable for neglect_person variable answer 'A parent or step-parent' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_sibling, 
      description = "Created dummy variable for neglect_person variable answer 'A brother or sister' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_child, 
      description = "Created dummy variable for neglect_person variable answer 'A son or daughter' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_other_relative, 
      description = "Created dummy variable for neglect_person variable answer 'Another relative' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_coworker, 
      description = "Created dummy variable for neglect_person variable answer 'A coworker' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_neighbor, 
      description = "Created dummy variable for neglect_person variable answer 'A neighbor' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_friend, 
      description = "Created dummy variable for neglect_person variable answer 'A friend' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_non_relative, 
      description = "Created dummy variable for neglect_person variable answer 'Some other non-relative' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_dont_know, 
      description = "Created dummy variable for neglect_person variable answer 'Don't know' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_refused, 
      description = "Created dummy variable for neglect_person variable answer 'Refused' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      finance_help_4cat, 
      description = "Recoded finance_help variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      finance_person_permission_4cat, 
      description = "Recoded finance_person_permission variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      finance_person_decisions_4cat, 
      description = "Recoded finance_person_decisions variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      finance_copies_4cat, 
      description = "Recoded finance_copies variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      finance_person_forged_4cat, 
      description = "Recoded finance_person_forged variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      finance_person_tricked_4cat, 
      description = "Recoded finance_person_tricked variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      finance_person_stolen_4cat, 
      description = "Recoded finance_person_stolen variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      finance_stranger_permission_4cat, 
      description = "Recoded finance_stranger_permission variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      finance_stranger_forged_4cat, 
      description = "Recoded finance_stranger_forged variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      finance_stranger_tricked_4cat, 
      description = "Recoded finance_stranger_tricked variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      finance_person_permission65_4cat, 
      description = "Recoded finance_person_permission65 variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      finance_person_forged65_4cat, 
      description = "Recoded finance_person_forged65 variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      finance_person_tricked65_4cat, 
      description = "Recoded finance_person_tricked65 variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      finance_person_stolen65_4cat, 
      description = "Recoded finance_person_stolen65 variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      finance_stranger_permission65_4cat, 
      description = "Recoded finance_stranger_permission65 variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      finance_stranger_forged65_4cat, 
      description = "Recoded finance_stranger_forged65 variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      finance_stranger_tricked65_4cat, 
      description = "Recoded finance_stranger_tricked65 variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      finance_help_4cat_f, 
      description = "Recoded finance_help variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      finance_person_permission_4cat_f, 
      description = "Recoded finance_person_permission variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      finance_person_decisions_4cat_f, 
      description = "Recoded finance_person_decisions variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      finance_copies_4cat_f, 
      description = "Recoded finance_copies variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      finance_person_forged_4cat_f, 
      description = "Recoded finance_person_forged variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      finance_person_tricked_4cat_f, 
      description = "Recoded finance_person_tricked variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      finance_person_stolen_4cat_f, 
      description = "Recoded finance_person_stolen variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      finance_stranger_permission_4cat_f, 
      description = "Recoded finance_stranger_permission variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      finance_stranger_forged_4cat_f, 
      description = "Recoded finance_stranger_forged variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      finance_stranger_tricked_4cat_f, 
      description = "Recoded finance_stranger_tricked variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      finance_person_permission65_4cat_f, 
      description = "Recoded finance_person_permission65 variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      finance_person_forged65_4cat_f, 
      description = "Recoded finance_person_forged65 variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      finance_person_tricked65_4cat_f, 
      description = "Recoded finance_person_tricked65 variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      finance_person_stolen65_4cat_f, 
      description = "Recoded finance_person_stolen65 variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      finance_stranger_permission65_4cat_f, 
      description = "Recoded finance_stranger_permission65 variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      finance_stranger_forged65_4cat_f, 
      description = "Recoded finance_stranger_forged65 variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      finance_stranger_tricked65_4cat_f, 
      description = "Recoded finance_stranger_tricked65 variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      finance_spouse, 
      description = "Created dummy variable for finance_person variable answer 'A spouse or partner' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      finance_ex_partner, 
      description = "Created dummy variable for finance_person variable answer 'An ex spouse or partner' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      finance_parent, 
      description = "Created dummy variable for finance_person variable answer 'A parent or step-parent' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      finance_sibling, 
      description = "Created dummy variable for finance_person variable answer 'A brother or sister' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      finance_child, 
      description = "Created dummy variable for finance_person variable answer 'A son or daughter' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      finance_other_relative, 
      description = "Created dummy variable for finance_person variable answer 'Another relative' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      finance_coworker, 
      description = "Created dummy variable for finance_person variable answer 'A coworker' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      finance_neighbor, 
      description = "Created dummy variable for finance_person variable answer 'A neighbor' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      finance_friend, 
      description = "Created dummy variable for finance_person variable answer 'A friend' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      finance_non_relative, 
      description = "Created dummy variable for finance_person variable answer 'Some other non-relative' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      finance_dont_know, 
      description = "Created dummy variable for finance_person variable answer 'Don't know' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      finance_refused, 
      description = "Created dummy variable for finance_person variable answer 'Refused' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      finance_person_permission_last_time_8cat, 
      description = "Recoded finance_person_permission_last_time variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Less than 1 month ago"                       = 1,
        "Between 1 month and less than 3 months ago"  = 2,
        "Between 3 months and less than 6 months ago" = 3,
        "Between 6 months and less than 1 year ago"   = 4,
        "Between 1 year and less than 3 years ago"    = 5,
        "3 or more years ago"                         = 6,
        "Don’t know"                                  = 7,
        "Refused"                                     = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      finance_person_forged_last_time_8cat, 
      description = "Recoded finance_person_forged_last_time variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Less than 1 month ago"                       = 1,
        "Between 1 month and less than 3 months ago"  = 2,
        "Between 3 months and less than 6 months ago" = 3,
        "Between 6 months and less than 1 year ago"   = 4,
        "Between 1 year and less than 3 years ago"    = 5,
        "3 or more years ago"                         = 6,
        "Don’t know"                                  = 7,
        "Refused"                                     = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      finance_person_tricked_last_time_8cat, 
      description = "Recoded finance_tricked_permission_last_time variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Less than 1 month ago"                       = 1,
        "Between 1 month and less than 3 months ago"  = 2,
        "Between 3 months and less than 6 months ago" = 3,
        "Between 6 months and less than 1 year ago"   = 4,
        "Between 1 year and less than 3 years ago"    = 5,
        "3 or more years ago"                         = 6,
        "Don’t know"                                  = 7,
        "Refused"                                     = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      finance_person_stolen_last_time_8cat, 
      description = "Recoded finance_person_stolen_last_time variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Less than 1 month ago"                       = 1,
        "Between 1 month and less than 3 months ago"  = 2,
        "Between 3 months and less than 6 months ago" = 3,
        "Between 6 months and less than 1 year ago"   = 4,
        "Between 1 year and less than 3 years ago"    = 5,
        "3 or more years ago"                         = 6,
        "Don’t know"                                  = 7,
        "Refused"                                     = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      finance_stranger_permission_last_time_8cat, 
      description = "Recoded finance_stranger_permission_last_time variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Less than 1 month ago"                       = 1,
        "Between 1 month and less than 3 months ago"  = 2,
        "Between 3 months and less than 6 months ago" = 3,
        "Between 6 months and less than 1 year ago"   = 4,
        "Between 1 year and less than 3 years ago"    = 5,
        "3 or more years ago"                         = 6,
        "Don’t know"                                  = 7,
        "Refused"                                     = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      finance_stranger_forged_last_time_8cat, 
      description = "Recoded finance_stranger_forged_last_time variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Less than 1 month ago"                       = 1,
        "Between 1 month and less than 3 months ago"  = 2,
        "Between 3 months and less than 6 months ago" = 3,
        "Between 6 months and less than 1 year ago"   = 4,
        "Between 1 year and less than 3 years ago"    = 5,
        "3 or more years ago"                         = 6,
        "Don’t know"                                  = 7,
        "Refused"                                     = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      finance_stranger_tricked_last_time_8cat, 
      description = "Recoded finance_stranger_tricked_last_time variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Less than 1 month ago"                       = 1,
        "Between 1 month and less than 3 months ago"  = 2,
        "Between 3 months and less than 6 months ago" = 3,
        "Between 6 months and less than 1 year ago"   = 4,
        "Between 1 year and less than 3 years ago"    = 5,
        "3 or more years ago"                         = 6,
        "Don’t know"                                  = 7,
        "Refused"                                     = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      finance_person_permission_last_time_8cat_f, 
      description = "Recoded finance_permission_last_time variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      finance_person_forged_last_time_8cat_f, 
      description = "Recoded finance_forged_last_time variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      finance_person_tricked_last_time_8cat_f, 
      description = "Recoded finance_tricked_last_time variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      finance_person_stolen_last_time_8cat_f, 
      description = "Recoded finance_stolen_last_time variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      finance_stranger_permission_last_time_8cat_f, 
      description = "Recoded finance_stranger_permission_last_time variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      finance_stranger_forged_last_time_8cat_f, 
      description = "Recoded finance_stranger_forged_last_time variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      finance_stranger_tricked_last_time_8cat_f, 
      description = "Recoded finance_stranger_tricked_last_time variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_yelled_4cat, 
      description = "Recoded emotional_yelled variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
        ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_embarrassed_4cat, 
      description = "Recoded emotional_embarrassed variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
        ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_harassed_4cat, 
      description = "Recoded emotional_harrassed variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
        ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_refused_4cat, 
      description = "Recoded emotional_refused variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
        ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_incident60_4cat, 
      description = "Recoded emotional_incident60 variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
        ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_incident_reported_4cat, 
      description = "Recoded emotional_incident_reported variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
        ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_person_live_4cat, 
      description = "Recoded emotional_person_live variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
        ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_person_alcohol_4cat, 
      description = "Recoded emotional_person_alcohol variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
        ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_person_counseling_4cat, 
      description = "Recoded emotional_person_counseling variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
        ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_person_police_4cat, 
      description = "Recoded emotional_person_police variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
        ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_person_job_4cat, 
      description = "Recoded emotional_person_job variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
        ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_person_help_4cat, 
      description = "Recoded emotional_person_help variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
        ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_person_no_live_4cat, 
      description = "Recoded emotional_person_no_live variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
        ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_yelled65_4cat, 
      description = "Recoded emotional_yelled65 variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
        ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_embarrassed65_4cat, 
      description = "Recoded emotional_embarrassed65 variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
        ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_harassed65_4cat, 
      description = "Recoded emotional_harassed65 variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
        ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_refused65_4cat, 
      description = "Recoded emotional_refused65 variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
        ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_incident_reported_v2_4cat, 
      description = "Recoded emotional_incident_reported_v2 variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
        ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_person_live_then_4cat, 
      description = "Recoded emotional_person_live_then variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
        ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_person_live_now_4cat, 
      description = "Recoded emotional_person_live_now variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
        ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_yelled_4cat_f, 
      description = "Recoded emotional_yelled variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
        ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_embarrassed_4cat_f, 
      description = "Recoded emotional_embarrassed variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
        ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_harassed_4cat_f, 
      description = "Recoded emotional_harassed variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
        ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_refused_4cat_f, 
      description = "Recoded emotional_refused variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_incident60_4cat_f, 
      description = "Recoded emotional_incident60 variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_incident_reported_4cat_f, 
      description = "Recoded emotional_incident_reported variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_person_live_4cat_f, 
      description = "Recoded emotional_person_live variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_person_alcohol_4cat_f, 
      description = "Recoded emotional_person_alcohol variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_person_counseling_4cat_f, 
      description = "Recoded emotional_person_counseling variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_person_police_4cat_f, 
      description = "Recoded emotional_person_police variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_person_job_4cat_f, 
      description = "Recoded emotional_person_job variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_person_help_4cat_f, 
      description = "Recoded emotional_person_help variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_person_no_live_4cat_f, 
      description = "Recoded emotional_person_no_live variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_yelled65_4cat_f, 
      description = "Recoded emotional_yelled65 variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_embarrassed65_4cat_f, 
      description = "Recoded emotional_embarrassed65 variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_harassed65_4cat_f, 
      description = "Recoded emotional_harassed65 variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_refused65_4cat_f, 
      description = "Recoded emotional_refused65 variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_incident_reported_v2_4cat_f, 
      description = "Recoded emotional_incident_reported_v2 variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_person_live_then_4cat_f, 
      description = "Recoded emotional_person_live_then variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_person_live_now_4cat_f, 
      description = "Recoded emotional_person_live_now variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_stranger, 
      description = "Created dummy variable for emotional_person variable answer 'A stranger' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_spouse, 
      description = "Created dummy variable for emotional_person variable answer 'A spouse or partner' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_ex_partner, 
      description = "Created dummy variable for emotional_person variable answer 'An ex spouse or partner' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_parent, 
      description = "Created dummy variable for emotional_person variable answer 'A parent or step-parent' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_sibling, 
      description = "Created dummy variable for emotional_person variable answer 'A brother or sister' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_child, 
      description = "Created dummy variable for emotional_person variable answer 'A son or daughter' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_other_relative, 
      description = "Created dummy variable for emotional_person variable answer 'Another relative' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_coworker, 
      description = "Created dummy variable for emotional_person variable answer 'A coworker' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_neighbor, 
      description = "Created dummy variable for emotional_person variable answer 'A neighbor' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_friend, 
      description = "Created dummy variable for emotional_person variable answer 'A friend' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_non_relative, 
      description = "Created dummy variable for emotional_person variable answer 'Some other non-relative' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_dont_know, 
      description = "Created dummy variable for emotional_person variable answer 'Don't know' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_yelled_last_time_8cat, 
      description = "Recoded emotional_yelled_last_time variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Less than 1 month ago"                       = 1,
        "Between 1 month and less than 3 months ago"  = 2,
        "Between 3 months and less than 6 months ago" = 3,
        "Between 6 months and less than 1 year ago"   = 4,
        "Between 1 year and less than 3 years ago"    = 5,
        "3 or more years ago"                         = 6,
        "Don’t know"                                  = 7,
        "Refused"                                     = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_embarrassed_last_time_8cat, 
      description = "Recoded emotional_embarrassed_last_time variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Less than 1 month ago"                       = 1,
        "Between 1 month and less than 3 months ago"  = 2,
        "Between 3 months and less than 6 months ago" = 3,
        "Between 6 months and less than 1 year ago"   = 4,
        "Between 1 year and less than 3 years ago"    = 5,
        "3 or more years ago"                         = 6,
        "Don’t know"                                  = 7,
        "Refused"                                     = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_harassed_last_time_8cat, 
      description = "Recoded emotional_harassed_last_time variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Less than 1 month ago"                       = 1,
        "Between 1 month and less than 3 months ago"  = 2,
        "Between 3 months and less than 6 months ago" = 3,
        "Between 6 months and less than 1 year ago"   = 4,
        "Between 1 year and less than 3 years ago"    = 5,
        "3 or more years ago"                         = 6,
        "Don’t know"                                  = 7,
        "Refused"                                     = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_refused_last_time_8cat, 
      description = "Recoded emotional_refused_last_time variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Less than 1 month ago"                       = 1,
        "Between 1 month and less than 3 months ago"  = 2,
        "Between 3 months and less than 6 months ago" = 3,
        "Between 6 months and less than 1 year ago"   = 4,
        "Between 1 year and less than 3 years ago"    = 5,
        "3 or more years ago"                         = 6,
        "Don’t know"                                  = 7,
        "Refused"                                     = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_yelled_last_time_8cat_f, 
      description = "Recoded emotional_yelled_last_time variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_embarrassed_last_time_8cat_f, 
      description = "Recoded emotional_embarrassed_last_time variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_harassed_last_time_8cat_f, 
      description = "Recoded emotional_harassed_last_time variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_refused_last_time_8cat_f, 
      description = "Recoded emotional_refused_last_time variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_yelled_times_7cat, 
      description = "Recoded emotional_yelled_times variable to match levels in follow-up interview protocol",
      value_labels = c(
        "1 or 2 times"                      = 1,
        "Between 3 and less than 5 times"   = 2,
        "Between 5 and less than 10 times"  = 3,
        "Between 10 and less than 20 times" = 4,
        "20 or more times"                  = 5,
        "Don’t know"                        = 7,
        "Refused"                           = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_embarrassed_times_7cat, 
      description = "Recoded emotional_embarrassed_times variable to match levels in follow-up interview protocol",
      value_labels = c(
        "1 or 2 times"                      = 1,
        "Between 3 and less than 5 times"   = 2,
        "Between 5 and less than 10 times"  = 3,
        "Between 10 and less than 20 times" = 4,
        "20 or more times"                  = 5,
        "Don’t know"                        = 7,
        "Refused"                           = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_harassed_times_7cat, 
      description = "Recoded emotional_harassed_times variable to match levels in follow-up interview protocol",
      value_labels = c(
        "1 or 2 times"                      = 1,
        "Between 3 and less than 5 times"   = 2,
        "Between 5 and less than 10 times"  = 3,
        "Between 10 and less than 20 times" = 4,
        "20 or more times"                  = 5,
        "Don’t know"                        = 7,
        "Refused"                           = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_refused_times_7cat, 
      description = "Recoded emotional_refused_times variable to match levels in follow-up interview protocol",
      value_labels = c(
        "1 or 2 times"                      = 1,
        "Between 3 and less than 5 times"   = 2,
        "Between 5 and less than 10 times"  = 3,
        "Between 10 and less than 20 times" = 4,
        "20 or more times"                  = 5,
        "Don’t know"                        = 7,
        "Refused"                           = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_yelled_times_7cat_f, 
      description = "Recoded emotional_yelled_times variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_embarrassed_times_7cat_f, 
      description = "Recoded emotional_embarrassed_times variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_harassed_times_7cat_f, 
      description = "Recoded emotional_harassed_times variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_refused_times_7cat_f, 
      description = "Recoded emotional_refused_times variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_person_friends_6cat, 
      description = "Recoded emotional_person_friends variable to match levels in follow-up interview protocol",
      value_labels = c(
        "None" = 0,
        "Very few (1 -3)" = 1,
        "Some (4 -6)" = 2,
        "A lot (7+)" = 3,
        "Don’t know" = 7,
        "Refused" = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_person_friends_6cat_f, 
      description = "Recoded emotional_person_friends variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_stranger_v2, 
      description = "Created dummy variable for emotional_incident_person_v2 variable answer 'A stranger' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_spouse_v2, 
      description = "Created dummy variable for emotional_incident_person_v2 variable answer 'A spouse or partner' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_ex_partner_v2, 
      description = "Created dummy variable for emotional_incident_person_v2 variable answer 'An ex spouse or partner' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_parent_v2, 
      description = "Created dummy variable for emotional_incident_person_v2 variable answer 'A parent or step-parent' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_sibling_v2, 
      description = "Created dummy variable for emotional_incident_person_v2 variable answer 'A brother or sisterr' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_child_v2, 
      ddescription = "Created dummy variable for emotional_incident_person_v2 variable answer 'A son or daughter' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_other_relative_v2, 
      description = "Created dummy variable for emotional_incident_person_v2 variable answer 'Another relative' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_coworker_v2, 
      description = "Created dummy variable for emotional_incident_person_v2 variable answer 'A coworker' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_neighbor_v2, 
      description = "Created dummy variable for emotional_incident_person_v2 variable answer 'A neighbor' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_friend_v2, 
     description = "Created dummy variable for emotional_incident_person_v2 variable answer 'A friend' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_non_relative_v2, 
      description = "Created dummy variable for emotional_incident_person_v2 variable answer 'Some other non-relativer' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_dont_know_v2, 
      description = "Created dummy variable for emotional_incident_person_v2 variable answer 'Don't know' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      emotional_refused_v2, 
      description = "Created dummy variable for emotional_incident_person_v2 variable answer 'Refused' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      physical_hit_4cat, 
      description = "Recoded physical_hit variable to match levels in the follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      physical_restrain_4cat, 
      description = "Recoded physical_restrain variable to match levels in the follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      physical_hurt_4cat, 
      description = "Recoded physical_hurt variable to match levels in the follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      physical_incident60_4cat, 
      description = "Recoded physical_incident60 variable to match levels in the follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      physical_incident_reported_4cat, 
      description = "Recoded physical_incident_reported variable to match levels in the follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      physical_incident_person_4cat, 
      description = "Recoded physical_incident_person variable to match levels in the follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      physical_person_4cat, 
      description = "Recoded physical_person variable to match levels in the follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      physical_person_live_4cat, 
      description = "Recoded physical_person_live variable to match levels in the follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      physical_person_alcohol_4cat, 
      description = "Recoded physical_person_alcohol variable to match levels in the follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      physical_person_counseling_4cat, 
      description = "Recoded physical_person_counseling variable to match levels in the follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      physical_person_police_4cat, 
      description = "Recoded physical_person_police variable to match levels in the follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      physical_person_job_4cat, 
      description = "Recoded physical_person_job variable to match levels in the follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      physical_person_help_4cat, 
      description = "Recoded physical_person_help variable to match levels in the follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      physical_person_no_live_4cat, 
      description = "Recoded physical_person_no_live variable to match levels in the follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      physical_hit65_4cat, 
      description = "Recoded physical_hit65 variable to match levels in the follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      physical_restrain65_4cat, 
      description = "Recoded physical_restrain65 variable to match levels in the follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      physical_hurt65_4cat, 
      description = "Recoded physical_hurt65 variable to match levels in the follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      physical_incident_reported_v2_4cat, 
      description = "Recoded physical_incident_reported_v2 variable to match levels in the follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      physical_person_live_then_4cat, 
      description = "Recoded physical_person_live_then variable to match levels in the follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      physical_person_live_now_4cat, 
      description = "Recoded physical_live_now variable to match levels in the follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      physical_hit_4cat_f, 
      description = "Recoded physical_hit variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      physical_restrain_4cat_f, 
      description = "Recoded physical_restrain variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      physical_hurt_4cat_f, 
      description = "Recoded physical_hurt variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      physical_incident60_4cat_f, 
      description = "Recoded physical_incident60 variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      physical_incident_reported_4cat_f, 
      description = "Recoded physical_incident_reported variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      physical_incident_person_4cat_f, 
      description = "Recoded physical_incident_person variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      physical_person_4cat_f, 
      description = "Recoded physical_person variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      physical_person_live_4cat_f, 
      description = "Recoded physical_person_live variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      physical_person_alcohol_4cat_f, 
      description = "Recoded physical_person_alcohol variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      physical_person_counseling_4cat_f, 
      description = "Recoded physical_person_counseling variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      physical_person_police_4cat_f, 
      description = "Recoded physical_person_police variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      physical_person_job_4cat_f, 
      description = "Recoded physical_person_job variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      physical_person_help_4cat_f, 
      description = "Recoded physical_person_help variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      physical_person_no_live_4cat_f, 
      description = "Recoded physical_person_no_live variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      physical_hit65_4cat_f, 
      description = "Recoded physical_hit65 variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      physical_restrain65_4cat_f, 
      description = "Recoded physical_restrain65 variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      physical_hurt65_4cat_f, 
      description = "Recoded physical_hurt65 variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      physical_incident_reported_v2_4cat_f, 
      description = "Recoded physical_incident_reported_v2 variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      physical_person_live_then_4cat_f, 
      description = "Recoded physical_person_live_then variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      physical_person_live_now_4cat_f, 
      description = "Recoded physical_person_live_now variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      physical_hit_last_time_8cat, 
      description = "Recoded physical_hit_last_time variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Less than 1 month ago"                       = 1,
        "Between 1 month and less than 3 months ago"  = 2,
        "Between 3 months and less than 6 months ago" = 3,
        "Between 6 months and less than 1 year ago"   = 4,
        "Between 1 year and less than 3 years ago"    = 5,
        "3 or more years ago"                         = 6,
        "Don’t know"                                  = 7,
        "Refused"                                     = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      physical_restrain_last_time_8cat, 
      description = "Recoded physical_restrain_last_time variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Less than 1 month ago"                       = 1,
        "Between 1 month and less than 3 months ago"  = 2,
        "Between 3 months and less than 6 months ago" = 3,
        "Between 6 months and less than 1 year ago"   = 4,
        "Between 1 year and less than 3 years ago"    = 5,
        "3 or more years ago"                         = 6,
        "Don’t know"                                  = 7,
        "Refused"                                     = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      physical_hurt_last_time_8cat, 
      description = "Recoded physical_hurt_last_time variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Less than 1 month ago"                       = 1,
        "Between 1 month and less than 3 months ago"  = 2,
        "Between 3 months and less than 6 months ago" = 3,
        "Between 6 months and less than 1 year ago"   = 4,
        "Between 1 year and less than 3 years ago"    = 5,
        "3 or more years ago"                         = 6,
        "Don’t know"                                  = 7,
        "Refused"                                     = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      physical_hit_last_time_8cat_f, 
      description = "Recoded physical_hit_last_time variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      physical_restrain_last_time_8cat_f, 
      description = "Recoded physical_restrain_last_time variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      physical_hurt_last_time_8cat_f, 
      description = "Recoded physical_hurt_last_time variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      physical_hit_times_7cat, 
      description = "Recoded physical_hit_times variable to match levels in follow-up interview protocol",
      value_labels = c(
        "1 or 2 times"                      = 1,
        "Between 3 and less than 5 times"   = 2,
        "Between 5 and less than 10 times"  = 3,
        "Between 10 and less than 20 times" = 4,
        "20 or more times"                  = 5,
        "Don’t know"                        = 7,
        "Refused"                           = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      physical_restrain_times_7cat, 
      description = "Recoded physical_restrain_times variable to match levels in follow-up interview protocol",
      value_labels = c(
        "1 or 2 times"                      = 1,
        "Between 3 and less than 5 times"   = 2,
        "Between 5 and less than 10 times"  = 3,
        "Between 10 and less than 20 times" = 4,
        "20 or more times"                  = 5,
        "Don’t know"                        = 7,
        "Refused"                           = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      physical_hurt_times_7cat, 
      description = "Recoded physical_hurt_times variable to match levels in follow-up interview protocol",
      value_labels = c(
        "1 or 2 times"                      = 1,
        "Between 3 and less than 5 times"   = 2,
        "Between 5 and less than 10 times"  = 3,
        "Between 10 and less than 20 times" = 4,
        "20 or more times"                  = 5,
        "Don’t know"                        = 7,
        "Refused"                           = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      physical_hit_times_7cat_f, 
      description = "Recoded physical_hit_times variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      physical_restrain_times_7cat_f, 
      description = "Recoded physical_restrain_times variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      physical_hurt_times_7cat_f, 
      description = "Recoded physical_hurt_times variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      physical_person_friends_6cat, 
      description = "Recoded physical_person_friends variable to match levels in follow-up interview protocol",
      value_labels = c(
        "None"            = 0,
        "Very few (1 -3)" = 1,
        "Some (4 -6)"     = 2,
        "A lot (7+)"      = 3,
        "Don’t know"      = 7,
        "Refused"         = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      physical_person_friends_6cat_f, 
      description = "Recoded physical_person_friends variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      physical_stranger_v2, 
      description = "Created dummy variable for physical_incident_person_v2 variable answer 'A stranger' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      physical_spouse_v2, 
      description = "Created dummy variable for physical_incident_person_v2 variable answer 'A spouse or partner' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      physical_ex_partner_v2, 
      description = "Created dummy variable for physical_incident_person_v2 variable answer 'An ex spouse or partner' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      physical_parent_v2, 
      description = "Created dummy variable for physical_incident_person_v2 variable answer 'A mother or father' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      physical_sibling_v2, 
      description = "Created dummy variable for physical_incident_person_v2 variable answer 'A brother or sister' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      physical_child_v2, 
      description = "Created dummy variable for physical_incident_person_v2 variable answer 'A son or daughter' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      physical_other_relative_v2, 
      description = "Created dummy variable for physical_incident_person_v2 variable answer 'Another relative' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      physical_coworker_v2, 
      description = "Created dummy variable for physical_incident_person_v2 variable answer 'A coworker' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      physical_neighbor_v2, 
      description = "Created dummy variable for physical_incident_person_v2 variable answer 'A neighbor' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      physical_friend_v2, 
      description = "Created dummy variable for physical_incident_person_v2 variable answer 'A friend' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      physical_non_relative_v2, 
      description = "Created dummy variable for physical_incident_person_v2 variable answer 'Some other non-relative' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      physical_dont_know_v2, 
      description = "Created dummy variable for physical_incident_person_v2 variable answer 'Don't know' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      physical_refused_v2, 
      description = "Created dummy variable for physical_incident_person_v2 variable answer 'Refused' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      physical_stranger, 
      description = "Created dummy variable for physical_incident_person variable answer 'A stranger' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      physical_spouse, 
      description = "Created dummy variable for physical_incident_person variable answer 'A spouse or partner' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      physical_ex_partner, 
      description = "Created dummy variable for physical_incident_person variable answer 'An ex spouse or partner' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      physical_parent, 
      description = "Created dummy variable for physical_incident_person variable answer 'A parent or step-parent' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      physical_sibling, 
      description = "Created dummy variable for physical_incident_person variable answer 'A brother or sister' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      physical_child, 
      description = "Created dummy variable for physical_incident_person variable answer 'A son or daughter' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      physical_other_relative, 
      description = "Created dummy variable for physical_incident_person variable answer 'Another relative' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      physical_coworker, 
      description = "Created dummy variable for physical_incident_person variable answer 'A coworker' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      physical_neighbor, 
      description = "Created dummy variable for physical_incident_person variable answer 'A neighbor' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      physical_friend, 
      description = "Created dummy variable for physical_incident_person variable answer 'A friend' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      physical_non_relative, 
      description = "Created dummy variable for physical_incident_person variable answer 'Some other non-relative' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      physical_dont_know, 
      description = "Created dummy variable for physical_incident_person variable answer 'Don't know' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      physical_refused, 
      description = "Created dummy variable for physical_incident_person variable answer 'Refused' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_harm_4cat, 
      description = "Recoded sexual_harm variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9 
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_touched_4cat, 
      description = "Recoded sexual_touched variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9 
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_forced_4cat, 
      description = "Recoded sexual_forced variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9 
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_picture_4cat, 
      description = "Recoded sexual_picture variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9 
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_incident60_4cat, 
      description = "Recoded sexual_incident60 variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9 
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_incident_reported_4cat, 
      description = "Recoded sexual_incident_reported variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9 
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_incident_person_4cat, 
      description = "Recoded sexual_incident_person variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9 
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_person_4cat, 
      description = "Recoded sexual_person variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9 
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_person_live_4cat, 
      description = "Recoded sexual_person_live variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9 
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_person_alcohol_4cat, 
      description = "Recoded sexual_person_alcohol variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9 
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_person_counseling_4cat, 
      description = "Recoded sexual_person_counseling variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9 
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_person_police_4cat, 
      description = "Recoded sexual_person_police variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9 
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_person_job_4cat, 
      description = "Recoded sexual_person_job variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9 
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_person_help_4cat, 
      description = "Recoded sexual_person_help variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9 
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_person_no_live_4cat, 
      description = "Recoded sexual_person_no_live variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9 
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_harm65_4cat, 
      description = "Recoded sexual_harm65 variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9 
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_touched65_4cat, 
      description = "Recoded sexual_touched65 variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9 
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_forced65_4cat, 
      description = "Recoded sexual_forced65 variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9 
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_picture65_4cat, 
      description = "Recoded sexual_pictures65 variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9 
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_incident_reported_v2_4cat, 
      description = "Recoded sexual_incident_reported_v2 variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9 
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_person_live_then_4cat, 
      description = "Recoded sexual_person_live_then variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9 
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_person_live_now_4cat, 
      description = "Recoded sexual_person_live_now variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9 
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_harm_4cat_f, 
      description = "Recoded sexual_harm variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_touched_4cat_f, 
      description = "Recoded sexual_touched variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_forced_4cat_f, 
      description = "Recoded sexual_forced variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_picture_4cat_f, 
      description = "Recoded sexual_picture variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_incident60_4cat_f, 
      description = "Recoded sexual_incident60 variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_incident_reported_4cat_f, 
      description = "Recoded sexual_incident_reported variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_incident_person_4cat_f, 
      description = "Recoded sexual_incident_person variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_person_4cat_f, 
      description = "Recoded sexual_person variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_person_live_4cat_f, 
      description = "Recoded sexual_person_live variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_person_alcohol_4cat_f, 
      description = "Recoded sexual_person_alcohol variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_person_counseling_4cat_f, 
      description = "Recoded sexual_person_counseling variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_person_police_4cat_f, 
      description = "Recoded sexual_person_police variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_person_job_4cat_f, 
      description = "Recoded sexual_person_job variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_person_help_4cat_f, 
      description = "Recoded sexual_person_help variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_person_no_live_4cat_f, 
      description = "Recoded sexual_person_no_live variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_harm65_4cat_f, 
      description = "Recoded sexual_harm65 variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_touched65_4cat_f, 
      description = "Recoded sexual_touched65 variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_forced65_4cat_f, 
      description = "Recoded sexual_forced65 variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_picture65_4cat_f, 
      description = "Recoded sexual_picture65 variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_incident_reported_v2_4cat_f, 
      description = "Recoded sexual_incident_reported_v2 variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_person_live_then_4cat_f, 
      description = "Recoded sexual_person_live_then variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_person_live_now_4cat_f, 
      description = "Recoded sexual_person_live_now variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_harm_last_time_8cat, 
      description = "Recoded sexual_harm_last_time variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Less than 1 month ago"                       = 1,
        "Between 1 month and less than 3 months ago"  = 2,
        "Between 3 months and less than 6 months ago" = 3,
        "Between 6 months and less than 1 year ago"   = 4,
        "Between 1 year and less than 3 years ago"    = 5,
        "3 or more years ago"                         = 6,
        "Don’t know"                                  = 7,
        "Refused"                                     = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_touched_last_time_8cat, 
      description = "Recoded sexual_touched_last_time variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Less than 1 month ago"                       = 1,
        "Between 1 month and less than 3 months ago"  = 2,
        "Between 3 months and less than 6 months ago" = 3,
        "Between 6 months and less than 1 year ago"   = 4,
        "Between 1 year and less than 3 years ago"    = 5,
        "3 or more years ago"                         = 6,
        "Don’t know"                                  = 7,
        "Refused"                                     = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_forced_last_time_8cat, 
      description = "Recoded sexual_forced_last_time variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Less than 1 month ago"                       = 1,
        "Between 1 month and less than 3 months ago"  = 2,
        "Between 3 months and less than 6 months ago" = 3,
        "Between 6 months and less than 1 year ago"   = 4,
        "Between 1 year and less than 3 years ago"    = 5,
        "3 or more years ago"                         = 6,
        "Don’t know"                                  = 7,
        "Refused"                                     = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_picture_last_time_8cat, 
      description = "Recoded sexual_picture_last_time variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Less than 1 month ago"                       = 1,
        "Between 1 month and less than 3 months ago"  = 2,
        "Between 3 months and less than 6 months ago" = 3,
        "Between 6 months and less than 1 year ago"   = 4,
        "Between 1 year and less than 3 years ago"    = 5,
        "3 or more years ago"                         = 6,
        "Don’t know"                                  = 7,
        "Refused"                                     = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_harm_last_time_8cat_f, 
      description = "Recoded sexual_harm_last_time variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_touched_last_time_8cat_f, 
      description = "Recoded sexual_touched_last_time variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_forced_last_time_8cat_f, 
      description = "Recoded sexual_forced_last_time variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_picture_last_time_8cat_f, 
      description = "Recoded sexual_picture_last_time variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_harm_times_7cat, 
      description = "Recoded sexual_harm_times variable to match levels in follow-up interview protocol",
      value_labels = c(
        "1 or 2 times"                      = 1,
        "Between 3 and less than 5 times"   = 2,
        "Between 5 and less than 10 times"  = 3,
        "Between 10 and less than 20 times" = 4,
        "20 or more times"                  = 5,
        "Don’t know"                        = 7,
        "Refused"                           = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_touched_times_7cat, 
      description = "Recoded sexual_touched_times variable to match levels in follow-up interview protocol",
      value_labels = c(
        "1 or 2 times"                      = 1,
        "Between 3 and less than 5 times"   = 2,
        "Between 5 and less than 10 times"  = 3,
        "Between 10 and less than 20 times" = 4,
        "20 or more times"                  = 5,
        "Don’t know"                        = 7,
        "Refused"                           = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_forced_times_7cat, 
      description = "Recoded sexual_forced_times variable to match levels in follow-up interview protocol",
      value_labels = c(
        "1 or 2 times"                      = 1,
        "Between 3 and less than 5 times"   = 2,
        "Between 5 and less than 10 times"  = 3,
        "Between 10 and less than 20 times" = 4,
        "20 or more times"                  = 5,
        "Don’t know"                        = 7,
        "Refused"                           = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_picture_times_7cat, 
      description = "Recoded sexual_picture_times variable to match levels in follow-up interview protocol",
      value_labels = c(
        "1 or 2 times"                      = 1,
        "Between 3 and less than 5 times"   = 2,
        "Between 5 and less than 10 times"  = 3,
        "Between 10 and less than 20 times" = 4,
        "20 or more times"                  = 5,
        "Don’t know"                        = 7,
        "Refused"                           = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_harm_times_7cat_f, 
      description = "Recoded sexual_harm_times variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_touched_times_7cat_f, 
      description = "Recoded sexual_touched_times variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_forced_times_7cat_f, 
      description = "Recoded sexual_forced_times variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_picture_times_7cat_f, 
      description = "Recoded sexual_picture_times variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_person_friends_6cat, 
      description = "Recoded sexual_person_friends variable to match levels in follow-up interview protocol",
      value_labels = c(
        "None"            = 0,
        "Very few (1 -3)" = 1,
        "Some (4 -6)"     = 2,
        "A lot (7+)"      = 3,
        "Don’t know"      = 7,
        "Refused"         = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_person_friends_6cat_f, 
      description = "Recoded sexual_person_friends variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_stranger_v2, 
       description = "Created dummy variable for sexual_incident_person_v2 variable answer 'A stranger' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_spouse_v2, 
      description = "Created dummy variable for sexual_incident_person_v2 variable answer 'A spouse or partner' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_ex_partner_v2, 
      description = "Created dummy variable for sexual_incident_person_v2 variable answer 'An ex spouse or partner' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_parent_v2, 
      description = "Created dummy variable for sexual_incident_person_v2 variable answer 'A parent or step-parentr' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_sibling_v2, 
      description = "Created dummy variable for sexual_incident_person_v2 variable answer 'A brother or sister' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_child_v2, 
      description = "Created dummy variable for sexual_incident_person_v2 variable answer 'A son or daughter' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_other_relative_v2, 
      description = "Created dummy variable for sexual_incident_person_v2 variable answer 'Another relative' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_coworker_v2, 
      description = "Created dummy variable for sexual_incident_person_v2 variable answer 'A coworker' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_neighbor_v2, 
      description = "Created dummy variable for sexual_incident_person_v2 variable answer 'A eighbor' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_friend_v2, 
      description = "Created dummy variable for sexual_incident_person_v2 variable answer 'A friend' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_non_relative_v2, 
      description = "Created dummy variable for sexual_incident_person_v2 variable answer 'Some other non-relative' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_dont_know_v2, 
      ddescription = "Created dummy variable for sexual_incident_person_v2 variable answer 'Don't know' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_refused_v2, 
      description = "Created dummy variable for sexual_incident_person_v2 variable answer 'Refused' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_stranger, 
      description = "Created dummy variable for sexual_incident_person variable answer 'A stranger' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_spouse, 
      description = "Created dummy variable for sexual_incident_person variable answer 'A spouse or partner' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_ex_partner, 
      description = "Created dummy variable for sexual_incident_person variable answer 'An ex spouse or partner' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_parent, 
      description = "Created dummy variable for sexual_incident_person variable answer 'A parent or step-parent' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_sibling, 
      description = "Created dummy variable for sexual_incident_person variable answer 'A brother or sister' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_child, 
      description = "Created dummy variable for sexual_incident_person variable answer 'A son or daughter' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_other_relative, 
      description = "Created dummy variable for sexual_incident_person variable answer 'Another relative' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_coworker, 
      description = "Created dummy variable for sexual_incident_person variable answer 'A coworker' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_neighbor, 
      description = "Created dummy variable for sexual_incident_person variable answer 'A neighbor' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_friend, 
      description = "Created dummy variable for sexual_incident_person variable answer 'A friend' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_non_relative, 
      description = "Created dummy variable for sexual_incident_person variable answer 'Some other non-relative' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_dont_know, 
      description = "Created dummy variable for sexual_incident_person variable answer 'Don't know' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_refused, 
      description = "Created dummy variable for sexual_incident_person variable answer 'Refused' since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      fear_afraid_2cat, 
      description = "Recoded fear_afraid variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      fear_future_2cat, 
      description = "Recoded fear_future variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      fear_grateful_2cat, 
      description = "Recoded fear_grateful variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      fear_forward_2cat, 
      description = "Recoded fear_forward variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      fear_important_2cat, 
      description = "Recoded fear_important variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      fear_afraid_2cat_f, 
      description = "Recoded fear_afraid variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      fear_future_2cat_f, 
      description = "Recoded fear_future variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      fear_grateful_2cat_f, 
      description = "Recoded fear_grateful variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      fear_forward_2cat_f, 
      description = "Recoded fear_forward variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      fear_important_2cat_f, 
      description = "Recoded fear_important variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      report_private_5cat, 
      description = "Recoded report_private variable to match levels in the follow-up interview protocol",
      value_labels = c(
        "Yes, for the entire time" = 1,
        "Yes, for part of the time" = 2,
        "No, but they were still close enough to hear" = 3,
        "No" = 4,
        "Don’t know" = 7
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      report_private_5cat_f, 
      description = "Recoded report_private variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      report_influence_4cat, 
      description = "Recoded report_influence variable to match levels in the follow-up interview protocol",
      value_labels = c(
        "Yes" = 1,
        "No" = 2,
        "Don’t know" = 7
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      report_influence_4cat_f, 
      description = "Recoded report_influence variable as a factor variable"
    )
```

# Pass data frame to the codebook() function

```{r}
# Add title and description to codebook
sr_codebook <- codebook(
  df = sr,
  title = "Self Report Dataset",
  description = "Data collected during DETECT follow-up interviews on self-report of injury, violence, neglect, and exploitation",
  no_summary_stats = admin_vars)
```

```{r}
print(sr_codebook, "basic_sr_codebook.docx")
```
