---
title: "General Health Codebook"
output: html_document
date: "2022-09-26"
author: Rebecca Schaefer
---

```{r}
# Load needed packages
library(codebookr)
library(dplyr, warn.conflicts = FALSE)
library(haven)
library(readr)
```

# Purpose of the program

Using the CodebookR package, we will create a data dictionary for follow-up interview data for the DETECT project.

```{r}
# Load data from General Health data set
geheal <- readRDS("~/Documents/UT Thesis/geheal_factor.rds")
```

# Set column attributes

```{r}
# Create a vector of column names that have the same source, in this case administrative data
admin_vars <- geheal %>% 
  select(1:11) %>%  # Choose the first columns in the data frame
  names()

for(i in admin_vars) {
  attr(geheal[[i]], "source") <- "Administrative data"
}
```

```{r}
# Create a vector of column names that have the same source, in this case General Health data from DETECT Follow-up Interview
geheal_vars <- geheal %>% 
  select(12:63) %>% # Choose the variables from the raw data
  names()

for(i in geheal_vars) {
  attr(geheal[[i]], "source") <- "DETECT Follow-up Interview General Health"
}
```

```{r}
# Create a vector of column names that have the same source, in this case recoded factor variables
factor_vars <- geheal %>% 
  select(64:155) %>%  #Choose the recoded variables
  names()

for(i in factor_vars) {
  attr(geheal[[i]], "source") <- "Recoded from raw data"
}
```

```{r}
# Create a template for all variables in the dataframe
for (i in seq_along(names(geheal))) {
  cat(paste0('
    cb_add_col_attributes( \n    ',
      "  ", names(geheal)[i], ', \n    ',
      "  ", 'description = ""
    ) %>%
  '))
}
```

```{r}
# Add column attributes to all variables
geheal <- geheal %>%
    cb_add_col_attributes( 
      x_created_by, 
      description = "Person who created the record"
    ) %>%
  
    cb_add_col_attributes( 
      x_created_timestamp, 
      description = "Timestamp when the record was created",
      col_type = "Time"
    ) %>%
  
    cb_add_col_attributes( 
      x_modified_by, 
      description = "Person who modified the record"
    ) %>%
  
    cb_add_col_attributes( 
      x_modified_timestamp, 
      description = "Timestamp when the record was modified",
      col_type = "Time"
    ) %>%
  
    cb_add_col_attributes( 
      x_error_message, 
      description = "Error message entered by research team"
    ) %>%
  
    cb_add_col_attributes( 
      x_record_month, 
      description = "Month record was created",
      col_type = "Time"
    ) %>%
  
    cb_add_col_attributes( 
      x_record_year, 
      description = "Year record was created",
      col_type = "Time"
    ) %>%
  
    cb_add_col_attributes( 
      x_record_status, 
      description = "Status of the record as determined by research team"
    ) %>%
  
    cb_add_col_attributes( 
      x_record_comment, 
      description = "Comments by interviewer"
    ) %>%
  
    cb_add_col_attributes( 
      medstar_id, 
      description = "Unique record number in MedStar System"
    ) %>%
  
    cb_add_col_attributes( 
      name_full, 
      description = "Full name of older individual"
    ) %>%
  
    cb_add_col_attributes( 
      health_bp_systolic, 
      description = "Vital signs, none recorded"
    ) %>%
  
    cb_add_col_attributes( 
      health_bp_diastolic, 
      description = "Vital signs, none recorded"
    ) %>%
  
    cb_add_col_attributes( 
      health_heart, 
      description = "Vital signs, none recorded"
    ) %>%
  
    cb_add_col_attributes( 
      health_oxygen, 
      description = "Vital signs, none recorded"
    ) %>%
  
    cb_add_col_attributes( 
      health_temp, 
      description = "Vital signs, none recorded"
    ) %>%
  
    cb_add_col_attributes( 
      health_pain, 
      description = "Vital signs, none recorded"
    ) %>%
  
    cb_add_col_attributes( 
      peg_pain, 
      description  = "PEG_1. What number best describes your pain on average in the past week?" 
    ) %>%
  
    cb_add_col_attributes( 
      peg_enjoyment, 
      description  = "PEG_2. What number best describes how, during the past week, pain has interfered with your enjoyment of life?"
    ) %>%
  
    cb_add_col_attributes( 
      peg_activity, 
      description  = "PEG_3. What number best describes how, during the past week, pain has interfered with your general activity?"
    ) %>%
  
    cb_add_col_attributes( 
      outcomes_health_general, 
      description = "MO_2. In general, would you say your health is..."
    ) %>%
  
    cb_add_col_attributes( 
      outcomes_health_vigorous, 
      description = "MO_3. The kinds or amounts of vigorous activities you can do, like lifting heavy objects, running or participating in strenuous sports"
    ) %>%

    cb_add_col_attributes( 
      outcomes_health_moderate, 
      description = "MO_4. The kinds or amounts of moderate activities you can do, like moving a table, carrying groceries, or bowling"
    ) %>%

    cb_add_col_attributes( 
      outcomes_health_uphill, 
      description = "MO_5. Walking uphill or climbing a few flights of stairs"
    ) %>%
  
    cb_add_col_attributes( 
      outcomes_health_bend, 
      description = "MO_6. Bending, lifting, or stooping"
    ) %>%
  
    cb_add_col_attributes( 
      outcomes_health_block, 
      description = "MO_7. Walking one block"
    ) %>%
  
    cb_add_col_attributes( 
      outcomes_health_bathe, 
      description = "MO_8. Eating, dressing, bathing or using the toilet"
    ) %>%
  
    cb_add_col_attributes( 
      outcomes4_weeks_pain, 
      description = "MO_1. How much bodily pain have you had during the past 4 weeks?"
    ) %>%

    cb_add_col_attributes( 
      outcomes_health_keep, 
      description = "MO_9. Does your health keep you from working at a job, doing work around the house, or going to school?"
    ) %>%
  
    cb_add_col_attributes( 
      outcomes_health_unable, 
      description = "MO_10. Have you been unable to do certain kinds or amounts of work, housework, or schoolwork because of your health?"
    ) %>%
  
    cb_add_col_attributes( 
      outcomes_month_social, 
      description = "MO_11. How much of the time during the past month has your health limited your social activities (like visiting with friends or close relatives)?"
    ) %>%
  
    cb_add_col_attributes( 
      outcomes_month_nervous, 
      description = "MO_12. How much of the time, during the past month, have you been a very nervous person?"
    ) %>%
  
    cb_add_col_attributes( 
      outcomes_month_calm, 
      description = "MO_13. During the past month, how much of the time have you felt calm and peaceful?"
    ) %>%
  
    cb_add_col_attributes( 
      outcomes_month_blue, 
      description = "MO_14. How much of the time, during the past month, have you felt downhearted and blue?"
    ) %>%
  
    cb_add_col_attributes( 
      outcomes_month_happy, 
      description = "MO_15. During the past month, how much of the time have you been a happy person?"
    ) %>%
  
    cb_add_col_attributes( 
      outcomes_month_dumps, 
      description = "MO_16. How often, during the past month, have you felt so down in the dumps that nothing could cheer you up?"
    ) %>%
  
    cb_add_col_attributes( 
      outcomes_tf_ill, 
      description = "MO_17. I am somewhat ill"
    ) %>%
  
    cb_add_col_attributes( 
      outcomes_tf_anybody, 
      description = "MO_18. I am as healthy as anybody I know"
    ) %>%
  
    cb_add_col_attributes( 
      outcomes_tf_health, 
      description = "MO_19. My health is excellent"
    ) %>%
  
    cb_add_col_attributes( 
      outcomes_tf_bad, 
      description = "MO_20. I have been feeling bad lately"
    ) %>%
  
    cb_add_col_attributes( 
      depres_satisfied, 
      description = "GD_1. Are you basically satisfied with your life?"
    ) %>%
  
    cb_add_col_attributes( 
      depres_hopeless, 
      description = "GD_2. Do you feel that your situation is hopeless?"
    ) %>%
  
    cb_add_col_attributes( 
      depres_better, 
      description = "GD_3. Do you think that most people are better off than you are?"
    ) %>%
  
    cb_add_col_attributes( 
      depres_activities, 
      description = "GD_4. Have you dropped many of your activities and interests?"
    ) %>%
  
    cb_add_col_attributes( 
      depres_empty, 
      description = "GD_5. Do you feel that your life is empty?"
    ) %>%
  
    cb_add_col_attributes( 
      depres_bored, 
      description = "GD_6. Do you often get bored?"
    ) %>%
  
    cb_add_col_attributes( 
      depres_spirits, 
      description = "GD_7. Are you in good spirits most of the time?"
    ) %>%
  
    cb_add_col_attributes( 
      depres_afraid, 
      description = "GD_8. Are you afraid that something bad is going to happen to you?"
    ) %>%
  
    cb_add_col_attributes( 
      depres_happy, 
      description = "GD_9. Do you feel happy most of the time?"
    ) %>%
  
    cb_add_col_attributes( 
      depres_helpless, 
      description = "GD_10. Do you often feel helpless?"
    ) %>%
  
    cb_add_col_attributes( 
      depres_home, 
      description = "GD_11. Do you prefer to stay at home, rather than going out and doing things?"
    ) %>%
  
    cb_add_col_attributes( 
      depres_memory, 
      description = "GD_12. Do you feel that you have more problems with your memory than most?"
    ) %>%
  
    cb_add_col_attributes( 
      depres_alive, 
      description = "GD_13. Do you think it is wonderful to be alive now?"
    ) %>%
  
    cb_add_col_attributes( 
      depres_worthless, 
      description = "GD_14. Do you feel worthless the way you are now?"
    ) %>%
  
    cb_add_col_attributes( 
      depres_energy, 
      description = "GD_15. Do you feel full of energy?"
    ) %>%
  
    cb_add_col_attributes( 
      ls_lack_companionship, 
      description = "LS_1. First, how often do you feel that you lack companionship?"
    ) %>%
  
    cb_add_col_attributes( 
      ls_feel_left_out, 
      description = "LS_2. How often do you feel left out?"
    ) %>%

    cb_add_col_attributes( 
      ls_feel_isolated, 
      description = "LS_3. How often do you feel isolated from others?"
    ) %>%

    cb_add_col_attributes( 
      nesarc_drink, 
      description = "NC_1. In your entire life, have you had at least 1 drink of any kind of alcohol, not counting small tastes or sips?",
      skip_pattern = "If answer is No, go to Section 3."
    ) %>%

    cb_add_col_attributes( 
      nesarc_months, 
      description = "NC_2. During the last 12 months, did you have at least 1 drink of any kind of alcohol?",
      skip_pattern = "If answer is No, go to Section 3."
    ) %>%
  
    cb_add_col_attributes( 
      auditc_drink, 
      description = "AC_1. How often do you have a drink containing alcohol?",
      skip_pattern = "If answer is Never, go to Section 3."
    ) %>%

    cb_add_col_attributes( 
      auditc_day, 
      description = "AC_2. How many standard drinks containing alcohol do you have on a typical day?"
    ) %>%
  
    cb_add_col_attributes( 
      auditc_five, 
      description = "AC_3. How often do you have five or more drinks on one occasion?"
    ) %>%

    cb_add_col_attributes( 
      peg_pain_12cat, 
      description  = "Recoded variable peg_pain to match levels in follow-up interview protocol",
      value_labels = c(
        "No Pain"                        = 0, 
        "1"                              = 1, 
        "2"                              = 2, 
        "3"                              = 3,
        "4"                              = 4,
        "5"                              = 5,
        "6"                              = 6,
        "7"                              = 7,
        "8"                              = 8,
        "9"                              = 9,
        "Pain as bad as you can imagine" = 10,
        "Refused"                        = 99
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      peg_enjoyment_12cat, 
      description  = "Recoded variable peg_enjoyment to match levels in follow-up interview protocol",
      value_labels = c(
        "No Pain"                        = 0, 
        "1"                              = 1, 
        "2"                              = 2, 
        "3"                              = 3,
        "4"                              = 4,
        "5"                              = 5,
        "6"                              = 6,
        "7"                              = 7,
        "8"                              = 8,
        "9"                              = 9,
        "Pain as bad as you can imagine" = 10,
        "Refused"                        = 99
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      peg_activity_12cat, 
      description  = "Recoded variable peg_activity to match levels in follow-up interview protocol",
      value_labels = c(
        "0 - No Pain"                    = 0, 
        "1"                              = 1, 
        "2"                              = 2, 
        "3"                              = 3,
        "4"                              = 4,
        "5"                              = 5,
        "6"                              = 6,
        "7"                              = 7,
        "8"                              = 8,
        "9"                              = 9,
        "10 - Pain as bad as you can imagine" = 10,
        "Refused"                             = 99
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      peg_pain_12cat_f, 
      description = "Recoded variable peg_pain as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      peg_enjoyment_12cat_f, 
      description = "Recoded variable peg_enjoyment as a factor variable"
    ) %>%

    cb_add_col_attributes( 
      peg_activity_12cat_f, 
      description = "Recoded variable peg_activity as a factor variable"
    ) %>%

    cb_add_col_attributes(
      outcomes_health_general_7cat, 
      description = "Recoded variable outcomes_health_general to match levels in follow-up interview protocol",
      value_labels = c(
        "Excellent"  = 1, 
        "Very good"  = 2, 
        "Good"       = 3, 
        "Fair"       = 4, 
        "Poor"       = 5,
        "Don't know" = 7,
        "Refused"    = 9
        ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      outcomes_health_general_7cat_f, 
      description = "Recoded variable outcomes_health_general as a factor variable"
    ) %>%

    cb_add_col_attributes( 
      outcomes_health_vigorous_5cat, 
      description = "Recoded variable outcomes_health_vigorous to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes, limited for more than 3 months" = 1, 
        "Yes, limited for 3 months or less"   = 2, 
        "Not limited at all"                  = 3, 
        "Don’t know"                          = 7,
        "Refused"                             = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      outcomes_health_moderate_5cat, 
      description = "Recoded variable outcomes_health_moderate to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes, limited for more than 3 months" = 1, 
        "Yes, limited for 3 months or less"   = 2, 
        "Not limited at all"                  = 3, 
        "Don’t know"                          = 7,
        "Refused"                             = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      outcomes_health_uphill_5cat, 
      description = "Recoded variable outcomes_health_uphill to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes, limited for more than 3 months" = 1, 
        "Yes, limited for 3 months or less"   = 2, 
        "Not limited at all"                  = 3, 
        "Don’t know"                          = 7,
        "Refused"                             = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      outcomes_health_bend_5cat, 
      description = "Recoded variable outcomes_health_bend to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes, limited for more than 3 months" = 1, 
        "Yes, limited for 3 months or less"   = 2, 
        "Not limited at all"                  = 3, 
        "Don’t know"                          = 7,
        "Refused"                             = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      outcomes_health_block_5cat, 
      description = "Recoded variable outcomes_health_block to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes, limited for more than 3 months" = 1, 
        "Yes, limited for 3 months or less"   = 2, 
        "Not limited at all"                  = 3, 
        "Don’t know"                          = 7,
        "Refused"                             = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      outcomes_health_bathe_5cat, 
      description = "Recoded variable outcomes_health_bathe to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes, limited for more than 3 months" = 1, 
        "Yes, limited for 3 months or less"   = 2, 
        "Not limited at all"                  = 3, 
        "Don’t know"                          = 7,
        "Refused"                             = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      outcomes_health_vigorous_5cat_f, 
      description = "Recoded variable outcomes_health_vigorous as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      outcomes_health_moderate_5cat_f, 
      description = "Recoded variable outcomes_health_moderate as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      outcomes_health_uphill_5cat_f, 
      description = "Recoded variable outcomes_health_uphill as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      outcomes_health_bend_5cat_f, 
      description = "Recoded variable outcomes_health_bend as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      outcomes_health_block_5cat_f, 
      description = "Recoded variable outcomes_health_block as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      outcomes_health_bathe_5cat_f, 
      description = "Recoded variable outcomes_health_bathe as a factor variable"
    ) %>%
  
    cb_add_col_attributes(
      outcomes4_weeks_pain_8cat, 
      description = "Recoded variable outcomes4_weeks_pain to match levels in follow-up interview protocol",
      value_labels = c(
        "None"        = 0, 
        "Very mild"   = 1, 
        "Mild"        = 2, 
        "Moderate"    = 3, 
        "Severe"      = 4,
        "Very Severe" = 5,
        "Don't know"  = 7,
        "Refused"     = 9
        ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      outcomes4_weeks_pain_8cat_f, 
      description = "Recoded variable outcomes4_weeks_pain as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      outcomes_health_keep_5cat, 
      description = "Recoded variable outcomes_health_keep to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes, for more than 3 months" = 1, 
        "Yes, for 3 months or less"   = 2, 
        "No"                          = 3, 
        "Don’t know"                  = 7,
        "Refused"                     = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      outcomes_health_unable_5cat, 
      description = "Recoded variable outcomes_health_unable to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes, for more than 3 months" = 1, 
        "Yes, for 3 months or less"   = 2, 
        "No"                          = 3, 
        "Don’t know"                  = 7,
        "Refused"                     = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      outcomes_health_keep_5cat_f, 
      description = "Recoded variable outcomes_health_keep as a factor variable"
    ) %>%

    cb_add_col_attributes( 
      outcomes_health_unable_5cat_f, 
      description = "Recoded variable outcomes_health_unable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      outcomes_month_social_7cat, 
      description = "Recoded variable outcomes_month_social to match levels in follow-up interview protocol",
      value_labels = c(
        "All of the time"      = 1, 
        "Most of the time"     = 2, 
        "Some of the time"     = 3, 
        "A little of the time" = 4,
        "None of the time"     = 5,
        "Don’t know"           = 7,
        "Refused"              = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      outcomes_month_nervous_7cat, 
      description = "Recoded variable outcomes_month_nervous to match levels in follow-up interview protocol",
      value_labels = c(
        "All of the time"      = 1, 
        "Most of the time"     = 2, 
        "Some of the time"     = 3, 
        "A little of the time" = 4,
        "None of the time"     = 5,
        "Don’t know"           = 7,
        "Refused"              = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      outcomes_month_calm_7cat, 
      description = "Recoded variable outcomes_month_calm to match levels in follow-up interview protocol",
      value_labels = c(
        "All of the time"      = 1, 
        "Most of the time"     = 2, 
        "Some of the time"     = 3, 
        "A little of the time" = 4,
        "None of the time"     = 5,
        "Don’t know"           = 7,
        "Refused"              = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      outcomes_month_blue_7cat, 
      description = "Recoded variable outcomes_month_blue to match levels in follow-up interview protocol",
      value_labels = c(
        "All of the time"      = 1, 
        "Most of the time"     = 2, 
        "Some of the time"     = 3, 
        "A little of the time" = 4,
        "None of the time"     = 5,
        "Don’t know"           = 7,
        "Refused"              = 9
      ),
      col_type = "Categorical"
    ) %>%

    cb_add_col_attributes( 
      outcomes_month_happy_7cat, 
      description = "Recoded variable outcomes_month_happy to match levels in follow-up interview protocol",
      value_labels = c(
        "All of the time"      = 1, 
        "Most of the time"     = 2, 
        "Some of the time"     = 3, 
        "A little of the time" = 4,
        "None of the time"     = 5,
        "Don’t know"           = 7,
        "Refused"              = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      outcomes_month_dumps_7cat, 
      description = "Recoded variable outcomes_month_dumps to match levels in follow-up interview protocol",
      value_labels = c(
        "All of the time"      = 1, 
        "Most of the time"     = 2, 
        "Some of the time"     = 3, 
        "A little of the time" = 4,
        "None of the time"     = 5,
        "Don’t know"           = 7,
        "Refused"              = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      outcomes_month_social_7cat_f, 
      description = "Recoded variable outcomes_month_social as a factor variable"
    ) %>%

    cb_add_col_attributes( 
      outcomes_month_nervous_7cat_f, 
      description = "Recoded variable outcomes_month_nervous as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      outcomes_month_calm_7cat_f, 
      description = "Recoded variable outcomes_month_calm as a factor variable"
    ) %>%

    cb_add_col_attributes( 
      outcomes_month_blue_7cat_f, 
      description = "Recoded variable outcomes_month_blue as a factor variable"
    ) %>%

    cb_add_col_attributes( 
      outcomes_month_happy_7cat_f, 
      description = "Recoded variable outcomes_month_happy as a factor variable"
    ) %>%

    cb_add_col_attributes( 
      outcomes_month_dumps_7cat_f, 
      description = "Recoded variable outcomes_month_dumps as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      outcomes_tf_ill_6cat, 
      description = "Recoded variable outcomes_tf_ill to match levels in follow-up interview protocol",
      value_labels = c(
        "Definitely true"  = 1, 
        "Mostly true"      = 2, 
        "Don't know"       = 3, 
        "Mostly false"     = 4,
        "Definitely false" = 5,
        "Refused"          = 9
      ),
      col_type = "Categorical"
    ) %>%

    cb_add_col_attributes( 
      outcomes_tf_anybody_6cat, 
      description = "Recoded variable outcomes_tf_anybody to match levels in follow-up interview protocol",
      value_labels = c(
        "Definitely true"  = 1, 
        "Mostly true"      = 2, 
        "Don't know"       = 3, 
        "Mostly false"     = 4,
        "Definitely false" = 5,
        "Refused"          = 9
      ),
      col_type = "Categorical"
    ) %>%

    cb_add_col_attributes( 
      outcomes_tf_health_6cat, 
      description = "Recoded variable outcomes_tf_health to match levels in follow-up interview protocol",
      value_labels = c(
        "Definitely true"  = 1, 
        "Mostly true"      = 2, 
        "Don't know"       = 3, 
        "Mostly false"     = 4,
        "Definitely false" = 5,
        "Refused"          = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      outcomes_tf_bad_6cat, 
      description = "Recoded variable outcomes_tf_bad to match levels in follow-up interview protocol",
      value_labels = c(
        "Definitely true"  = 1, 
        "Mostly true"      = 2, 
        "Don't know"       = 3, 
        "Mostly false"     = 4,
        "Definitely false" = 5,
        "Refused"          = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      outcomes_tf_ill_6cat_f, 
      description = "Recoded variable outcomes_tf_ill as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      outcomes_tf_anybody_6cat_f, 
      description = "Recoded variable outcomes_tf_anybody as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      outcomes_tf_health_6cat_f, 
      description = "Recoded variable outcomes_tf_health as a factor variable"
    ) %>%

    cb_add_col_attributes( 
      outcomes_tf_bad_6cat_f, 
      description = "Recoded variable outcomes_tf_bad as a factor variable"
    ) %>%

    cb_add_col_attributes( 
      depres_satsified_2cat, 
      description = "Recoded variable depres_satsified to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes"  = 0, 
        "No"   = 1 
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      depres_satsified_2cat_f, 
      description = "Recoded variable depres_satsified as a factor variable"
    ) %>%

    cb_add_col_attributes( 
      depres_hopeless_2cat, 
      description = "Recoded variable depres_hopeless to match levels in follow-up interview protocol",
      value_labels = c(
        "No"  = 0, 
        "Yes" = 1 
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      depres_hopeless_2cat_f, 
      description = "Recoded variable depres_hopeless as a factor variable"
    ) %>%

    cb_add_col_attributes( 
      depres_better_2cat, 
      description = "Recoded variable depres_better to match levels in follow-up interview protocol",
      value_labels = c(
        "No"  = 0, 
        "Yes" = 1 
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      depres_better_2cat_f, 
      description = "Recoded variable depres_better as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      depres_activities_2cat, 
      description = "Recoded variable depres_activities to match levels in follow-up interview protocol",
      value_labels = c(
        "No"  = 0, 
        "Yes" = 1 
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      depres_activities_2cat_f, 
      description = "Recoded variable depres_activities as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      depres_empty_2cat, 
      description = "Recoded variable depres_empty to match levels in follow-up interview protocol",
      value_labels = c(
        "No"  = 0, 
        "Yes" = 1 
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      depres_empty_2cat_f, 
      description = "Recoded variable depres_empty as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      depres_bored_2cat, 
      description = "Recoded variable depres_bored to match levels in follow-up interview protocol",
      value_labels = c(
        "No"  = 0, 
        "Yes" = 1 
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      depres_bored_2cat_f, 
      description = "Recoded variable depres_bored as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      depres_spirits_2cat, 
      description = "Recoded variable depres_spirits to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes"  = 0, 
        "No"   = 1 
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      depres_spirits_2cat_f, 
      description = "Recoded variable depres_spirits as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      depres_afraid_2cat, 
      description = "Recoded variable depres_afraid to match levels in follow-up interview protocol",
      value_labels = c(
        "No"  = 0, 
        "Yes" = 1 
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      depres_afraid_2cat_f, 
      description = "Recoded variable depres_afraid as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      depres_happy_2cat, 
      description = "Recoded variable depres_happy to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes"  = 0, 
        "No"   = 1 
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      depres_happy_2cat_f, 
      description = "Recoded variable depres_happy as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      depres_helpless_2cat, 
      description = "Recoded variable depres_helpless to match levels in follow-up interview protocol",
      value_labels = c(
        "No"  = 0, 
        "Yes" = 1 
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      depres_helpless_2cat_f, 
      description = "Recoded variable depres_helpless as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      depres_home_2cat, 
      description = "Recoded variable depres_home to match levels in follow-up interview protocol",
      value_labels = c(
        "No"  = 0, 
        "Yes" = 1 
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      depres_home_2cat_f, 
      description = "Recoded variable depres_home as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      depres_memory_2cat, 
      description = "Recoded variable depres_memory to match levels in follow-up interview protocol",
      value_labels = c(
        "No"  = 0, 
        "Yes" = 1 
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      depres_memory_2cat_f, 
      description = "Recoded variable depres_memory as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      depres_alive_2cat, 
      description = "Recoded variable depres_alive to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes"  = 0, 
        "No"   = 1 
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      depres_alive_2cat_f, 
      description = "Recoded variable depres_alive as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      depres_worthless_2cat, 
      description = "Recoded variable depres_worthless to match levels in follow-up interview protocol",
      value_labels = c(
        "No"  = 0, 
        "Yes" = 1 
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      depres_worthless_2cat_f, 
      description = "Recoded variable depres_worthless as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      depres_energy_2cat, 
      description = "Recoded variable depres_energy to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes"  = 0, 
        "No"   = 1 
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      depres_energy_2cat_f, 
      description = "Recoded variable depres_energy as a factor variable"
    ) %>%

    cb_add_col_attributes( 
      ls_lack_companionship_4cat, 
      description = "Recoded variable ls_lack_companionship to match levels in follow-up interview protocol",
      value_labels = c(
        "Hardly ever"      = 1, 
        "Some of the time" = 2,
        "Often"            = 3,
        "Refused"          = 9
      ),
      col_type = "Categorical"
    ) %>%

    cb_add_col_attributes( 
      ls_feel_left_out_4cat, 
      description = "Recoded variable ls_feel_left_out to match levels in follow-up interview protocol",
      value_labels = c(
        "Hardly ever"      = 1, 
        "Some of the time" = 2,
        "Often"            = 3,
        "Refused"          = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      ls_feel_isolated_4cat, 
      description = "Recoded variable ls_feel_isolated to match levels in follow-up interview protocol",
      value_labels = c(
        "Hardly ever"      = 1, 
        "Some of the time" = 2,
        "Often"            = 3,
        "Refused"          = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      ls_lack_companionship_4cat_f, 
      description = "Recoded variable ls_lack_companionship as a factor variable"
    ) %>%

    cb_add_col_attributes( 
      ls_feel_left_out_4cat_f, 
      description = "Recoded variable ls_feel_left_out as a factor variable"
    ) %>%

    cb_add_col_attributes( 
      ls_feel_isolated_4cat_f, 
      description = "Recoded variable ls_feel_isolated as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      nesarc_drink_4cat, 
      description = "Recoded variable nesarc_drink to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1, 
        "No"         = 2,
        "Don't know" = 3,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      nesarc_months_4cat, 
      description = "Recoded variable nesarc_months to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1, 
        "No"         = 2,
        "Don't know" = 3,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      nesarc_drink_4cat_f, 
      description = "Recoded variable nesarc_drink as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      nesarc_months_4cat_f, 
      description = "Recoded variable nesarc_months as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      auditc_drink_7cat, 
      description = "Recoded variable auditc_drink to match levels in follow-up interview protocol",
      value_labels = c(
        "Never"                  = 0, 
        "Monthly or less"        = 1,
        "2-4 times a month"      = 2,
        "2-3 times a week"       = 3,
        "4 or more times a week" = 4,
        "Don't know"             = 7,
        "Refused"                = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      auditc_drink_7cat_f, 
      description = "Recoded variable auditc_drink as a factor variable"
    ) %>%

    cb_add_col_attributes( 
      auditc_day_7cat, 
      description = "Recoded variable auditc_day to match levels in follow-up interview protocol",
      value_labels = c(
        "1 or 2"     = 1, 
        "3 or 4"     = 2,
        "5 or 6"     = 3,
        "7 to 9"     = 4,
        "10 or more" = 5,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      auditc_day_7cat_f, 
      description = "Recoded variable auditc_day as a factor variable"
    ) %>%

    cb_add_col_attributes( 
      auditc_five_7cat, 
      description = "Recoded variable auditc_five to match levels in follow-up interview protocol",
      value_labels = c(
        "Never"                 = 0, 
        "Less than monthly"     = 1,
        "Monthly"               = 2,
        "Weekly"                = 3,
        "Daily or almost daily" = 4,
        "Don't know"            = 7,
        "Refused"               = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      auditc_five_7cat_f, 
      description = "Recoded variable auditc_five as a factor variable"
    )
  
```

# Pass data frame to the codebook() function

```{r}
# Add title and description to codebook
geheal_codebook <- codebook(
  df = geheal,
  title = "General Health Dataset",
  description = "Data collected during DETECT follow-up interviews regarding the patient's general health and safety",
  no_summary_stats = admin_vars)
```

```{r}
print(geheal_codebook, "basic_geheal_codebook.docx")
```