---
title: "CodebookR Observational Measures data from recoded data"
author: "Marissa Gough"
---

```{r}
# Load necessary packages
library(codebookr)
library(dplyr, warn.conflicts = FALSE)
library(readr)
```

# Purpose of the program

Using the CodebookR package, we will create a data dictionary for follow-up interview data for the DETECT project.

```{r}
# Load data from APS Investigations data set
obs <- read_rds("~.../detect_public/data/obs_factor.rds") #598 184
```

# Set column attributes

```{r}
# Create a vector of column names that have the same source, in this case administrative data
admin_vars <- obs %>% 
  select(1:11) %>%  # Choose the first columns in the data frame
  names()

for(i in admin_vars) {
  attr(obs[[i]], "source") <- "Administrative data"
}
```

```{r}
# Create a vector of column names that have the same source, in this case, DETECT Screening items

obs_vars <- obs %>% 
  select(12:26) %>% # Choose the variables from the raw data
  names()

for(i in obs_vars) {
  attr(obs[[i]], "source") <- "Detection of Elder abuse Through Emergency Care Technicians (DETECT) Screening Items"
}
```

```{r}
# Create a vector of column names that have the same source, in this case Observational Measures
obs_vars <- obs %>% 
  select('hygiene':'aps_reported_method') %>% # Choose the variables from the raw data
  names()

for(i in obs_vars) {
  attr(obs[[i]], "source") <- "DETECT Follow-up Interview Questions Observational Measures"
}
```

```{r}
# Create a vector of column names that have the same description, in this case Observational Measures variables that were used in older versions of the follow-up interview
obs_vars <- obs %>% 
  select('hygiene':'aps_reported_method') %>% # Choose the variables from the raw data
  names()

for(i in obs_vars) {
  attr(obs[[i]], "description") <- "Variable used in older version of follow-up interview. Not in use in most recent protocol"
}
```

```{r}
# Create a vector of column names that have the same source, in this case Medic EM Assessment
obs_vars <- obs %>% 
  select('at_physical':'at_self_why') %>% # Choose the variables from the raw data
  names()

for(i in obs_vars) {
  attr(obs[[i]], "source") <- "Observational Measures - Medic EM Assessment"
}
```

```{r}
# Create a vector of column names that have the same source, in this case recoded factor variables
factor_vars <- obs %>% 
  select(102:184) %>%  #Choose the recoded variables
  names()

for(i in factor_vars) {
  attr(obs[[i]], "source") <- "Recoded from raw data"
}
```

```{r}
# Choose variables that will not have summary statistics
no_stats <- obs %>%
  select(1:11, 33, 39,40, 53, 54, 59, 60, 63, 64, 84, 86, 89, 91, 93, 95, 97, 99, 101)

no_stats_vars <- colnames(no_stats)
```

```{r}
# Create a template for all variables in the data frame
for (i in seq_along(names(obs))) {
  cat(paste0('
    cb_add_col_attributes( \n    ',
      "  ", names(obs)[i], ', \n    ',
      "  ", 'description = ""
    ) %>%
  '))
}
```

```{r}
# Add column attributes to all variables

obs <- obs %>%
    cb_add_col_attributes( 
      x_created_by, 
      description = "Person who created the record"
    ) %>%
  
    cb_add_col_attributes( 
      x_created_timestamp, 
      description = "Timestamp when the record was created",
      col_type = "Time"
    ) %>%
  
    cb_add_col_attributes( 
      x_modified_by, 
      description = "Person who modified the record"
    ) %>%
  
    cb_add_col_attributes( 
      x_modified_timestamp, 
      description = "Timestamp when the record was modified",
      col_type = "Time"
    ) %>%
  
    cb_add_col_attributes( 
      x_error_message, 
      description = "Error message entered by research team"
    ) %>%
  
    cb_add_col_attributes( 
      x_record_month, 
      description = "Month record was created",
      col_type = "Time"
    ) %>%
  
    cb_add_col_attributes( 
      x_record_year, 
      description = "Year record was created",
      col_type = "Time"
    ) %>%
  
    cb_add_col_attributes( 
      x_record_status, 
      description = "Status of the record as determined by research team"
    ) %>%
  
    cb_add_col_attributes( 
      x_record_comment, 
      description = "Comments by interviewer"
    ) %>%
  
    cb_add_col_attributes( 
      medstar_id, 
      description = "Unique record number in MedStar System"
    ) %>%
  
    cb_add_col_attributes( 
      name_full, 
      description = "Full name of older individual"
    ) %>%
  
    cb_add_col_attributes( 
      unusual_odor, 
      description = "Unusual odors (e.g. urine, feces) that are unrelated to current medical conditions and/or are more extreme than expected given current medical conditions"
    ) %>%
  
    cb_add_col_attributes( 
      disarray_hoarding, 
      description = "Inside of home is in extreme disarray/hoarding"
    ) %>%
  
    cb_add_col_attributes( 
      health_safety_concern, 
      description = "Living environment poses a health or safety concern (e.g., fire hazard, insect or rodent infestation, urine or feces present)"
    ) %>%
  
    cb_add_col_attributes( 
      caregiver_lack_knowledge, 
      description = "If caregiver present, they appear to lack knowledge of the patient/older adult’s medical needs"
    ) %>%
  
    cb_add_col_attributes( 
      caregiver_unengaged, 
      description = "If caregiver(s) present, they appear unengaged an inattentive in caring for the patient/older adult"
    ) %>%
  
    cb_add_col_attributes( 
      caregiver_frustrated, 
      description = "If caregiver(s) present, they appear frustrated, tired, angry or burdened by the patient/older adult"
    ) %>%
  
    cb_add_col_attributes( 
      caregiver_anxious, 
      description = "If caregiver(s) present, they appear overly concerned (e.g., anxious, hovering)"
    ) %>%
  
    cb_add_col_attributes( 
      isolated_home, 
      description = "Is the older adult isolated in the home and/or cut-off from needed social networks or supports?"
    ) %>%
  
    cb_add_col_attributes( 
      depressed, 
      description = "Does the older adult appear depressed, anxious, or emotionally distressed for reasons other than their immediate medical condition?"
    ) %>%
  
    cb_add_col_attributes( 
      poor_personal_hygiene, 
      description = "Does the older adult have poor personal hygiene (including soiled in urine or feces)?"
    ) %>%
  
    cb_add_col_attributes( 
      inadequately_clothed, 
      description = "Is the older adult inadequately clothed or wearing dirty, torn, or soiled clothing?"
    ) %>%
  
    cb_add_col_attributes( 
      difficulty_medications, 
      description = "Does the older adult have difficulties taking their prescribed medications as directed?"
    ) %>%
  
    cb_add_col_attributes( 
      hoarding_medications, 
      description = "Does the older adult appear to be hoarding/saving old medications?"
    ) %>%
  
    cb_add_col_attributes( 
      unmet_needs, 
      description = "Is/Does the patient/older adult have unmet needs for assistance with eating, toileting, transferring, dressing, or bathing?"
    ) %>%
  
    cb_add_col_attributes( 
      report_elder_abuse, 
      description = "Did you report elder abuse/neglect to APS, or, do you plan to based on what you just observed?"
    ) %>%
  
   cb_add_col_attributes( 
      hygiene, 
      description = "Elder Assessment Instrument (EAI) / Self-neglect Severity Scale General Assessment: Hygeine. Question from earlier version of follow-up interview."
    ) %>%
  
    cb_add_col_attributes( 
      nutrition, 
      description = "Elder Assessment Instrument (EAI) / Self-neglect Severity Scale General Assessment: Nutrition. Question from earlier version of follow-up interview."
    ) %>%
  
    cb_add_col_attributes( 
      skin_integrity, 
      description = "Elder Assessment Instrument (EAI) / Self-neglect Severity Scale General Assessment: Skin-integrity. Question from earlier version of follow-up interview."
    ) %>%
  
    cb_add_col_attributes( 
      clothes, 
      description = "Elder Assessment Instrument (EAI) / Self-neglect Severity Scale General Assessment: Clothes. Question from earlier version of follow-up interview."
    ) %>%
  
    cb_add_col_attributes( 
      hair, 
      description = "Elder Assessment Instrument (EAI) / Self-neglect Severity Scale General Assessment: Hair. Question from earlier version of follow-up interview."
    ) %>%
  
    cb_add_col_attributes( 
      nails, 
      description = "Elder Assessment Instrument (EAI) / Self-neglect Severity Scale General Assessment: Nails. Question from earlier version of follow-up interview."
    ) %>%
  
    cb_add_col_attributes( 
      general_assessment_comments, 
      description = "Elder Assessment Instrument (EAI) / Self-neglect Severity Scale General Assessment: Additional Comments. Question from earlier version of follow-up interview."
    ) %>%
  
    cb_add_col_attributes( 
      bruising, 
      description = "Elder Assessment Instrument (EAI) / Self-neglect Severity Scale Possible Abuse Indicators: Bruising. Question from earlier version of follow-up interview."
    ) %>%
  
    cb_add_col_attributes( 
      lacerations, 
      description = "Elder Assessment Instrument (EAI) / Self-neglect Severity Scale Possible Abuse Indicators: Lacerations. Question from earlier version of follow-up interview."
    ) %>%
  
    cb_add_col_attributes( 
      fractures, 
      description = "Elder Assessment Instrument (EAI) / Self-neglect Severity Scale Possible Abuse Indicators: Fractures. Question from earlier version of follow-up interview."
    ) %>%
  
    cb_add_col_attributes( 
      stages_healing, 
      description = "Elder Assessment Instrument (EAI) / Self-neglect Severity Scale Possible Abuse Indicators: Various stages of healing of any bruises or fractures/ Question from earlier version of follow-up interview."
    ) %>%
  
    cb_add_col_attributes( 
      sexual_abuse, 
      description = "Elder Assessment Instrument (EAI) / Self-neglect Severity Scale Possible Abuse Indicators: Evidence of sexual abuse. Question from earlier version of follow-up interview."
    ) %>%
  
    cb_add_col_attributes( 
      abuse_statement, 
      description = "Elder Assessment Instrument (EAI) / Self-neglect Severity Scale Possible Abuse Indicators: Statement by older adult related to abuse. Question from earlier version of follow-up interview."
    ) %>%
  
    cb_add_col_attributes( 
      abuse_indicators_comments, 
      description = "Elder Assessment Instrument (EAI) / Self-neglect Severity Scale Possible Abuse Indicators: Additional comments. Question from earlier version of follow-up interview."
    ) %>%
  
    cb_add_col_attributes( 
      contracture, 
      description = "Elder Assessment Instrument (EAI) / Self-neglect Severity Scale Possible Neglect Indicators: Contractures. Question from earlier version of follow-up interview."
    ) %>%
  
    cb_add_col_attributes( 
      decubitus, 
      description = "Elder Assessment Instrument (EAI) / Self-neglect Severity Scale Possible Neglect Indicators: Decubitii Question from earlier version of follow-up interview."
    ) %>%
  
    cb_add_col_attributes( 
      dehydration, 
      description = "Elder Assessment Instrument (EAI) / Self-neglect Severity Scale Possible Neglect Indicators: Dehydration. Question from earlier version of follow-up interview."
    ) %>%
  
    cb_add_col_attributes( 
      diarrhea, 
      description = "Elder Assessment Instrument (EAI) / Self-neglect Severity Scale Possible Neglect Indicators: Diarrhea. Question from earlier version of follow-up interview."
    ) %>%
  
    cb_add_col_attributes( 
      depression, 
      description = "Elder Assessment Instrument (EAI) / Self-neglect Severity Scale Possible Neglect Indicators: Depression. Question from earlier version of follow-up interview."
    ) %>%
  
    cb_add_col_attributes( 
      impaction, 
      description = "Elder Assessment Instrument (EAI) / Self-neglect Severity Scale Possible Neglect Indicators: Impaction. Question from earlier version of follow-up interview."
    ) %>%
  
    cb_add_col_attributes( 
      malnutrition, 
      description = "Elder Assessment Instrument (EAI) / Self-neglect Severity Scale Possible Neglect Indicators: Malnutrition. Question from earlier version of follow-up interview."
    ) %>%
  
    cb_add_col_attributes( 
      urine_burn, 
      description = "Elder Assessment Instrument (EAI) / Self-neglect Severity Scale Possible Neglect Indicators: Urine burns. Question from earlier version of follow-up interview."
    ) %>%
  
    cb_add_col_attributes( 
      poor_hygiene, 
      description = "Elder Assessment Instrument (EAI) / Self-neglect Severity Scale Possible Neglect Indicators: Poor hygiene. Question from earlier version of follow-up interview."
    ) %>%
  
    cb_add_col_attributes( 
      obvious_disease, 
      description = "Elder Assessment Instrument (EAI) / Self-neglect Severity Scale Possible Neglect Indicators:  Failure to respond to warning of obvious disease Question from earlier version of follow-up interview."
    ) %>%
  
    cb_add_col_attributes( 
      inappropriate_medication, 
      description = "Elder Assessment Instrument (EAI) / Self-neglect Severity Scale Possible Neglect Indicators: Inappropirate medications (over/under). Question from earlier version of follow-up interview."
    ) %>%
  
    cb_add_col_attributes( 
      repetitive_hosp_admission, 
      description = "Elder Assessment Instrument (EAI) / Self-neglect Severity Scale Possible Neglect Indicators: Repetitive hospital admissions due to probable failure of health care surveillance. Question from earlier version of follow-up interview."
    ) %>%
  
    cb_add_col_attributes( 
      neglect_statement, 
      description = "Elder Assessment Instrument (EAI) / Self-neglect Severity Scale Possible Neglect Indicators: Statement by older adult related to neglect. Question from earlier version of follow-up interview."
    ) %>%
  
    cb_add_col_attributes( 
      neglect_comments, 
      description = "Elder Assessment Instrument (EAI) / Self-neglect Severity Scale Possible Neglect Indicators: Additional comments. Question from earlier version of follow-up interview."
    ) %>%
  
    cb_add_col_attributes( 
      money_misuse, 
      description = "Elder Assessment Instrument (EAI) / Self-neglect Severity Scale Possible Exploitation Indicators: Misuse of money. Question from earlier version of follow-up interview."
    ) %>%
  
    cb_add_col_attributes( 
      evidence, 
      description = "Elder Assessment Instrument (EAI) / Self-neglect Severity Scale Possible Exploitation Indicators: Evidence. Question from earlier version of follow-up interview."
    ) %>%
  
    cb_add_col_attributes( 
      goods_for_services, 
      description = "Elder Assessment Instrument (EAI) / Self-neglect Severity Scale Possible Exploitation Indicators: Reports of demands for goods in exchange for service. Question from earlier version of follow-up interview."
    ) %>%
  
    cb_add_col_attributes( 
      inability_account_money, 
      description = "Elder Assessment Instrument (EAI) / Self-neglect Severity Scale Possible Exploitation Indicators: Inability to account for money/property. Question from earlier version of follow-up interview."
    ) %>%
  
    cb_add_col_attributes( 
      exploitation_statement, 
      description = "Elder Assessment Instrument (EAI) / Self-neglect Severity Scale Possible Exploitation Indicators: Statement by older adult related to exploitation. Question from earlier version of follow-up interview."
    ) %>%
  
    cb_add_col_attributes( 
      exploitation_comments, 
      description = "Elder Assessment Instrument (EAI) / Self-neglect Severity Scale Possible Exploitation Indicators: Additional comments. Question from earlier version of follow-up interview."
    ) %>%
  
    cb_add_col_attributes( 
      caretaker_withdrawn_care, 
      description = "Elder Assessment Instrument (EAI) / Self-neglect Severity Scale Possible Abandonment Indicators: Evidence that a caretaker has withdrawn care precipitously without alternate arrangements. Question from earlier version of follow-up interview."
    ) %>%
  
    cb_add_col_attributes( 
      left_alone_unsafe, 
      description = "Elder Assessment Instrument (EAI) / Self-neglect Severity Scale Possible Abandonment Indicators: Evidence that older adult is left alone in an unsafe environment for extended periods of time without adequate support. Question from earlier version of follow-up interview."
    ) %>%
  
    cb_add_col_attributes( 
      abandonment_statement, 
      description = "Elder Assessment Instrument (EAI) / Self-neglect Severity Scale Possible Abandonment Indicators: Statement by older adults regarding abandonment. Question from earlier version of follow-up interview."
    ) %>%
  
    cb_add_col_attributes( 
      abandonment_comments, 
      description = "Elder Assessment Instrument (EAI) / Self-neglect Severity Scale Possible Abandonment Indicators: Additional comments. Question from earlier version of follow-up interview."
    ) %>%
  
    cb_add_col_attributes( 
      exterior_condition, 
      description = "Elder Assessment Instrument (EAI) / Self-neglect Severity Environment status of subject: Exterior condition. Question from earlier version of follow-up interview."
    ) %>%
  
    cb_add_col_attributes( 
      yard_sidewalk, 
      description = "Elder Assessment Instrument (EAI) / Self-neglect Severity Environment status of subject: Yard/Sidewalk. Question from earlier version of follow-up interview."
    ) %>%
  
    cb_add_col_attributes( 
      roof, 
      description = "Elder Assessment Instrument (EAI) / Self-neglect Severity Environment status of subject: Roof. Question from earlier version of follow-up interview."
    ) %>%
  
    cb_add_col_attributes( 
      walls, 
      description = "Elder Assessment Instrument (EAI) / Self-neglect Severity Environment status of subject: Walls Question from earlier version of follow-up interview."
    ) %>%
  
    cb_add_col_attributes( 
      windows, 
      description = "Elder Assessment Instrument (EAI) / Self-neglect Severity Environment status of subject: Windows. Question from earlier version of follow-up interview."
    ) %>%
  
    cb_add_col_attributes( 
      interior_condition, 
      description = "Elder Assessment Instrument (EAI) / Self-neglect Severity Environment status of subject: Interior condition. Question from earlier version of follow-up interview."
    ) %>%
  
    cb_add_col_attributes( 
      odor, 
      description = "Elder Assessment Instrument (EAI) / Self-neglect Severity Environment status of subject: Odor. Question from earlier version of follow-up interview."
    ) %>%
  
    cb_add_col_attributes( 
      kitchen_cleanliness, 
      description = "Elder Assessment Instrument (EAI) / Self-neglect Severity Environment status of subject: Cleanliness - Kitchen. Question from earlier version of follow-up interview."
    ) %>%
  
    cb_add_col_attributes( 
      bathroom_cleanliness, 
      description = "Elder Assessment Instrument (EAI) / Self-neglect Severity Environment status of subject: Cleanliness - Bathroom. Question from earlier version of follow-up interview."
    ) %>%
  
    cb_add_col_attributes( 
      bedroom_cleanliness, 
      description = "Elder Assessment Instrument (EAI) / Self-neglect Severity Environment status of subject: Cleanliness - Bedroom. Question from earlier version of follow-up interview."
    ) %>%
  
    cb_add_col_attributes( 
      living_room_cleanliness, 
      description = "Elder Assessment Instrument (EAI) / Self-neglect Severity Environment status of subject: Cleanliness - Living room.  Question from earlier version of follow-up interview."
    ) %>%
  
    cb_add_col_attributes( 
      clutter, 
      description = "Elder Assessment Instrument (EAI) / Self-neglect Severity Environment status of subject: Clutter. Question from earlier version of follow-up interview."
    ) %>%
  
    cb_add_col_attributes( 
      structural_problems, 
      description = "Elder Assessment Instrument (EAI) / Self-neglect Severity Environment status of subject: Structural problems. Question from earlier version of follow-up interview."
    ) %>%
  
    cb_add_col_attributes( 
      pets, 
      description = "Elder Assessment Instrument (EAI) / Self-neglect Severity Environment status of subject: Pets. Question from earlier version of follow-up interview."
    ) %>%
  
    cb_add_col_attributes( 
      utilities, 
      description = "Elder Assessment Instrument (EAI) / Self-neglect Severity Environment status of subject: Utilities. Question from earlier version of follow-up interview."
    ) %>%
  
    cb_add_col_attributes( 
      summary_evidence_abuse, 
      description = "Elder Assessment Instrument (EAI) / Self-neglect Severity Environment status of subject: Summary - Evidence of abuse. Question from earlier version of follow-up interview."
    ) %>%
  
    cb_add_col_attributes( 
      summary_evidence_neglect, 
      description = "Elder Assessment Instrument (EAI) / Self-neglect Severity Environment status of subject: Summary - Evidence of neglect. Question from earlier version of follow-up interview."
    ) %>%
  
    cb_add_col_attributes( 
      summary_evidence_exploitation, 
      description = "Elder Assessment Instrument (EAI) / Self-neglect Severity Environment status of subject: Summary - Evidence of exploitation. Question from earlier version of follow-up interview."
    ) %>%
  
    cb_add_col_attributes( 
      summary_evidence_abandonment, 
      description = "Elder Assessment Instrument (EAI) / Self-neglect Severity Environment status of subject: Summary - Evidence of abandonment. Question from earlier version of follow-up interview."
    ) %>%
  
    cb_add_col_attributes( 
      summary_comments, 
      description = "Elder Assessment Instrument (EAI) / Self-neglect Severity Environment status of subject: Summary - Additional comments. Question from earlier version of follow-up interview."
    ) %>%
  
    cb_add_col_attributes( 
      aps_reported, 
      description = ""
    ) %>%
  
    cb_add_col_attributes( 
      aps_reported_confirmation_number, 
      description = ""
    ) %>%
  
    cb_add_col_attributes( 
      aps_reported_method, 
      description = ""
    ) %>%
  
    cb_add_col_attributes( 
      at_physical, 
      description = "AT_1. Do you believe physical abuse has occurred?"
    ) %>%
  
    cb_add_col_attributes( 
      at_phys_why, 
      description = "AT_1a. Why do you believe physical abuse has or has not occurred?"
    ) %>%
  
    cb_add_col_attributes( 
      at_sexual, 
      description = "AT_2. Do you believe sexual abuse has occurred?"
    ) %>%
  
    cb_add_col_attributes( 
      at_sex_why, 
      description = "AT_2a. Why do you believe sexual abuse has or has not occurred?"
    ) %>%
  
    cb_add_col_attributes( 
      at_emotional, 
      description = "AT_3. Do you believe emotional or psychological abuse has occurred?"
    ) %>%
  
    cb_add_col_attributes( 
      at_emot_why, 
      description = "AT_3a. Why do you believe emotional or psychological abuse has or has not occurred?"
    ) %>%
  
    cb_add_col_attributes( 
      at_neglect, 
      description = "AT_4. Do you believe neglect has occurred?"
    ) %>%
  
    cb_add_col_attributes( 
      at_neg_why, 
      description = "AT_4a. Why do you believe neglect has or has not occurred?"
    ) %>%
  
    cb_add_col_attributes( 
      at_abandon, 
      description = "AT_5. Do you believe abandonment has occurred?"
    ) %>%
  
    cb_add_col_attributes( 
      at_aban_why, 
      description = "AT_5a. Why do you believe abandonment has or has not occurred?"
    ) %>%
  
    cb_add_col_attributes( 
      at_financial, 
      description = "AT_6. Do you believe financial or material exploitation has occurred?"
    ) %>%
  
    cb_add_col_attributes( 
      at_fina_why, 
      description = "AT_6a. Why do you believe financial or material exploitation has or hasn’t occurred?"
    ) %>%
  
    cb_add_col_attributes( 
      at_self, 
      description = "AT_7. Do you believe self-neglect has occurred?"
    ) %>%
  
    cb_add_col_attributes( 
      at_self_why, 
      description = "AT_7a. Why do you believe self-neglect has or has not occurred?"
    ) %>%
  
    cb_add_col_attributes( 
      clothes_5cat, 
      description = "Recoded variable clothes to match levels in follow-up interview protocol",
      value_labels = c(
        "0 - Clean/neat"  = 0,
        "1"               = 1,
        "2"               = 2,
        "3"               = 3,
        "4 - Very soiled" = 4
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      clothes_5cat_f, 
      description = "Recoded variable clothes as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      hair_5cat, 
      description = "Recoded variable hair to match levels in follow-up interview protocol",
      value_labels = c(
        "0 - Clean/combed" = 0,
        "1"                = 1,
        "2"                = 2,
        "3"                = 3,
        "4 - Matted/dirty" = 4
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      hair_5cat_f, 
      description = "Recoded hair variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      nails_5cat, 
      description = "Recoded nails variable to match levels in follow-up interview protocol",
      value_labels = c(
        "0 - Clean/trimmed"        = 0,
        "1"                        = 1,
        "2"                        = 2,
        "3"                        = 3,
        "4 - Long/untrimmed/dirty" = 4
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      nails_5cat_f, 
      description = "Recoded nails variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      bruising_f, 
      description = "Recoded bruising variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      lacerations_f, 
      description = "Recoded lacerations variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      fractures_f, 
      description = "Recoded fractures variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      stages_healing_f, 
      description = "Recoded stages_healing variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      sexual_abuse_f, 
      description = "Recoded sexual_abuse variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      abuse_statement_f, 
      description = "Recoded abuse_statement as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      contracture_f, 
      description = "Recoded contracture variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      decubitus_f, 
      description = "Recoded decubitus variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      dehydration_f, 
      description = "Recoded dehydration variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      diarrhea_f, 
      description = "Recoded diarrhea variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      depression_f, 
      description = "Recoded depression variabe as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      impaction_f, 
      description = "Recoded impaction variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      malnutrition_f, 
      description = "Recoded malnutrition variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      urine_burn_f, 
      description = "Recoded urine_burn variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      poor_hygiene_f, 
      description = "Recoded poor_hygiene variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      obvious_disease_f, 
      description = "Recoded obvious_disease as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      inappropriate_medication_f, 
      description = "Recoded inappropriate_medication variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      repetitive_hosp_admission_f, 
      description = "Recoded repetitive_hosp_admission as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      neglect_statement_f, 
      description = "Recoded neglect_statement as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      money_misuse_f, 
      description = "Recoded money_misuse as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      evidence_f, 
      description = "Recoded evidence as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      goods_for_services_f, 
      description = "Recoded goods_for_services as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      inability_account_money_f, 
      description = "Recoded inability_account_money as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      exploitation_statement_f, 
      description = "Recoded exploitation_statement as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      caretaker_withdrawn_care_f, 
      description = "Recoded caretaker_withdrawn_care as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      left_alone_unsafe_f, 
      description = "Recoded left_alone_unsafe as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      abandonment_statement_f, 
      description = "Recoded abandonment_statement as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      exterior_condition_5cat, 
      description = "Recoded exterior_condition variable to match levels in follow-up interview protocol",
      value_labels = c(
        "0 - Neat/well kept/no trash, debris"       = 0,
        "1"                                         = 1,
        "2"                                         = 2,
        "3"                                         = 3,
        "4 - Poorly maintained/trash, other debris" = 4
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      exterior_condition_5cat_f, 
      description = "Recoded exterior_condition variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      yard_sidewalk_5cat, 
      description = "Recoded yard_sidewalk variable to match levels in follow-up interview protocol",
      value_labels = c(
        "0 - Neat/well kept/no trash, debris" = 0,
        "1"                                   = 1,
        "2"                                   = 2,
        "3"                                   = 3,
        "4 - Poorly maintained/trash, debris" = 4
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      yard_sidewalk_5cat_f, 
      description = "Recoded yard_sidewalk variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      roof_5cat, 
      description = "Recoded roof variable to match levels in follow-up interview protocol",
      value_labels = c(
        "0 - Intact/no structural damage"          = 0,
        "1"                                        = 1,
        "2"                                        = 2,
        "3"                                        = 3,
        "4 - Dilapidated/poorly maintained, holes" = 4
      ), 
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      roof_5cat_f, 
      description = "Recoded roof variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      walls_5cat, 
      description = "Recoded walls variable to match levels in follow-up interview protocol",
      value_labels = c(
        "0 - Intact/no structural damage"          = 0,
        "1"                                        = 1,
        "2"                                        = 2,
        "3"                                        = 3,
        "4 - Dilapidated/poorly maintained, holes" = 4
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      walls_5cat_f, 
      description = "Recoded walls variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      windows_5cat, 
      description = "Recoded windows variable to match levels in follow-up interview protocol",
      value_labels = c(
        "0 - Intact/not broken or missing"     = 0,
        "1"                                    = 1,
        "2"                                    = 2,
        "3"                                    = 3,
        "4 - Multiple sections broken/missing" = 4
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      windows_5cat_f, 
      description = "Recoded windows variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      interior_condition_5cat, 
      description = "Recoded interior_condition varible to match levels in follow-up interview protocol",
      value_labels = c(
        "0 - Intact/not broken or missing"     = 0,
        "1"                                    = 1,
        "2"                                    = 2,
        "3"                                    = 3,
        "4 - Multiple sections broken/missing" = 4
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      interior_condition_5cat_f, 
      description = "Recoded interior_condition variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      odor_5cat, 
      description = "Recoded odor variable to match levels in follow-up interview protocol",
      value_labels = c(
        "0 - Normal household odor"                                              = 0,
        "1"                                                                      = 1,
        "2"                                                                      = 2,
        "3"                                                                      = 3,
        "4 - Pungent, unpleasant odor (may be human/animal waste, rotting food)" = 4
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      odor_5cat_f, 
      description = "Recoded odor variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      kitchen_cleanliness_5cat, 
      description = "Recoded kitchen_cleanliness variable to match levels in follow-up interview protocol",
      value_labels = c(
        "0 - Clean, no evidence of unsanitary conditions" = 0,
        "1"                                               = 1,
        "2"                                               = 2,
        "3"                                               = 3,
        "4 - Very dirty, unwashed dishes, trash litter"   = 4
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      kitchen_cleanliness_5cat_f, 
      description = "Recoded kitchen_cleanliness variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      bathroom_cleanliness_5cat, 
      description = "Recoded bathroom_cleanliness variable to match levels in follow-up interview protocol",
      value_labels = c(
        "0 - Clean, no evidence of unsanitary conditions"  = 0,
        "1"                                                = 1,
        "2"                                                = 2,
        "3"                                                = 3,
        "4 - Very dirty, unwashed dishes, trash litter"    = 4
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      bathroom_cleanliness_5cat_f, 
      description = "Recoded bathroom_cleanliness as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      bedroom_cleanliness_5cat, 
      description = "Recoded bedroom_cleanliness variable to match levels in follow-up interview protocol",
      value_labels = c(
        "0 - Clean, no evidence of unsanitary conditions" = 0,
        "1"                                               = 1,
        "2"                                               = 2,
        "3"                                               = 3,
        "4 - Very dirty, unwashed dishes, trash litter"   = 4
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      bedroom_cleanliness_5cat_f, 
      description = "Recoded bedroom_cleanliness variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      living_room_cleanliness_5cat, 
      description = "Recoded living_room_cleanliness variable to match levels in follow-up interview protocol",
      value_labels = c(
        "0 - Clean, no evidence of unsanitary conditions" = 0,
        "1"                                               = 1,
        "2"                                               = 2,
        "3"                                               = 3,
        "4 - Very dirty, unwashed dishes, trash litter"   = 4
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      living_room_cleanliness_5cat_f, 
      description = "Recoded living_room_cleanliness variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      clutter_5cat, 
      description = "Recoded clutter variable to match levels in follow-up interview protocol",
      value_labels = c(
        "0 - Neat/orderly"                                             = 0,
        "1"                                                            = 1,
        "2"                                                            = 2,
        "3"                                                            = 3,
        "4 - Very cluttered/difficult to move around or find things"   = 4
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      clutter_5cat_f, 
      description = "Recoded clutter variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      structural_problems_5cat, 
      description = "Recoded structural_problems variable to match levels in follow-up interview protocol",
      value_labels = c(
        "0 - No structural problems"                                                     = 0,
        "1"                                                                              = 1,
        "2"                                                                              = 2,
        "3"                                                                              = 3,
        "4 - Severe structural damage (e.g., holes in sheetrock, floor leaking, ceiling" = 4
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      structural_problems_5cat_f, 
      description = "Recoded structural_problems variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      pets_5cat, 
      description = "Recoded pets variable to match levels in follow-up interview protocol",
      value_labels = c(
        "0 - All animals cared for"    = 0,
        "1 or 2 - Uncared animals"     = 1,
        "3 or 4 - Uncared animals"     = 2,
        "5 or 6 - Uncared animals"     = 3,
        "6 or more -  Uncared animals" = 4
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      pets_5cat_f, 
      description = "Recoded pets variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      utilities_5cat, 
      description = "Recoded utilities variable to match levels in follow-up interview protocol",
      value_labels = c(
        "0 - All utilities work"             = 0,
        "1 - No phone"                       = 1,
        "2 - No gas/electricity"             = 2,
        "3 - No water"                       = 3,
        "4 - Multiple utilities do not work" = 4
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      utilities_5cat_f, 
      description = "Recoded utilities variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      summary_evidence_abuse_f, 
      description = "Recoded summary_evidence_abuse variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      summary_evidence_neglect_f, 
      description = "Recoded summary_evidence_neglect variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      summary_evidence_exploitation_f, 
      description = "Recoded summary_evidence_exploitation variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      summary_evidence_abandonment_f, 
      description = "Recoded summary_evidence_abandonment variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      aps_reported_f, 
      description = "Recoded aps_reported variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      aps_reported_method_f, 
      description = "Recoded aps_reported_method variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      at_physical_4cat, 
      description = "Recoded at_physical variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      at_sexual_4cat, 
      description = "Recoded at_sexual variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      at_emotional_4cat, 
      description = "Recoded at_emotional variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      at_neglect_4cat, 
      description = "Recoded at_neglect variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      at_abandon_4cat, 
      description = "Recoded at_abandon variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      at_financial_4cat, 
      description = "Recoded at_financial variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      at_self_4cat, 
      description = "Recoded at_self variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      at_physical_4cat_f, 
      description = "Recoded at_physical variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      at_sexual_4cat_f, 
      description = "Recoded at_sexual variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      at_emotional_4cat_f, 
      description = "Recoded at_emotional variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      at_neglect_4cat_f, 
      description = "Recoded at_neglect variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      at_abandon_4cat_f, 
      description = "Recoded at_abandon variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      at_financial_4cat_f, 
      description = "Recoded at_financial variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      at_self_4cat_f, 
      description = "Recoded at_self variable as a factor variable"
    )
```


# Pass data frame to the codebook() function

```{r}
# Add title and description to codebook
obs_codebook <- codebook(
  df = obs,
  title = "Observational Measures Dataset",
  description = "Data collected during DETECT follow-up interviews on  Observational Measures of Elder Abuse, Neglect, and Exploitation",
  no_summary_stats = no_stats_vars) 
```

```{r}
print(obs_codebook, "basic_obs_codebook.docx")
```
