---
#title: "CodebookR Sociodemographic Information data from recoded data"
#author: "Marissa Gough"
---

```{r}
# Load necessary packages
library(codebookr)
library(dplyr, warn.conflicts = FALSE)
library(readr)
```

# Purpose of the program

Using the CodebookR package, we will create a data dictionary for follow-up interview data for the DETECT project.

```{r, encoding = "utf-8"}
# Load data from Sociodemographic Information Data Set
socdem <- read_rds("~/OneDrive - The University of Texas Health Science Center at Houston/DETECT - SPH Cannell Research - DETECT/detect_public/data/socdem_factor.rds") #600 63
```

```{r}
# Remove vertical tab data frame
# for example, remove all spaces
socdem <- socdem %>% 
  mutate(across(where(is.character), str_remove_all, pattern = fixed("\v")))
```

# Set column attributes

```{r}
# Create a vector of column names that have the same source, in this case administrative data
admin_vars <- socdem %>% 
  select(1:16) %>%  # Choose the first columns in the data frame
  names()

for(i in admin_vars) {
  attr(socdem[[i]], "source") <- "Administrative data"
}
```

```{r}
# Create a vector of column names that have the same source, in this case Sociodemographic Information data from DETECT Follow-up Interview
socdem_vars <- socdem %>% 
  select(sode_people:hsi_contact) %>%  
  names()

for(i in socdem_vars) {
  attr(socdem[[i]], "source") <- "DETECT Follow-up Interview Sociodemographic Information"
}
```

```{r}
# Create a vector of column names that have the same source, in this case recoded factor variables
factor_vars <- socdem %>% 
  select(sode_marital_8cat:hsi_contact_4cat_f) %>%  #Choose the recoded variables
  names()

for(i in factor_vars) {
  attr(socdem[[i]], "source") <- "Recoded from raw data"
}
```




```{r}
# Create a template for all variables in the data frame
for (i in seq_along(names(socdem))) {
  cat(paste0('
    cb_add_col_attributes( \n    ',
      "  ", names(socdem)[i], ', \n    ',
      "  ", 'description = ""
    ) %>%
  '))
}
```

```{r}
# Add column attributes to all variables
socdem <- socdem %>%
    cb_add_col_attributes( 
      x_created_by, 
      description = "Person who created the record"
    ) %>%
  
    cb_add_col_attributes( 
      x_created_timestamp, 
      description = "Timestamp when the record was created",
      col_type = "Time"
    ) %>%
  
    cb_add_col_attributes( 
      x_modified_by, 
      description = "Person who modified the record"
    ) %>%
  
    cb_add_col_attributes( 
      x_modified_timestamp, 
      description = "Timestamp when the record was modified",
      col_type = "Time"
    ) %>%
  
    cb_add_col_attributes( 
      x_error_message, 
      description = "Error message entered by research team"
    ) %>%
  
    cb_add_col_attributes( 
      x_record_month, 
      description = "Month record was created",
      col_type = "Time"
    ) %>%
  
    cb_add_col_attributes( 
      x_record_year, 
      description = "Year record was created",
      col_type = "Time"
    ) %>%
  
    cb_add_col_attributes( 
      x_record_status, 
      description = "Status of the record as determined by research team"
    ) %>%
  
    cb_add_col_attributes( 
      x_record_comment, 
      description = "Comments by interviewer"
    ) %>%
  
    cb_add_col_attributes( 
      medstar_id, 
      description = "Unique record number in MedStar System"
    ) %>%
  
    cb_add_col_attributes( 
      name_full, 
      description = "Full name of older individual"
    ) %>%
  
    cb_add_col_attributes( 
      sex, 
      description = "Sex of older individual"
    ) %>%
  
    cb_add_col_attributes( 
      dob, 
      description = "Date of birth of older individual"
    ) %>%
  
    cb_add_col_attributes( 
      age, 
      description = "Age, in years, of older individual"
    ) %>%
  
    cb_add_col_attributes( 
      race, 
      description = "Race of older individual"
    ) %>%
  
    cb_add_col_attributes( 
      zip_code, 
      description = "Zip code of older individual"
    ) %>%
  
    cb_add_col_attributes( 
      sode_people, 
      description = "SI_1. Including you how many people live in this household?",
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sode_marital, 
      description = "SI_2. What is your marital status? Would you say you are…"
    ) %>%
  
    cb_add_col_attributes( 
      sogi_identity, 
      description = "SOGI_1. What is your gender identity?"
    ) %>%
  
    cb_add_col_attributes( 
      sogi_orientation, 
      description = " SOGI_2. What best describes your sexual orientation?"
    ) %>%
  
    cb_add_col_attributes( 
      sode_age, 
      description = "SI_3. How old are you?"
    ) %>%
  
    cb_add_col_attributes( 
      sode_age_years, 
      description = "Reported age of older individual"
    ) %>%
  
    cb_add_col_attributes( 
      sode_hispanic, 
      description = "SI_4. Are you of Hispanic or Latino origin?"
    ) %>%
  
    cb_add_col_attributes( 
      sode_race, 
      description = "SI_5. Which of the following racial categories describes you? You may select more than one."
    ) %>%
  
    cb_add_col_attributes( 
      sode_school, 
      description = "SI_6. What is the highest level of schooling you completed"
    ) %>%
  
    cb_add_col_attributes( 
      sode_employed, 
      description = "SI_7. What is your employment status? Would you say you are…"
    ) %>%
  
    cb_add_col_attributes( 
      sode_income, 
      description = "SI_8. Including everyone else in your household, which of the following categories best describes your total household income before taxes? Is it.."
    ) %>%
  
    cb_add_col_attributes( 
      sode_military, 
      description = "SI_9. Have you ever served in the military (e.g., on active duty in the U.S. Armed Forces, Reserves, or National Guard)?", 
      skip_pattern = "If answer is yes, go to SI_10. For all other answers, go to SI_11"
    ) %>%
  
    cb_add_col_attributes( 
      sode_unwanted, 
      description = "When you were in the military: SI_10.  Did you ever receive unwanted, threatening or repeated sexual attention (for example, touching, cornering, pressure for sexual favors, or inappropriate verbal remarks, etc.?)"
    ) %>%
  
    cb_add_col_attributes( 
      sode_sexual, 
      description = "SI_11. Did you have sexual contact against your will or when you were unable to say no (for example, after being forced or threatened or to avoid other consequences?)"
    ) %>%
  
    cb_add_col_attributes( 
      hsi_contact, 
      description = "HS_1. Would it be alright if we contact you again in the future?"
    ) %>%
  
    cb_add_col_attributes( 
      sode_marital_8cat, 
      description = "Recoded variable sode_marital to match levels in follow-up interview protocol",
      value_labels = c(
        "Married"                                     = 1,
        "Living as an unmarried or common law couple" = 2,
        "Separated"                                   = 3,
        "Divorced"                                    = 4,
        "Widowed"                                     = 5,
        "Single, or never married"                    = 6,
        "Don’t know"                                  = 7,
        "Refused"                                     = 9
      )
    ) %>%
  
    cb_add_col_attributes( 
      sode_marital_8cat_f, 
      description = "Recoded variable sode_marital as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      sogi_identity_5cat, 
      description = "Recoded sogi_identity variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Male"       = 1,
        "Female"     = 2,
        "Other"      = 3,
        "Don’t know" = 7,
        "Refused"    = 9
      )
    ) %>%
  
    cb_add_col_attributes( 
      sogi_identity_5cat_f, 
      description = "Recoded sogi_identity variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      sogi_orientation_8cat, 
      description = "Recoded sogi_orientation variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Straight/heterosexual" = 1,
        "Gay man"               = 2,
        "Lesbian/gay woman"     = 3,
        "Bisexual"              = 4,
        "Queer"                 = 5,
        "Other"                 = 6,
        "Don’t know"            = 7,
        "Refused"               = 9
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sogi_orientation_8cat_f, 
      description = "Recode sogi_orientation variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      sode_age_4cat, 
      description = "Recode sode_age variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Age 65 to 100+" = 1,
        "Don’t know"     = 7,
        "Refused"        = 9
      )
    ) %>%
  
    cb_add_col_attributes( 
      sode_age_4cat_f, 
      description = "Recoded sode_age variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      sode_hispanic_4cat, 
      description = "Recoded sode_hispanic variable to match levels in follow-up interview protocol", 
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      )
    ) %>%
  
    cb_add_col_attributes( 
      sode_hispanic_4cat_f, 
      description = "Recoded sode_hispanic variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      race_american_indian, 
      description = "Created dummy variable for sode_race variable answer American Indian or Alaskan Native since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      )
    ) %>%
  
    cb_add_col_attributes( 
      race_asian, 
      description = "Created dummy variable for sode_race variable answer Asian since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      )
    ) %>%
  
    cb_add_col_attributes( 
      race_black, 
      description = "Created dummy variable for sode_race variable answer Black or African American since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      )
    ) %>%
  
    cb_add_col_attributes( 
      race_pacific_islander, 
      description = "Created dummy variable for sode_race variable anwer Native Hawaiian or Other Pacific Islander since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      )
    ) %>%
  
    cb_add_col_attributes( 
      race_white, 
      description = "Created dummy variable for sode_race variable White since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      )
    ) %>%
  
    cb_add_col_attributes( 
      race_other, 
      description = "Created dummy variable for sode_race variable anwer Other since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      )
    ) %>%
  
    cb_add_col_attributes( 
      race_dont_know, 
      description = "Created dummy variable for sode_race variable anwer Don't know since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      )
    ) %>%
  
    cb_add_col_attributes( 
      race_refused, 
      description = "Created dummy variable for sode_race variable anwer Refused since individuals could choose more than one answer for this category",
      value_labels = c(
        "False" = 0,
        "True"  = 1
      )
    ) %>%
  
    cb_add_col_attributes( 
      sode_school_9cat, 
      description = "Recoded sode_school variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Some high school (no diploma)"                                  = 1,
        "High school graduate"                                           = 2,
        "Some college (no degree)"                                       = 3,
        "Associate’s degree"                                             = 4,
        "Bachelor’s degree (BA, AB, BS, etc.)"                           = 5,
        "Some graduate or professional school (no degree)"               = 6,
        "Graduate or professional school degree (MS, MA, MD, PhD, etc.)" = 7,
        "Don’t know"                                                     = 77,
        "Refused"                                                        = 99
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sode_school_9cat_f, 
      description = "Recoded sode_school variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      sode_employed_11cat, 
      description = "Recoded sode_employed variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Employed full time"         = 1,
        "Employed part time"         = 2,
        "In the military"            = 3,
        "Unemployed"                 = 4,
        "Retired"                    = 5,
        "A student"                  = 6,
        "A homemaker"                = 7,
        "Disabled or unable to work" = 8,
        "Something else"             = 9,
        "Don’t know"                 = 77,
        "Refused"                    = 99
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sode_employed_11cat_f, 
      description = "Recoded sode_employed variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      sode_income_9cat, 
      description = "Recoded sode_income variable to match levels in follow-up interview protocol",
      value_labels = c(
        "$10,000 or less"              = 1,
        "Between $10,001 and $20,000"  = 2,
        "Between $20,001 and $35,000"  = 3,
        "Between $35,001 and $50,000"  = 4,
        "Between $50,001 and $75,000"  = 5,
        "Between $75,001 and $100,000" = 6,
        "More than $100,000"           = 7,
        "Don’t know"                   = 77,
        "Refused"                      = 99
      ),
      col_type = "Categorical"
    ) %>%
  
    cb_add_col_attributes( 
      sode_income_9cat_f, 
      description = "Recoded sode_income variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      sode_military_4cat, 
      description = "Recoded sode_military variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      )
    ) %>%
  
    cb_add_col_attributes( 
      sode_military_4cat_f, 
      description = "Recoded sode_military variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      sode_unwanted_4cat, 
      description = "Recoded sode_unwanted variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      )
    ) %>%
  
    cb_add_col_attributes( 
      sode_unwanted_4cat_f, 
      description = "Recoded sode_unwanted variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      sode_sexual_4cat, 
      description = "Recoded sode_sexual variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      )
    ) %>%
  
    cb_add_col_attributes( 
      sode_sexual_4cat_f, 
      description = "Recoded sode_sexual variable as a factor variable"
    ) %>%
  
    cb_add_col_attributes( 
      hsi_contact_4cat, 
      description = "Recoded hsi_contact variable to match levels in follow-up interview protocol",
      value_labels = c(
        "Yes"        = 1,
        "No"         = 2,
        "Don't know" = 7,
        "Refused"    = 9
      )
    ) %>%
  
    cb_add_col_attributes( 
      hsi_contact_4cat_f, 
      description = "Recoded hsi_contact variable as a factor variable"
    )
  
```

# Pass data frame to the codebook() function

```{r}
# Add title and description to codebook
socdem_codebook <- codebook(
  df = socdem,
  title = "Sociodemographic Information Dataset",
  description = "Data collected during DETECT follow-up interviews about sociodemographic information",
  no_summary_stats = admin_vars)
```

```{r}
print(socdem_codebook, "socdem_codebook.docx")
```


```{r}
```

